### DISCUSSION TITLE
Containerlab Linux node: ssh access

### DISCUSSION THREAD

**Discussion by sdktr** [ipspace/netlab#1007] [Q&A] [answered]
Does anyone have a working config for specifying SSH as the mgmt interface for a Linux node (docker image) with clab provider?

If I understand the logic correctly, the access method is derived by the ```ansible_connection``` or ```netlab_console_connection```, but both these settings don't seem allowed node or group attributes.

**Comment by ipspace** [comment]
You can use custom group Ansible variables -- it seems the order of groups in `inventory.yml` ensures the custom group variables overwrite device-specific groups. For example:

```
provider: clab

groups:
  linux_ssh:
    members: [ h ]
    vars:
      ansible_connection: ssh

nodes:
  h:
    device: linux
````

FWIW, make sure you're using containers that include a preconfigured SSH server.

**Reply by sdktr** [reply]
I'm assuming the ```netlab connect``` command should follow the connection method specified here? In that case it didn't work out for me using:
```yaml
plugin: [multilab]

defaults:
  multilab.id: 7
  device: linux


groups:
  linux_ssh:
    members: [ x1 ]
    vars:
      ansible_connection: ssh

nodes:
  - name: x1
```

```
<snip>
~/netlab/lab7-linux$ netlab connect x1 -v
Executing: ['docker', 'exec', '-it', 'clab-ml_7-x1', 'sh', '-il']
x1:~# 
```

**Reply by sdktr** [reply]
So, in the source for ```netlab connect``` cli [here](https://github.com/ipspace/netlab/blob/ab2440b10252fe5a2125c530216aaa84f927888e/netsim/cli/connect.py#L175) it can be found that the CLI tool does a lookup to the inventory data using [the snapshot](https://github.com/ipspace/netlab/blob/ab2440b10252fe5a2125c530216aaa84f927888e/netsim/cli/__init__.py#L120)

This snapshot is the only place that contains the wrong data:
```yaml
    linux:
      clab:
        group_vars:
          ansible_connection: docker
```
In the Ansible host and group vars the value is overwritten. So my assumption is that if ansible were to interact with this node, it will use SSH.

Edit: validated ansible view of the inventory:
```
~/netlab/lab7-linux$ ansible-inventory --list | jq ._meta.hostvars.x1.ansible_connection
"ssh"
```
vs the netlab.snapshot.yaml view of the inventory:
```
cat netlab.snapshot.yml | yq .defaults.devices.linux.clab.group_vars.ansible_connection
"docker"
```
