### DISCUSSION TITLE
Nokia SROS 100G breakout ports

### DISCUSSION THREAD

**Discussion by sdktr** [ipspace/netlab#1030] [General]
Nokia SROS when provisioned on a 100G+ platform ([IXR-X1](https://github.com/hellt/vrnetlab/pull/156) for example) still requires a breakout config even if the port is dedicated to just one link. This logic is not in netlab at the moment, so we have no out-of-the-box working configs for two nodes connecting on 100G.

Just wanted to confirm with @jbemmel that I'm drawing the right conclusion here. 

Repro:
```yaml
provider: clab
defaults:
  device: sros
nodes:
  S1:
    module: [ bfd, ospf ]
    clab.type: ixr-x1

  S2:
    module: [ bfd, ospf ]
    clab.type: ixr-x1

links:
- S1-S2
```

Provisioned ports are in the format:
1/1/c1.

this errors during the configuration of the ethernet port ('capabilities ethernet not supported on  port 1/1/c1')

A breakout-but-no-breakout-config is configured as:
```
    port 1/1/c1 {
        admin-state enable
        connector {
            breakout c1-100g
        }
    }
    port 1/1/c1/1 {
        admin-state enable
    }
```
