### DISCUSSION TITLE
Should routed interfaces created from a VLAN with mode 'route' honor the prefix assigned to that VLAN?

### DISCUSSION THREAD

**Discussion by jbemmel** [ipspace/netlab#1114] [General]
Acknowledging all the caveats around 'route' mode VLANs, an example (trying to showcase all options):
```
vlans:
  bridge:
    mode: bridge
    links: [ s1-h1, s2-h2 ]
    # isis.metric: 20
  irb:
    mode: irb
    id: 32
    links: [ s1-h3, s2-h4 ]
    pool: vlan32
    gateway: True
  route:
    mode: route
    prefix:
      ipv4: 172.31.1.0/24
    links: [ s1-h5, s2-h6 ]
```

The ```route``` VLAN is created as a subinterface, but its IP address is not taken from ```172.31.1.0/24```
