### DISCUSSION TITLE
"More intelligence" around default BGP sessions

### DISCUSSION THREAD

**Discussion by jbemmel** [ipspace/netlab#1329] [General]
If not specified, the BGP module assumes both ```ibgp``` and ```ebgp``` sessions should be established:
```
attributes:
  global:
   ...
    sessions:
      ipv4: [ ibgp, ebgp ]
```

Would it make sense to change this, and assume no ```ibgp``` if the user included an IGP module and no EVPN for example?
Is it possible to infer user intent - or would that become too presumptuous?

I built a simple topology using OSPF and BGP, and figured it might be hard to find how to disable IBGP sessions
