### DISCUSSION TITLE
ifindex attribute at link level

### DISCUSSION THREAD

**Discussion by jbemmel** [ipspace/netlab#1340] [Features]
Small feature - I'd like to declare a single ```ifindex``` attribute for a link, and have it applied to all (usually 2) interfaces on that link.
For consistency when deploying pairs of devices, it's usually easiest if the same ports are used on both sides

I can create a PR if no objections

**Comment by ipspace** [comment]
That would only work for containers where containerlab names the interfaces anything it wishes when creating them in the container namespace. There's no such direct connection between libvirt interfaces and VM interfaces.

Also, don't we already have **ifindex** on interface-on-a-link level? What's wrong with that?

Finally, the current code does not check for overlapping values, so you might get some interesting problems.

In my opinion, including this in netlab core is too much hassle for too little impact (plus giving people too much rope to hang themselves).

**Reply by jbemmel** [reply]
This is just to populate ```ifindex``` consistently on both ends of a p2p link for example:
```
links:
- r1:
  r2:
  ifindex: 49 # To select 100G port 1/1/49 on both sides - assumes both are the same type of device
```
instead of
```
links:
- r1:
    ifindex: 49
  r2:
    ifindex: 49
```

The semantics are to copy the link attribute to the interfaces, unless the interface already has a value
