### DISCUSSION TITLE
vlan: More consistent static IP consistency checks

### DISCUSSION THREAD

**Discussion by jbemmel** [ipspace/netlab#1440] [Features]
```
---
defaults.device: frr
module: [vlan]

vlans:
 access:

nodes:
 n1:
  vlans:
   access:
    ipv4: 1
 n2:

links:
- n1:
    vlan.access: access
    ipv4: 2  # This is the one we end up with
  n2:
- n1:
    vlan.access: access
    ipv4: 3  # This gets ignored
  n2:
```

Arguably, the above topology should throw an error at ```ipv4: 2``` because the user put ```ipv4: 1``` at the node level.
We could allow ```ipv4: True``` (and keep .1)

If ```ipv4: 1``` were removed, ```ipv4: 3``` should throw an error (instead of getting ignored)
