### DISCUSSION TITLE
Cumulus Point to point links with switch port specified

### DISCUSSION THREAD

**Discussion by SudarshanVK** [ipspace/netlab#1452] [Q&A]
Hey All, 

I have a rather large cumulus environment that we are looking to lab out and maintain as a digital twin. Currently we are using vanilla Vagrant and the topology convert that Cumulus provides. I would love to move to netlab as it seems more manageable but having one issue.

I want to be able to specify connectivity between by specifying the port number.

For example , if i wanted `swp6` on router1 connect to `swp7` on router2, what I gather from the documentation is I would define my topology like the below? All of my links are either Layer2 or unnumbered. We run a vxlan fabric. Any help on this would be appreciated. 

```yaml
provider: libvirt
defaults.device: cumulus_nvue

nodes:
  - {"name": "router1", "image": "CumulusCommunity/cumulus-vx:5.10.0"}
  - {"name": "router2", "image": "CumulusCommunity/cumulus-vx:5.10.0"}

links:
  - {"router1": {"ifindex": 6}, "router2": {"ifindex": 7}}

addressing:
  mgmt:
    ipv4: 192.168.100.0/24
    mac: 08-4F-A9-00-00-00
    prefix: 24
    start: 20

```

**Comment by SudarshanVK** [comment]
Some observations,

1. Just mentioning links without `ifindex` works fine, it connects the swp1 on both the devices to each other, shows up in lldp, has an ipaddress assigned and able to ping eachother.
2. With the `ifindex` mentioned, the swithchport is configured. when i cat `/etc/network/interfaces` i see a description and an ipaddress? but does not show up in lldp and unable to ping eachother.

Also, how can I configure them as unnumbered?

**Reply by ipspace** [reply]
> 2. With the `ifindex` mentioned, the swithchport is configured. when i cat `/etc/network/interfaces` i see a description and an ipaddress? but does not show up in lldp and unable to ping eachother.

OK, so you must be using VMs. KVM creates what look like virtual NICs when starting the VM, and the VM operating system detect those NICs and assign them names (usually starting with **swp1**).

We can specify whatever interface we wish in the `/etc/network/interfaces`, if it does not exist on the system, it's ignored.

> Also, how can I configure them as unnumbered?

Once we'll figure out the interface naming everything else will click together.

**Comment by ipspace** [comment]
> I want to be able to specify connectivity between by specifying the port number.

You're doing exactly the right thing, but there's a gotcha -- the static "ifindex" changes the interface name in device configuration, but  not necessarily the underlying virtualization configuration.

It works well with physical devices (for obvious reasons), and it works with containers (because containerlab allows us to name the container Ethernet interfaces whatever we wish), but not with VMs.

When using VMs, we configure the VM interfaces linearly from the node **interfaces** list, and the VM operating system maps those virtual NIC cards into interface names in whatever way it wishes.

I see two potential ways to solve this:

1. Reshuffle the interfaces based on ifindex and insert bogus interfaces before creating Vagrantfile
2. Renaming interface within Cumulus Linux.

It would be ideal if you could figure out how to do #2 ;) and then I could integrate that into the initial configuration template, or I could write a plugin (because I'm not sure I want to have that as part of core functionality) to do #1.

Finally, it seems you're using a really old way of specifying the nodes. It would be great if you could point me to where you found it so I could fix that. A much simpler way of specifying the nodes is with a dictionary. Instead of:

```
nodes:
  - {"name": "router1", "image": "CumulusCommunity/cumulus-vx:5.10.0"}
  - {"name": "router2", "image": "CumulusCommunity/cumulus-vx:5.10.0"}
```

... you could have:

```
nodes:
  router1:
  router2:
```

**Comment by SudarshanVK** [comment]
Hey Ivan, Please excuse my lack of understanding. Its only been a few months of me working with Cumulus. I have taken it over from someone who was not very forthcoming with information. I have no idea how I would even approach #2. 

With regards to #1, Do you mean I add bogus interfaces from swp1 to swp5 on router1? Can you give me an example of how the topology file would look in that case? 

With respect to the format, I can not seem to re-collect where i picked it from, obviously some example but I am just not able to get the link.

**Reply by ipspace** [reply]
> I have no idea how I would even approach #2.

OK, I'll work on #1.

> With regards to #1, Do you mean I add bogus interfaces from swp1 to swp5 on router1?

That would work, but it's a nice challenge, so I'll fix it with a plugin.

> Can you give me an example of how the topology file would look in that case?

You would have to add links with a single node attached to them and using **l2only** pool so they don't get IPv4/IPv6 addresses.  But please don't waste you time on that, wait for the plugin.

Example:

```
links:
- router1:
  pool: l2only
- router1:
  pool: l2only
```

I have a few topologies like that in the BGP labs repository, for example https://github.com/bgplab/bgplab/blob/master/session/2-asoverride/topology.yml

**Reply by SudarshanVK** [reply]
ah ok.. let me try with `pool: l2only`

By plugin do you mean add the dummy interfaces while generating the Vagrant file?
I was thinking worst case, I would write my won jinja2 template to generate the dummy interfaces and then use `netlab`.

**Reply by SudarshanVK** [reply]
Not quite, even after setting it to `pool: l2only` It seems to assign an IP address.

**Reply by ipspace** [reply]
> Not quite, even after setting it to `pool: l2only` It seems to assign an IP address.

Are you setting **pool: l2only** on the link (left-aligned with the device name) or within the device name?

**Reply by SudarshanVK** [reply]
ok, got it working now.. thank you..

**Comment by SudarshanVK** [comment]
Ok, some progress this works. 
But it seems to assign an IP address. 

```yaml
---
provider: libvirt
defaults.device: cumulus_nvue

nodes:
  router1:
    image: CumulusCommunity/cumulus-vx:5.10.0
  router2:
    image: CumulusCommunity/cumulus-vx:5.10.0

links:
  - router1:
      ifindex: 1
  - router2:
      ifindex: 1
  - router1:
      ifindex: 2
    router2:
      ifindex: 2

```
