### DISCUSSION TITLE
Composite topologies

### DISCUSSION THREAD

**Discussion by jbemmel** [ipspace/netlab#151] [Ideas]
Currently topologies are flat, consisting of a single level of nodes and links. However, some topologies have a regular structure that is best expressed as a multi-level topology:

```
nodes:
 superspine1:
 superspine2:
 pod1:
  topology: pod.yml
  device: srlinux
 pod2:
  topology: pod.yml
  device: ceos

links:
- [ superspine1, pod1.spine1 ]
- [ superspine1, pod1.spine2 ]
- [ superspine1, pod2.spine1 ]
- [ superspine1, pod2.spine2 ]
- ... etc

pod.yml:
nodes:
 spine1:
 spine2:
 ... etc

```

'pod.yml' need not be a separate YAML file, there could be a way to embed multiple nodes+links structures in a single file

**Comment by ipspace** [comment]
Implementing included topology files is a no-brainer. Requires a bit of renaming within the included data structure, but not more.

The interesting thing is "how do we do it within a single topology file". We're almost there with **groups**, so we could just reuse **groups**, adding **device**, **nodes** and **links** attributes to individual groups.

Alternatively, we could add named sub-topologies (or whatever you want to call them) as top-level elements in the topology file (probably better than messing with **groups**), and include them in **nodes** somehow. Any idea how you'd like that glue to look like?

**Reply by jbemmel** [reply]
I would make sub-topologies an optional add-on, leaving groups as they are.

For example:
```
sub-topologies:
 pod:
  defaults:
   device: srlinux
  nodes:
   a:
   b:
   c:
  links: [ a-b, b-c, c-a ]

nodes:
 pod1:
  topology: pod
 pod2:
  topology: pod

links: [ pod1.a, pod2.b ]
```
