### DISCUSSION TITLE
stp.priority doesn't seem to be working?

### DISCUSSION THREAD

**Discussion by ddutt** [ipspace/netlab#1539] [Q&A]
Here's the relevant section of my node for s1:
```
  s1:
    module: [vlan, stp, gateway]
    vlans:
      blue:
        ipv4: 172.16.1.1/24
        stp.priority: 4096
        vlan.mode: route
        gateway:
          vrrp.priority: 100
      red:
        ipv4: 172.16.2.2/24
        stp.priority: 8192
        vlan.mode: route
        gateway:
          vrrp.priority: 200
      green:
        ipv4: 172.16.3.2/24
        stp.priority: 8192
        vlan.mode: route
        gateway:
          vrrp.priority: 200
      cyan:
        ipv4: 172.16.4.1/24
        stp.priority: 4096
        vlan.mode: route
        gateway:
          vrrp.priority: 100
```

I expect STP bridge priority for vlan blue to be 4096 and for vlan green to be 8192. Instead everything is 4096. What am I doing wrong?
