### DISCUSSION TITLE
Repetitive hosts groups

### DISCUSSION THREAD

**Discussion by jbemmel** [ipspace/netlab#1570] [Features]
I want to use Netlab to generate the full configs for new switches we're deploying. Each switch is mostly fully loaded with hosts; groups of hosts are connected in the same way (to the same vlans, etc.)

I'd like to have an easy way to say: "Connect 10 hosts to ports 1-10 with this port configuration"

One way to implement this:
```
groups:
 _auto_create: True
 hosts:
  members: [h]
  device: linux
  count: 10          <-- *NEW*

links:
- h:
  s1:
   ifindex: 1        <-- gets incremented for each additional host
  vlan.access: X
```

The semantics would be to generate N copies wherever node 'h' is used, replacing it with h1, h2, ... etc.
