### DISCUSSION TITLE
Defining group level VLAN with prefix

### DISCUSSION THREAD

**Discussion by jbemmel** [ipspace/netlab#1608] [Features]
I would like to configure the default VLAN 1 with a different prefix for different groups:
```
groups:
  _auto_create: True
  members: [ r1, r2 ]
  vlans:
    v1:
      id: 1
      prefix: 10.0.0.0/24
```

Unfortunately, this doesn't work: https://github.com/ipspace/netlab/blob/b76b2bd02572f7992a264b8f9f9ceaefc16054b9/netsim/modules/vlan.py#L1274 copies group VLANs into the global topology. The ```prefix``` isn't copied, but it's still not allowed to set a prefix for "global" vlan v1

As a workaround, one can define the VLAN at each node instead - but I'm wondering if it wouldn't be better to change the logic in ```export_group_node_data``` to not create a global vlan if one doesn't exist already
