### DISCUSSION TITLE
Add cost to OSPF area filter ranges

### DISCUSSION THREAD

**Discussion by jbemmel** [ipspace/netlab#2368] [Features]
A small addition to the newly introduced OSPF area parameters plugin:

```
- area: 11
  range:
  - ipv4: 10.17.0.0/16
    cost: 10
```

i.e. in addition to a string (IP prefix), allow a dict that specifies a cost

**Comment by ipspace** [comment]
That could require a change deep in the bowels of type validation code. Right now, the elements of the "range" list are "prefix_str". With this change, the elements would be a wider dictionary, and "prefix_str" would become _alt_type. I don't think the current code can do validation-triggered data transformation on _alt_types.

Anyhow, I will need the same functionality for **bgp.aggregate** list, so that will be fixed (one way or another) in a not-too-distant future.

**Reply by jbemmel** [reply]
Correct, here's what I have for the moment:
```
attributes:
    _range_with_cost:
      ipv4: { type: ipv4, use: prefix }
      ipv6: { type: ipv6, use: prefix }
      cost: { type: int, min_value: 1, max_value: 16777215 }
    global:
      areas:
        type: list
        _subtype:
          area: { type: ipv4, use: id, _required: True }
          kind: { type: str, valid_values: [ regular, stub, nssa ] }
          default:
            cost: int
          inter_area: bool
          filter:
            type: list
            _subtype: prefix_str
          range:
            type: list
            _subtype: { 'type': _range_with_cost, _alt_types: [ prefix_str, dict ] }
```

```dict``` allows the structure, but skips the validation of the exact attributes. We could do it like that until more granular type validation gets implemented
