### DISCUSSION TITLE
eBGP Utils plugin

### DISCUSSION THREAD

**Discussion by ssasso** [ipspace/netlab#281] [Ideas]
I tried to perform some work on a eBGP plugin which I was thinking to call "ebgp_utils".
This plugin should be able to support additional "attributes" for eBGP sessions, like

- AS Override (currently implemented)
- Allow-AS In (currently implemented)
- SOO
- Route Maps / Prefix Lists / Communities
- Password
- ...

Since I was thinking only about eBGP, at least for now, my idea was to add the required attributes under the link->node hierarchy (for the links where the eBGP session will be established):
```
links:
- pe1:
    vrf: blue
    bgp.as_override: true
  edge1:
- pe2:
    vrf: blue
  edge2:
    bgp.allowas_in: 10
```

You can find my initial implementation here: https://github.com/ssasso/netsim-tools/tree/plugin_ebgp_utils/netsim/extra/ebgp_utils

Any comment, idea, suggestion (or insult) is welcome ;)
