### DISCUSSION TITLE
When enabling EVPN L3VNI, L2 VNI info disappears

### DISCUSSION THREAD

**Discussion by ssasso** [ipspace/netlab#344] [General]
When I assign VLANs to a VRF, for using them with Symmetric IRB, I still want to preserve L2 VNI info (RD, RT) for my VLANs (L3 VNI shall not exclude L2 VNI).

With this topology:
```
vrfs:
  tenant:
    evpn.transit_vni: True

vlans:
  red:
    vrf: tenant
  blue:
    vrf: tenant
  green:
    vrf: tenant

nodes:
  h1:
  h2:
  h3:
  h4:
  s1:
    vlans:
      red:
      blue:
      green:
  s2:
    vlans:
      red:
      blue:
      green:

links:
- h1:
  s1:
    vlan.access: red
- h2:
  s2:
    vlan.access: red
- h3:
  s1:
    vlan.access: blue
- h4:
  s2:
    vlan.access: green
- s1:
  s2:
```

The *vlans* structure does not have them anymore:
```
vlans:
  blue:
    bridge_group: 2
    id: 1001
    prefix:
      ipv4: 172.16.1.0/24
    vni: 101001
    vrf: tenant
```

The problem maybe seems to be here:
https://github.com/ipspace/netsim-tools/blob/2b24377717c3233ba830b4d2abebcc46d5e847f5/netsim/modules/evpn.py#L169

When the *vrf* key is present, it is assumed to use vlan_bundle (which may not be supported by all the devices)
