### DISCUSSION TITLE
Uniform format for RD

### DISCUSSION THREAD

**Discussion by ssasso** [ipspace/netlab#351] [General]
Fighting again with Dell's implementations ;)

Right now in *netlab* we are using two different RD encoding, one for VRF and one for L2VNI.
```
vlans:
  blue:
    bridge_group: 2
    evpn:
      evi: 1001
      export:
      - 65000:1001
      import:
      - 65000:1001
      rd: 10.0.0.5:1001
    id: 1001
    prefix:
      ipv4: 172.16.1.0/24
    vni: 101001
    vrf: tenant

vrfs:
  tenant:
    af:
      ipv4: true
    evpn:
      transit_vni: 200000
    export:
    - '65000:1'
    import:
    - '65000:1'
    rd: '65000:1'
    vrfidx: 100
```
Can we uniform this to use Encoding Type 1 everywhere? https://www.rfc-editor.org/rfc/rfc4364#section-4.2

Dell OS10 is expecting this, for L3VNI RD:
```
s1(config-evpn-vrf-tenant)# rd 65000:1
% Error: Illegal parameter.
s1(config-evpn-vrf-tenant)# rd
  A.B.C.D:[1..65535]  4-octet-ipv4addr:2-octet-number
```

The workaround I am using right now is:
```
rd {{ rd_0|ipaddr('address') }}:{{ rd_1 }}
```
