### DISCUSSION TITLE
Routed vlan prefixes

### DISCUSSION THREAD

**Discussion by jbemmel** [ipspace/netlab#436] [General]
https://github.com/ipspace/netlab/blob/c6ef55aa7e946f38591c3ee2f908abe0059cd756/tests/topology/expected/vlan-vrf-lite.yml#L1094

The above prefix associated with the blue vlan confuses me, since:
* https://github.com/ipspace/netlab/blob/dev/tests/topology/expected/vlan-vrf-lite.yml#L373 ```ipv4: 172.16.3.1/24```

For routed vlans, perhaps we should not be allocating a prefix globally?

**Comment by jbemmel** [comment]
A test case for addressing of routed vlans:
```
defaults.device: srlinux
provider: clab

module: [vlan]

addressing:
  lan:
    ipv4: 192.168.0.0/20
    prefix: 24

  p2p:
    ipv4: 172.16.0.0/16
    prefix: 30

  routed-pool-1:
    ipv4: 100.0.0.0/24
    prefix: 31

  routed-pool-2:
    ipv4: 200.0.0.0/24
    prefix: 31

vlans:
  routed-1:
    mode: route
    pool: routed-pool-1 # Default == lan for irb, p2p for routed vlans

  irb-1:
    mode: irb

nodes:
  r1:
  r2:
  r3:
    vlans:
      routed-1:
        pool: routed-pool-2  # Override at node level

links:
- r1: # Currently (dev) taken from p2p pool
  r2:
  vlan.access: routed-1

- r2: # Currently (dev) taken from p2p pool
  r3:
  vlan.access: routed-1 # Outside of trunk, should get overridden by r3.vlans.routed-1.pool

- r1: # Currently (dev) becomes a vlan_member with ip from lan pool
  r3:
  vlan.trunk: [ routed-1 ] # Inside trunk, should get overridden by r3.vlans.routed-1.pool

- r1: # Currently (dev) becomes vlan_members with ips from lan pool ( routed vlan_member + svi for irb )
    vlan.trunk:
      routed-1:
        pool: routed-pool-2  # Override at trunk level
  r2:
  vlan.trunk: [ irb-1, routed-1 ]
```

Currently (dev branch) a routed vlan becomes a p2p link when used as access vlan, but it remains 'lan' when used in a trunk.
None of the pool override cases work as one might expect

* Should we convert routed vlans to link.type = p2p for addressing purposes?
* Should we support node or trunk level override of the 'pool'
