### DISCUSSION TITLE
Auto-generate "<feature>.supported_on"

### DISCUSSION THREAD

**Discussion by ssasso** [ipspace/netlab#689] [Ideas]
Every time we add the support for a "feature" (aka: module) on a platform, it is needed that we edit both the platform and the feature section.

example:
```
vlan:
  supported_on: [ eos, iosv, vyos, dellos10, srlinux, none, routeros, nxos, frr, cumulus, sros, routeros7, vmx, vsrx, none ]

vrsx:
 features:
   vlan:
      model: router
       subif_name: "{ifname}.{vlan.access_id}"

vmx:
 features:
   vlan:
      model: l3-switch
       subif_name: "{ifname}.{vlan.access_id}"

```
IMHO it would be easier if we can auto-generate the "supported_on" based on the platform data itself.
This would also add the "benefit" of avoiding conflicts on the file if multiple people are working to different platforms at the same time.

the "supported_on" attribute can be auto-generated with sth like:
```
for p, pdata in platforms.items():
  if current_mod in pdata.features:
    supported_on.append(p)
```

I can try to work on this after the JunOS stuff I'm working on, if you agree.
