### DISCUSSION TITLE
Proposal to change default loopback and router_id address pools

### DISCUSSION THREAD

**Discussion by ssasso** [ipspace/netlab#824] [Ideas]
Right now, the default addressing for *loopbacks* and *router_id* are:
```
loopback:
  ipv4: 10.0.0.0/24
router_id:
  ipv4: 10.0.0.0/24
  prefix: 32
```

Since it seems that all the *containerlab* containers based on *vrnetlab* (https://containerlab.dev/manual/vrnetlab/) use `10.0.0.0/24` as internal subnet, this will cause some problems to people not reading the "caveats" documentation (i.e., https://netlab.tools/caveats/#juniper-vmx-in-containerlab).
Additionally, having to manually set a new pool every time a new lab config is created is error prone and annoying ;)

For that reason I propose to change the default *loopback*/*router_id* addressing schema to:
```
loopback:
  ipv4: 10.255.0.0/24
router_id:
  ipv4: 10.255.0.0/24
  prefix: 32
vrf_loopback:
  ipv4: 10.255.1.0/24
  prefix: 32
```
(changed also the *vrf_loopback* pool for consistency)
