### DISCUSSION TITLE
Ordering of modules

### DISCUSSION THREAD

**Discussion by jbemmel** [ipspace/netlab#83] [General]
It looks like modules are currently processed in the order declared. For example, from routing sr-mpls-bgp example:
```
nodes:
  e1:
    device: csr
    module: [ sr, isis, bgp ]
    bgp:
      as: 65000
```

'sr' depends on 'isis', but this order of deployment is currently not enforced(?)

Also, there can be a case where 'sr' modifies 'bgp' configuration - there would seem to be a preferred execution order:
1. isis (or ospf)
2. bgp (first ebgp, then ibgp)
3. sr

(in my case I tried to configure a BGP shortcut for SR, which fails because BGP AS is not configured)
