### DISCUSSION TITLE
Put provider specific properties under <provider>.xxx scope

### DISCUSSION THREAD

**Discussion by jbemmel** [ipspace/netlab#96] [Ideas]
For example, on Containerlab we have provider_kind which gets copied to node.kind

Instead, each provider could declare attributes:
```
clab:
 attributes:
  node: [ kind, type ]
 devices: 
  srlinux:
   kind: srl
   type: ixrd2
```

and then those would be copied to node.\<provider\>.xxx:
```
clab:
 kind: srl
 type: ixrd2
```
and referenced in templates as {{ clab.kind }}, etc.
