### ISSUE TITLE
[BUG] Next-hop of Linux static routes is incorrect when the first-hop gateway uses unnumbered IPv4

### ISSUE THREAD

**Issue by ipspace** [ipspace/netlab#1000]
### Describe the bug

Initial configuration on Linux creates static routes pointing to an adjacent network device for all address pool prefixes (so we don't clash with the default route). The static routes contain `False` instead of the next hop when the adjacent interface uses **ipv4: True**

### Expected behavior

The next hop of the static routes should be the IP address of the parent interface of the adjacent device.

### Lab topology

```
nodes:
  r:
    device: eos
  h1:
    device: linux
    provider: clab

links:
- r:
    ipv4: True
  h1:
```

### Version

Most netlab version (`initial/linux.j2` template is ancient)
