### ISSUE TITLE
[BUG] Allow ansible_ and netlab_ parameters in node data

### ISSUE THREAD

**Issue by ipspace** [ipspace/netlab#1009]
### Describe the bug

It's almost impossible to overwrite ansible_ or netlab_ parameter set in device group_vars for individual nodes. We should allow (unchecked) ansible_ and netlab_ parameters in node data and group node data. See #1007 for more details.

### Lab topology

```
provider: clab

nodes:
  h:
    device: linux
    ansible_connection: ssh
```

### Version

All netlab versions
