### ISSUE TITLE
[BUG] - BGP daemon not started in a FRR container

### ISSUE THREAD

**Issue by barajus** [ipspace/netlab#1012]
### Describe the bug

When using the FRR container for bgplabs, the BGP daemon is not started

### To Reproduce

On a fresh install, clone the bgplab repo, then configure the defaults:
```
ubuntu@primary:~$ cat bgplab/defaults.yml

device: frr             # Change to your preferred network device
provider: clab          # Change to virtualbox or libvirt if needed

groups:
  external:
    device: frr                                    # Change to your preferred external router. Needs 1.6.4 to wo

devices.eos.clab.node.env.CLAB_MGMT_VRF: management    # Add management VRF to cEOS. Not needed after 1.6.4

```
then

```
cd bgplab/basic/1-session/
netlab up
[...]

ubuntu@primary:~/bgplab/basic/1-session$ netlab connect rtr
Connecting to container clab-session-rtr, starting bash
Use vtysh to connect to FRR daemon

rtr(bash)#
rtr(bash)#vtysh

Hello, this is FRRouting (version 9.1_git).
Copyright 1996-2005 Kunihiro Ishiguro, et al.

rtr# conf t
rtr(config)# router bgp 666
bgpd is not running
```
However, BGP daemon is up on the other side:

```
ubuntu@primary:~/bgplab/basic/1-session$ netlab connect x1
Connecting to container clab-session-x1, starting bash
Use vtysh to connect to FRR daemon

x1(bash)#vtysh

Hello, this is FRRouting (version 9.1_git).
Copyright 1996-2005 Kunihiro Ishiguro, et al.

x1# show ip bgp
BGP table version is 1, local router ID is 10.0.0.10, vrf id 0
Default local pref 100, local AS 65100
Status codes:  s suppressed, d damped, h history, * valid, > best, = multipath,
               i internal, r RIB-failure, S Stale, R Removed
Nexthop codes: @NNN nexthop's vrf id, < announce-nh-self
Origin codes:  i - IGP, e - EGP, ? - incomplete
RPKI validation codes: V valid, I invalid, N Not found

    Network          Next Hop            Metric LocPrf Weight Path
 *> 10.0.0.10/32     0.0.0.0(x1)              0         32768 i

Displayed  1 routes and 1 total paths
```

### Expected behavior

I would expect `bgpd=yes` in `/etc/frr/daemons` by default.
Apologies if I didn't RTFM correctly :) thanks

### Version

netlab version 1.7.1
