### ISSUE TITLE
[BUG] netlab initial -o crashes when used on topologies with daemons

### ISSUE THREAD

**Issue by ipspace** [ipspace/netlab#1019]
### Describe the bug

netlab initial (create-config.ansible) tries to find module-specific template that might not be present in case of daemons. 

### Lab topology

```
module: [ bgp ]
provider: clab

nodes:
  rs:
    device: bird
    bgp.as: 65000
  sw:
    device: eos
    bgp.as: 65100

links: [ rs-sw ]
```
