### ISSUE TITLE
[BUG] netlab initial -o should create daemon config files

### ISSUE THREAD

**Issue by ipspace** [ipspace/netlab#1020]
### Describe the bug

`netlab initial -o` should create daemon configuration files according to `daemon_config` device settings in the `config` directory.

### Lab topology

```
provider: clab
module: [ bgp ]

nodes:
  rs:
    device: bird
    bgp.as: 65000
  sw:
    device: eos
    bgp.as: 65100

links: [ rs-sw ]
```
