### ISSUE TITLE
[BUG] (maybe bug?) trying to parse templates for modules not in use

### ISSUE THREAD

**Issue by ssasso** [ipspace/netlab#1042]
I am struggling my head around this, and cannot understand if it's my fault or not.

I have two host groups, spine and leaf.

on spine I defined:
```
module: [ ospf, bgp, evpn ]
```
and on leaf:
```
module: [ vlan, vrf, vxlan, ospf, bgp, evpn, gateway ]
```

BUT, when running `netlab up`, it seems netlab is trying to configure, i.e., VRF on a spine. (note: vrf is only an example, it happens also for other modules)

```
TASK [Deploy vrf configuration] **********************************************************************************************************************************
included: /root/GIT_H/netlab-clone/netlab/netsim/ansible/tasks/deploy-config/arubacx.yml for spine, sw1, sw2, sw3, sw4

TASK [tempfile] **************************************************************************************************************************************************
changed: [spine -> localhost]
changed: [sw1 -> localhost]
changed: [sw2 -> localhost]
changed: [sw3 -> localhost]
changed: [sw4 -> localhost]

TASK [template] **************************************************************************************************************************************************
An exception occurred during task execution. To see the full traceback, use -vvv. The error was: ansible.errors.AnsibleUndefinedVariable: 'vrfs' is undefined
fatal: [spine -> localhost]: FAILED! => changed=false
  msg: 'AnsibleUndefinedVariable: ''vrfs'' is undefined'
changed: [sw1 -> localhost]
changed: [sw2 -> localhost]
changed: [sw3 -> localhost]
changed: [sw4 -> localhost]
```

**Comment by ipspace** [comment]
This definitely looks like a bug and might have been caused by my recent rearrangement of the configuration deployment playbook. Please post full lab topology so I can do some tests.

Thank you!

**Comment by ipspace** [comment]
I used the following topology with the **dev** branch and it works as expected:

```
provider: clab
defaults.device: eos

bgp.as: 65000

groups:
  _auto_create: True
  spine:
    members: [ s1 ]
    module: [ ospf, bgp, evpn ]
  leaf:
    members: [ l1, l2 ]
    module: [ vlan, vrf, vxlan, ospf, bgp, evpn, gateway ]

vlans:
  red:
    vrf: red
    links: [ l1, l2 ]

vrfs:
  red:

links: [ l1-s1, l2-s1 ]
```

Can you try it with Aruba so we can see whether it's something in the Aruba-specific task list that triggers the unwanted "template" call?

Otherwise, do **netlab inspect --node X module** to see what modules netlab thinks should be active on a node. If that turns out to be weird we have another gremlin to chase.

**Comment by ssasso** [comment]
This is the topology:
```

provider: clab

addressing:
  loopback:
    ipv4: 10.100.0.0/24
    prefix: 32
  router_id:
    ipv4: 10.100.0.0/24
    prefix: 32

vrfs:
  tenant:
    ospf: false

vlans:
  red:
    vrf: tenant

groups:
  leaf:
    device: arubacx
    members: [ sw1, sw2, sw3, sw4 ]
    module: [ vlan, vrf, vxlan, ospf, bgp, evpn, gateway ]
    node_data:
      bgp:
        as: 65000
        advertise_loopback: false
        activate:
          ipv4: [ ebgp ]

nodes:
  spine:
    device: arubacx
    id: 1
    module: [ ospf, bgp, evpn ]
    bgp:
      rr: True
      as: 65000
      advertise_loopback: false
      activate:
        ipv4: []
  sw1:
    id: 11
  sw2:
    id: 12
  sw3:
    id: 21
  sw4:
    id: 22
  cl1:
    device: arubacx
    id: 31
    module: [vlan]
  cl2:
    device: arubacx
    id: 32
    module: [vlan]

links:
- spine:
  sw1:
  ospf.cost: 10
- spine:
  sw2:
  ospf.cost: 10
- spine:
  sw3:
  ospf.cost: 10
- spine:
  sw4:
  ospf.cost: 10

# Links to Client Switches
# SW1 to CL1
- sw1:
  cl1:
  vlan.access: red
  gateway: true

# SW3 to CL2
- sw3:
  cl2:
  gateway: true
  vlan.access: red
```

**netlab inspect**, i.e. for spine, reports the correct/expected result:
```
# netlab inspect --node spine module
- ospf
- bgp
- evpn
```


Will try your topology now.
