### ISSUE TITLE
[BUG] (probably?) Issue with custom config templates

### ISSUE THREAD

**Issue by ssasso** [ipspace/netlab#1045]
Custom config template is correctly read, rendered, but then it's not applied.

Seems like the task *Find custom configuration deployment script* is not reporting the deploy task:

```
TASK [Find configuration template] *******************************************************************************************************************************
task path: /root/GIT_H/netlab-clone/netlab/netsim/ansible/tasks/deploy-custom-config.yml:10
redirecting (type: connection) ansible.builtin.network_cli to ansible.netcommon.network_cli
redirecting (type: connection) ansible.builtin.network_cli to ansible.netcommon.network_cli
ok: [sw3] => changed=false
  ansible_facts:
    config_module: extra-config-lag
    config_template: /root/GIT_H/netsim-topologies/multivendor-evpn/vsx_evpn/extra-config-lag/arubacx.j2
ok: [sw4] => changed=false
  ansible_facts:
    config_module: extra-config-lag
    config_template: /root/GIT_H/netsim-topologies/multivendor-evpn/vsx_evpn/extra-config-lag/arubacx.j2

TASK [fail] ******************************************************************************************************************************************************
task path: /root/GIT_H/netlab-clone/netlab/netsim/ansible/tasks/deploy-custom-config.yml:21
skipping: [sw3] => changed=false
  skip_reason: Conditional result was False
skipping: [sw4] => changed=false
  skip_reason: Conditional result was False

TASK [Process template /root/GIT_H/netsim-topologies/multivendor-evpn/vsx_evpn/extra-config-lag/arubacx.j2 for sw3] **********************************************
task path: /root/GIT_H/netlab-clone/netlab/netsim/ansible/tasks/deploy-custom-config.yml:25
redirecting (type: connection) ansible.builtin.network_cli to ansible.netcommon.network_cli
redirecting (type: connection) ansible.builtin.network_cli to ansible.netcommon.network_cli
ok: [sw3] =>
  msg: |-
    /root/GIT_H/netsim-topologies/multivendor-evpn/vsx_evpn/extra-config-lag/arubacx.j2 configuration for sw3
    =========================================

    interface lag 1 multi-chassis
      shutdown
      lacp mode active

    interface 1/1/3
      description LAG_1
      lag 1

    interface lag 1
      no routing

      vlan access 1000

    interface lag 1
      no shutdown
ok: [sw4] =>
  msg: |-
    /root/GIT_H/netsim-topologies/multivendor-evpn/vsx_evpn/extra-config-lag/arubacx.j2 configuration for sw4
    =========================================

    interface lag 1 multi-chassis
      shutdown
      lacp mode active

    interface 1/1/3
      description LAG_1
      lag 1

    interface lag 1
      no routing

      vlan access 1000

    interface lag 1
      no shutdown

TASK [Find custom configuration deployment script] ***************************************************************************************************************
task path: /root/GIT_H/netlab-clone/netlab/netsim/ansible/tasks/deploy-custom-config.yml:39
redirecting (type: connection) ansible.builtin.network_cli to ansible.netcommon.network_cli
redirecting (type: connection) ansible.builtin.network_cli to ansible.netcommon.network_cli
ok: [sw4] => changed=false
  ansible_facts:
    deploy_task: ''
ok: [sw3] => changed=false
  ansible_facts:
    deploy_task: ''

TASK [Run the configuration deployment script] *******************************************************************************************************************
task path: /root/GIT_H/netlab-clone/netlab/netsim/ansible/tasks/deploy-custom-config.yml:55
skipping: [sw3] => changed=false
  skip_reason: Conditional result was False
skipping: [sw4] => changed=false
  skip_reason: Conditional result was False
META: ran handlers
META: ran handlers
```

config is defined as follows:
```
  mclag2:
    members: [ sw3, sw4 ]
    device: arubacx
    config: [ extra-config-mclagcluster, extra-config-lag ]
```

**Comment by ssasso** [comment]
(note: this kind of topology was working one month ago, so looks like a regression)

**Comment by ipspace** [comment]
Definitely a bug introduced during the recent restructuring of the Ansible playbooks. Glad you caught it before I pushed out 1.8 ;)

**Comment by ipspace** [comment]
OK, that close was premature (GitHub does not understand "probably fixes" ;), but I'm suspecting the root cause is Aruba CX implementation uses **netlab_device_type** to find deployment scripts, which is perfectly OK, but I did not test the refactored playbooks on any other similar device.

**Comment by ssasso** [comment]
Nope, nothing changed :( 

seems the offending part is this:
```
TASK [Find custom configuration deployment script] ***************************************************************************************************************
task path: /root/GIT_H/netlab-clone/netlab/netsim/ansible/tasks/deploy-custom-config.yml:39
redirecting (type: connection) ansible.builtin.network_cli to ansible.netcommon.network_cli
redirecting (type: connection) ansible.builtin.network_cli to ansible.netcommon.network_cli
ok: [sw3] => changed=false
  ansible_facts:
    deploy_task: ''
ok: [sw4] => changed=false
  ansible_facts:
    deploy_task: ''
```
where *deploy_task* is not set?
