### ISSUE TITLE
[BUG] netlab status -i X - unknown lab instance

### ISSUE THREAD

**Issue by sdargoeuves** [ipspace/netlab#1058]
### Describe the bug

When performing the command `netlab status -i 2` I have the following errors:

```
~/c/n/labs/arista-test ❯ /home/seb/code/netlab/netlab/netlab status -i 3    seb@linux-lab 17:26:53
[FATAL]   Unknown lab instance 3.
[HINT]    Use 'netlab status --all' to display the list of lab instances
~/c/n/labs/arista-test ❯ /home/seb/code/netlab/netlab/netlab status -i 2    seb@linux-lab 17:27:03
[FATAL]   Unknown lab instance 2.
[HINT]    Use 'netlab status --all' to display the list of lab instances
~/c/n/labs/arista-test ❯ /home/seb/code/netlab/netlab/netlab status --all   seb@linux-lab 17:27:07
Active lab instance(s)

┏━━━━┳━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━┳━━━━━━━━━━━┓
┃ id ┃ directory                              ┃ status  ┃ providers ┃
┡━━━━╇━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━╇━━━━━━━━━━━┩
│ 2  │ /home/seb/code/netlab/labs/arista-ospf │ started │ libvirt   │
├────┼────────────────────────────────────────┼─────────┼───────────┤
│ 3  │ /home/seb/code/netlab/labs/arista-test │ started │ libvirt   │
└────┴────────────────────────────────────────┴─────────┴───────────┘
~/c/n/labs/arista-test ❯
```

Do I understand correctly the notion of lab instance, is it indeed the lab id?

### To Reproduce

Have multiple labs active, perform the `netlab status -i X`

### Expected behavior

Display a list of the active devices for this lab.

### Lab topology

```
##Lab3
---
plugin: [ multilab ]
defaults:
  multilab.id: 3
  device: eos
  links.stub_loopback: false
....removed the rest of the config.....

##Lab2
---
plugin: [ multilab ]
defaults:
    multilab.id: 2
    device: eos
    links.stub_loopback: false
....removed the rest of the config.....
```

### Version

* netlab version (as displayed by `netlab version`)
```
~/c/n/labs/arista-test ❯ /home/seb/code/netlab/netlab/netlab version        seb@linux-lab 17:31:36
netlab version 1.8.0-post2
```
but this is using the latest dev branch
