### ISSUE TITLE
[BUG] SR Linux: BGP-in-VRF test scenarios fail

### ISSUE THREAD

**Issue by ipspace** [ipspace/netlab#1074]
Based on https://netlab-cicd.pages.dev/_html/srlinux-clab-vrf it looks like every test scenario that uses BGP in a VRF fails.

According to one validation log (https://netlab-cicd.pages.dev/srlinux/clab/vrf/12-multi-vrf-bgp.yml-validate.log) the BGP sessions are established, but the IPv4 routes are never propagated between the CE-routers

Lab topology @ https://github.com/ipspace/netlab/blob/dev/tests/integration/vrf/12-multi-vrf-bgp.yml

**Comment by jbemmel** [comment]
```
vrfs:
  blue:
    af:
      ipv4: true
    bgp:
      neighbors:
      - as: 65103
        ifindex: 3
        ipv4: 10.1.0.10
        name: r3
        type: ebgp
      - as: 65104
        ifindex: 4
        ipv4: 10.1.0.14
        name: r4
        type: ebgp
    export:
    - '65000:2'
    id: 2
    import:
    - '65000:2'
    rd: '65000:2'
    vrfidx: 101
```

Based on the topology file, the BGP policies are importing routes with community 65000:2.
The FRR instances are not sending any communities, so no routes are imported
