### ISSUE TITLE
[DOC] VRFs without links have to be listed in node vrfs dictionary

### ISSUE THREAD

**Issue by ipspace** [ipspace/netlab#1092]
### Describe the bug

A topology that has no VRF links but uses VRF loopbacks should get VRFs on all devices with VRF loopbacks. At the moment, netlab does not create VRFs and removes the VRF module from devices that have no VRF links.

### Lab topology

```
defaults:
  device: frr
  provider: clab

vrf.loopback: True

vrfs:
  red:

bgp.as: 65001
mpls.ldp: True
mpls.vpn: True
module: [ isis, bgp, mpls, vrf]

nodes:
  r1:
  r2:

links: [r1-r2]
```
