### ISSUE TITLE
[BUG] Generate a warning when a device using VRF module has no active VRFs

### ISSUE THREAD

**Issue by ipspace** [ipspace/netlab#1093]
### Describe the bug

_netlab_ removes the VRF module from devices that have no active VRFs, resulting in somewhat unexpected behavior. Generate a warning when that happens.

### Lab topology

```
defaults:
  device: sros
  provider: clab

vrf.loopback: True

vrfs:
  red:

bgp.as: 65001
mpls.ldp: True
mpls.vpn: True
module: [isis,bgp,mpls,vrf]

nodes:
  r1:
  r2:

links: [r1-r2]
```
