### ISSUE TITLE
[BUG] Generate a warning when a routing protocol is not used on a device

### ISSUE THREAD

**Issue by ipspace** [ipspace/netlab#1094]
### Describe the bug

A routing protocol configuration module is removed from a network device when it's not used on any link. Generate a warning when that happens.

### Lab topology

```
defaults:
  device: frr
  provider: clab

bgp.as: 65001
module: [ ospf, bgp ]

nodes:
  r1:
  r2:
  r3:
    bgp.as: 65002

links: [r1-r2,r2-r3]
```
