### ISSUE TITLE
[BUG] vpnv4 or vpnv6 address family is not activated

### ISSUE THREAD

**Issue by ipspace** [ipspace/netlab#1096]
### Describe the bug

MPLS/VPN address family is never activated on IBGP sessions, even if the devices have perfectly legal VRFs

### Root cause

MPLS/VPN code uses VRF **af** parameter to figure out whether the vpnv4 or vpnv6 AF should be activated. As the MPLS/VPN **node_post_transform** function is called before the VRF one, the **af** parameter is not set.

### To Fix

Do MPLS/VPN transformations after VRF transformations

### Lab topology

```
defaults:
  device: frr
  provider: clab

vrfs:
  red:
    links: [r1,r2]

bgp.as: 65001
mpls.ldp: True
mpls.vpn: True
module: [isis,bgp,mpls,vrf]

nodes:
  r1:
  r2:

links: [r1-r2]
```
