### ISSUE TITLE
[BUG] VRFs should not be removed from node with VRF loopbacks but no links

### ISSUE THREAD

**Issue by ipspace** [ipspace/netlab#1108]
### Describe the bug

If a node has VRFs specified in the **vrfs** dictionary but does not have any VRF links, the **vrfs** dictionary is removed even when the device uses VRF loopbacks.

Note: this is an interesting spinoff from the investigation of #1092

### Expected behavior

VRFs with loopbacks should not be removed

### Lab topology

```
defaults:
  device: eos

module: [ vrf ]

vrfs:
  red:
  blue:

vrf.loopback: True

nodes:
  r1:
    vrfs:
      red:
      blue:
```
