### ISSUE TITLE
[BUG] Cannot create a topology without global VRFs

### ISSUE THREAD

**Issue by ipspace** [ipspace/netlab#1110]
### Describe the bug

A topology with VRFs defined on nodes but no global VRF fails because the initial VRF ID is not initialized.

### Expected behavior

Having node-only VRFs is a perfectly valid topology and has to work (see #1091 for details)

### Lab topology

```
defaults:
  device: eos
  provider: libvirt

vrf.loopback: True

module: [ vrf ]

nodes:
  r1:
    vrfs:
      red:
  r2:
    vrfs:
      red:

links: [r1-r2]
```
