### ISSUE TITLE
[BUG] Removing vlan.native attribute removes trunk from topology

### ISSUE THREAD

**Issue by jbemmel** [ipspace/netlab#1113]
### Describe the bug

e.g. in https://github.com/ipspace/netlab/blob/dev/tests/integration/vlan/41-vlan-bridge-native.yml#L40 if I comment out the
```
vlan.native: red
```
line there is no more 'trunk' attribute generated in the topology

### To Reproduce

Comment out that line, then 'netlab create -d frr'

### Expected behavior

In host_vars/s1/topology.yml I'd expect to see
```
vlan:
    access_id: 1000
    trunk:
      blue: {}
      red: {}
    trunk_id:
    - 1000
```

### Output

Missing 'trunk' dict

### Version

Latest HEAD under dev tree
