### ISSUE TITLE
[BUG] netlab initial crashes if an FRR node does not have a management VRF nor any modules

### ISSUE THREAD

**Issue by ipspace** [ipspace/netlab#1220]
### Describe the bug

When an FRR node does not use a management VRF and does not have any configuration modules, **netlab initial** crashes like in #1219 (but with a different error).

<img width="1064" alt="image" src="https://github.com/ipspace/netlab/assets/16917911/b69c0b9c-88cb-4fc9-9fed-23c199a4e971">

### Lab topology

```
provider: clab
nodes:
  rtr:
    device: frr
    netlab_mgmt_vrf: False
```
