### ISSUE TITLE
bgp.policy: allow to create an empty policy

### ISSUE THREAD

**Issue by ssasso** [ipspace/netlab#1229]
It would be great if the `bgp.policy` plugin will allow to create/append an empty policy to a neighbor. Allowing to define also the policy name would be a nice bonus.

**In this way we can "attach" a route-map to a neighbor, which can easily be used (populated) by external/custom configuration scripts without the need to worry about the neighbor IP address (and eventually the policy name).**

Example:

```
links:
- r1:
    bgp.create_empty_policy: true ### could be true/false or 'in' / 'out'
    bgp.policy_name_prefix: r1-to-r2-policy
  r2:
```

`bgp.create_empty_policy` will be considered only if no other attribute is present (as a sort of fallback), 

https://github.com/ipspace/netlab/blob/63c3bc7427cacdce3a055d344ac1b892c1803336/netsim/extra/bgp.policy/plugin.py#L204

and could create a route map with `permit 99` or sth similar, with no match/set clauses.

Then the route map needs to be linked to a neighbor (but the plugin is already capable of that).

`policy_name_prefix` could be used to create the two policy names, `<prefix>-in` and `<prefix>-out`.
