### ISSUE TITLE
Proposal for links as dict (still allowing list)

### ISSUE THREAD

**Issue by ssasso** [ipspace/netlab#1250]
If I am not wrong, currently the top-level-attribute `links` is (the only one?) defined as a _list_.

That means it is not possible to use the construct `_include` in it, thus not allowing _code reuse_.

My proposal is to accept as `links` value both *dict* and *list*.

- In case of *list*, no change in the actual behavior.
- In case of *dict*, they dict key is ignored, the dict values must be lists, and they are merged to create an unique list (and back to point (1))

This will allow to have sth like:

```
links:
  _include:
    - include/links_part_1.yaml
    - include/links_part_2.yaml
```

which is converted into sth like:

```
links:
  links_part_1:
  - node1:
    node2:
  links_part_2:
  - node2:
    node3:
```

which, at the end, behaves like:

```
links:
  - node1:
    node2:
  - node2:
    node3:
```

If we do not want to modify the "core code", I guess this can be performed as pre-transformation step in a dedicated plugin?
