### ISSUE TITLE
[BUG] BGP stub subnet not advertised in multi-provider environment

### ISSUE THREAD

**Issue by ipspace** [ipspace/netlab#1277]
When running a libvirt lab with one link being attached only to a container the link type is (probably) different than if we were running clab lab (and the subnet does not get advertised in BGP).

Sample topology:

```
module: [ bgp ]
defaults.device: frr

nodes:
  dut:
    bgp.as: 65000
  x1:
    bgp.as: 65100

links:
- dut-x1
- x1:
```

The stub network is not advertised by X1, we have to set bgp.advertise flag on it.
