### ISSUE TITLE
[BUG] Node VLAN definition should accept interface attributes

### ISSUE THREAD

**Issue by ipspace** [ipspace/netlab#1347]
### Describe the bug

Node VLAN definition results in an SVI interface. It should thus accept interface (not just link) attributes.

### Lab topology

```
module: [ vlan,dhcp ]

vlans:
  red:
    links: [ r1 ]

provider: clab

nodes:
  dhs:
    device: dnsmasq
  r1:
    device: eos
    vlans:
      red:
        dhcp.server: dhs

links: [ r1-dhs ]
```
