### ISSUE TITLE
[BUG] vrrp.priority defined on node VLAN not taken into account

### ISSUE THREAD

**Issue by jbemmel** [ipspace/netlab#1349]
### Describe the bug

In a topology that has a gateway on a VLAN using vrrp, the vrrp.priority configured on each node is not copied to the interface.
Consequently, all nodes get the default priority

### To Reproduce
```netlab create bug-topo```

### Expected behavior

Expected to see the configured vrrp.priority values on the VLAN interfaces for each node

### Lab topology
```
module: [ vlan, gateway ]

vlans:
 v1:
  gateway:
   protocol: vrrp

nodes:
 r1:
  vlans:
   v1:
    gateway.vrrp.priority: 100
 r2:
  vlans:
   v1:
    gateway.vrrp.priority: 200

links:
- r1:
  r2:
  vlan.trunk: [ v1 ]

```
### Output
```
In host_vars/r1/topology.yml
...
- bridge_group: 1
  gateway:
    id: -2
    ipv4: 172.16.0.254/24
    protocol: vrrp
    vrrp:
      group: 1
- ...
```

### Version

netlab version 1.9.1
