### ISSUE TITLE
[BUG] VLAN DHCP pools are incorrect

### ISSUE THREAD

**Issue by ipspace** [ipspace/netlab#1358]
### Describe the bug

The DHCP pools built for a DHCP-on-VLAN topology contain duplicate subnets and do not have excluded IP addresses

### Expected behavior

The IP subnets in the **dhcp.pools** list should be unique. Each entry should have the **excluded** IP addresses (at the very minimum, the DHCP relays). However, this is what the following topology generates:

```
pools:
- clean_name: vlans_red_links_1_
  ipv4: 172.16.0.0/24
  name: vlans.red.links[1]
- clean_name: vlans_red_links_2_
  ipv4: 172.16.0.0/24
  name: vlans.red.links[2]
```

### Lab topology

```
provider: libvirt

vlans:
  red:
    dhcp.client.ipv4: True
    links: [ s1-h1, s1-h2 ]

nodes:
  s1:
    module: [ dhcp, vlan ]
    device: eos
    vlans:
      red:
        dhcp.server: dhs
  h1:
    device: linux
  h2:
    device: linux
  dhs:
    device: dnsmasq
    provider: clab

links:
- s1-dhs
```

### Proposed solution

* Build excluded IP lists for all VLANs (iterate over SVI/subinterfaces or use the VLAN neighbors list)
* Iterate over all links, add link data if the link is not a VLAN link, or adjust the VLAN data if the link is a VLAN access link
* Use the combined data structure to generate the DHCP pools
