### ISSUE TITLE
[BUG] DHCP 'default router' option is missing for VLAN DHCP pools

### ISSUE THREAD

**Issue by ipspace** [ipspace/netlab#1359]
The default gateway used by hosts attached to a VLAN is not saved anywhere and thus not accessible to the DHCP module building DHCP pools. The DHCP pools for the VLAN prefixes thus lack the correct 'default router' option.

A workaround is to use the **gateway** module.

### Lab topology

```
provider: libvirt

vlans:
  red:
    dhcp.client.ipv4: True
    links: [ s1-h1, s1-h2 ]

nodes:
  s1:
    module: [ dhcp, vlan ]
    device: eos
    vlans:
      red:
        dhcp.server: dhs
  h1:
    device: linux
  h2:
    device: linux
  dhs:
    device: dnsmasq
    provider: clab

links:
- s1-dhs
```

### Current behavior

The `vlan_red` DHCP pool does not have a default gateway:

```
$ netlab inspect dhcp
pools:
- clean_name: vlan_red
  excluded:
    ipv4:
    - 172.16.0.1
  ipv4: 172.16.0.0/24
  name: vlan_red
```
