### ISSUE TITLE
[BUG] DHCP module gets confused when we want to have IPv4 and IPv6 client

### ISSUE THREAD

**Issue by ipspace** [ipspace/netlab#1365]
### Describe the bug

If we set **ipv4** and **ipv6** interface address to **dhcp**, the **ipv6** address is not changed.

### Lab topology

Based on the dhcp-vlan.yml transformation test, this is the snippet that triggers the bug:

```
links:
- s1-dhs
- s1:
    dhcp.server: dhs
  h3:
    ipv4: dhcp
    ipv6: dhcp
  vlan.access: blue
  gateway.id: 1
  gateway.protocol: anycast
```
