### ISSUE TITLE
[BUG] DHCP server is by definition not a DHCP client

### ISSUE THREAD

**Issue by ipspace** [ipspace/netlab#1366]
### Describe the bug

The interface.dhcp.client flag should be removed from nodes with dhcp.server set to True

### Lab topology

```
vlans:
  test:
    dhcp.client.ipv4: True
    links: [ s1-h1,s1-dhs ]

nodes:
  s1:
    vlans:
      test:
        dhcp.client.ipv4: False
    module: [ vlan,dhcp ]
    device: eos
  h1:
    device: linux
  dhs:
    device: dnsmasq
    provider: clab
```
