### ISSUE TITLE
[BUG] The 'dhcp.client' flag on link interfaces is not reliable

### ISSUE THREAD

**Issue by ipspace** [ipspace/netlab#1367]
### Describe the bug

When building the DHCP pool excluded IP list, we're checking the link interfaces. Those do not reflect the true status of the 'dhcp.client' flag for DHCP relays or servers attached to a non-VLAN segment or to a VLAN access link. The 'dhcp.client' flag is cleared only in the node interface data, not in the link interface data

Please note this bug happens only when setting **dhcp.client.ipv4** (or **ipv6**) to True on a link. Traditional way of enabling a DHCP client (**ipv4: dhcp** on an interface) is not affected.

### Lab topology

```
module: [ dhcp ]

nodes:
  h1:
    device: linux
  dhs:
    device: dnsmasq
    provider: clab

links:
- h1:
  dhs:
  dhcp.client.ipv4: True
```
