### ISSUE TITLE
[BUG] Node level VRRP gateway priority not propagated to interfaces

### ISSUE THREAD

**Issue by jbemmel** [ipspace/netlab#1370]
### Describe the bug

In the sample topology provided the ```gateway.vrrp.priority``` value configured at the node level is not propagated to the interfaces

### To Reproduce
```netlab create test.yml```

### Expected behavior

Correct VRRP priority value applied to interfaces

### Lab topology

```
module: [gateway,vlan]

vlans:
 v1:
  gateway.protocol: vrrp

nodes:
 r1:
 r2:
  gateway.vrrp.priority: 220

links:
- r1:
  r2:
  vlan.trunk: [v1]
```

### Output
In host_vars/r2/topology.yml
```
gateway:
  vrrp:
    group: 1
    priority: 220
...
- bridge_group: 1
  gateway:
    id: -2
    ipv4: 172.16.0.254/24
    protocol: vrrp
    vrrp:
      group: 1   <--- 'priority' not included here, device templates don't pick it up
  ifindex: 3
  ifname: vlan1000
  ipv4: 172.16.0.2/24
  name: VLAN v1 (1000) -> [r1]
  neighbors:
  - ifname: vlan1000
    ipv4: 172.16.0.1/24
    node: r1
  type: svi
  virtual_interface: true
  vlan:
    mode: irb
```

### Version

netlab version 1.9.1
