### ISSUE TITLE
[BUG] Cumulus fails to select between multiple links using STP

### ISSUE THREAD

**Issue by jbemmel** [ipspace/netlab#1401]
The topology at [tests/integration/stp/03-vlan-multi-link.yml ](https://github.com/ipspace/netlab/blob/9b4f9539123a05043f6fea82167977abbbf54177/tests/integration/stp/03-vlan-multi-link.yml) consists of a simple dual-switch topology with a redundant link in between them:

```
groups:
  _auto_create: True
  hosts:
    members: [ h1, h2 ]
    device: linux
    provider: clab
  switches:
    members: [ s1, s2 ]
    module: [ vlan ]

vlans:
  red:
    mode: bridge
    links: [ s1-h1, s2-h2, s1-s2, s1-s2 ]
```

With Cumulus, everything works when there is 1 s1-s2 link, but add a second one and STP fails to enable any ports.

Note that the above does not create a trunk, but even with a trunk (and native vlan) the scenario fails
