### ISSUE TITLE
[BUG] dev branch now allows ipv4 on vlan but doesn't resolve relative IPs

### ISSUE THREAD

**Issue by jbemmel** [ipspace/netlab#1417]
### Describe the bug

My intent is to pick a specific IP on a vlan trunk. Current Netlab release does not allow the ```ipv4``` attribute on a VLAN, the dev branch does but it doesn't handle it properly

### To Reproduce

```netlab create testtopo.yml```

### Expected behavior

Either "invalid attribute 'ipv4' on vlan" or (preferred) IP 10.0.0.10/24 assigned to n1 on VLAN v1

### Lab topology
```
---
#
# Pick a specific IP for a node on a VLAN trunk
#
module: [ vlan ]

vlans:
 v1:
  prefix: 10.0.0.0/24

nodes:
 n1:
  vlans:
   v1:
    ipv4: 10 # Pick IP 10.0.0.10, applies to all trunks
 n2:
 n3:
 
links:
- n1:
  n2:
  vlan.trunk: [v1]
- n1:
  n3:
  vlan.trunk: [v1]

```

### Output
```
...
- bridge_group: 1
  ifindex: 5
  ifname: vlan1000
  ipv4: 10                                                 <-- issue here
  name: VLAN v1 (1000) -> [n2,n3]
  neighbors:
  - ifname: vlan1000
    ipv4: 10.0.0.2/24
    node: n2
  - ifname: vlan1000
    ipv4: 10.0.0.3/24
    node: n3
  type: svi
  virtual_interface: true
  vlan:
    mode: irb
    name: v1
...
```

### Version
dev branch
