### ISSUE TITLE
[BUG] VRRP on cEOS - no preempt needs to be explicit

### ISSUE THREAD

**Issue by sdargoeuves** [ipspace/netlab#1418]
### Describe the bug

Despite setting the `vrrp.preempt` to false on cEOS, I can see on the `show vrrp` output that Preemption is enabled.

### To Reproduce

topology:

```yaml
vlans:
  vl_blue:
    id: 3032
    prefix: 172.16.32.0/24
    ospf.passive: true
    gateway:
      protocol: vrrp
      vrrp.preempt: false
  vl_red:
    id: 3033
    prefix: 172.16.33.0/24
    ospf.passive: true
    gateway:
      protocol: vrrp
      vrrp.preempt: false
```

Output:

```bash
Connecting to clab-ml_2-gw1 using SSH port 22, executing show vrrp
Vlan3032 - Group 1
  VRF is default
  VRRP Version 3
  State is Master
  Last state transition was 00:01:37 ago
  Virtual IPv4 address is 172.16.32.254
  Virtual MAC address is 0000.5e00.0101
  Mac Address Advertisement interval is 30s
  VRRP Advertisement interval is 1s
  Preemption is enabled
  Preemption delay is 0s
  Preemption reload delay is 0s
  Priority is 120
  Master Router is 172.16.32.1 (local), priority is 120
  Master Advertisement interval is 1s
  Skew time is 0.530s
  Master Down interval is 3.530s

Vlan3033 - Group 1
  VRF is default
  VRRP Version 3
  State is Backup
  Last state transition was 00:01:40 ago
  Virtual IPv4 address is 172.16.33.254
  Virtual MAC address is 0000.5e00.0101
  Mac Address Advertisement interval is 30s
  VRRP Advertisement interval is 1s
  Preemption is enabled
  Preemption delay is 0s
  Preemption reload delay is 0s
  Priority is 100
  Master Router is 172.16.33.2, priority is 120
  Master Advertisement interval is 1s
  Skew time is 0.600s
  Master Down interval is 3.600s
```

### Expected behavior

I would expect to see ` Preemption is disabled` in the output

### Lab topology

```yaml
---
plugin: [ multilab ]
defaults.multilab.id: 2
defaults.addressing.mgmt.start: 10
provider: clab

defaults.devices.eos.clab.image: "ceos:4.32.2F.1"

groups:
  vl_gws:
    device: eos
    module: [vlan, gateway, ospf]
    members: [ gw1, gw2 ]

vlans:
  vl_blue:
    id: 3032
    prefix: 172.16.32.0/24
    ospf.passive: true
    gateway:
      protocol: vrrp
      vrrp.preempt: false
  vl_red:
    id: 3033
    prefix: 172.16.33.0/24
    ospf.passive: true
    gateway:
      protocol: vrrp
      vrrp.preempt: false

nodes:
  gw1:
    vlans:
      vl_blue:
        gateway.vrrp.priority: 120
      vl_red:
        gateway.vrrp.priority: 100
  gw2:
    vlans:
      vl_blue:
        gateway.vrrp.priority: 100
      vl_red:
        gateway.vrrp.priority: 120

links:
  - gw1:
    gw2:
    vlan.trunk: [ vl_blue, vl_red ]
```

### Output

```
Connecting to clab-ml_2-gw1 using SSH port 22, executing show vrrp
Vlan3032 - Group 1
  VRF is default
  VRRP Version 3
  State is Master
  Last state transition was 00:00:42 ago
  Virtual IPv4 address is 172.16.32.254
  Virtual MAC address is 0000.5e00.0101
  Mac Address Advertisement interval is 30s
  VRRP Advertisement interval is 1s
  Preemption is enabled
  Preemption delay is 0s
  Preemption reload delay is 0s
  Priority is 120
  Master Router is 172.16.32.1 (local), priority is 120
  Master Advertisement interval is 1s
  Skew time is 0.530s
  Master Down interval is 3.530s

Vlan3033 - Group 1
  VRF is default
  VRRP Version 3
  State is Backup
  Last state transition was 00:00:42 ago
  Virtual IPv4 address is 172.16.33.254
  Virtual MAC address is 0000.5e00.0101
  Mac Address Advertisement interval is 30s
  VRRP Advertisement interval is 1s
  Preemption is enabled
  Preemption delay is 0s
  Preemption reload delay is 0s
  Priority is 100
  Master Router is 172.16.33.2, priority is 120
  Master Advertisement interval is 1s
  Skew time is 0.600s
  Master Down interval is 3.600s
```

### Version

Running on `dev`

### Additional context

I will send an MR with (what I think should be) the fix.

While testing I thought I saw another issue with either ArubaCX or another vendor, I'll perform more tests on this.
