### ISSUE TITLE
[BUG] Links with a default gateway should not get prefixes from the P2P pool

### ISSUE THREAD

**Issue by ipspace** [ipspace/netlab#1421]
### Describe the bug

If you enable default gateway on a link with two routers attached to it, the prefix for the link comes out of the P2P pool and we run out of IP addresses.

### Expected behavior

The prefix for any link with default gateway should come from the LAN pool

### Lab topology

```
module: [ gateway ]
defaults.device: eos
gateway.protocol: vrrp

nodes:
  r1:
  r2:

links:
- gateway: True
  r1:
  r2:
```

### Version

* all netlab versions
