### ISSUE TITLE
Switch to Switch link with pool l2only

### ISSUE THREAD

**Issue by DanPartelly** [ipspace/netlab#1433]
Currently a topology like (see below) results on Cisco devices results in a interface config like:

interface Ethernet0/1
 description s2 -> s1
 no switchport
 no ip address

Wouldn't have more sense to just leave the interface of layer2 device in access mode instead of automatically turning it into a routed interface?

```
defaults:
    provider: clab
    device: ioll2
      
nodes: [s1, s2, s3]
links:
- s1:
  s2:
  pool: l2only  
```
