### ISSUE TITLE
[BUG] Node VLAN data is not copied into interface data when the access VLAN is defined on the interface

### ISSUE THREAD

**Issue by ipspace** [ipspace/netlab#1436]
When you define an access VLAN on an interface but not on the parent link, the node VLAN data is not copied into the interface data. It looks like the access VLAN information is copied into the link data too late to matter.

The bug was initially observed by @jbemmel when reviewing #1422, a proposed fix is in #1432

### Lab topology

```
---
module: [ vlan ]

defaults.device: eos

vlans:
  access:

nodes:
  a1:
    vlans.access.ipv4: 42
  a2:

links:
- a1:
    vlan.access: access
  a2:
    vlan.access: access
```

Adding `vlan.access` to the link definition results in the correct behavior, so the bug must be somewhere in the VLAN attribute initialization code.
