### ISSUE TITLE
[BUG] Mixing access VLANs on a link should be prohibited

### ISSUE THREAD

**Issue by ipspace** [ipspace/netlab#1437]
Netlab accepts a lab topology that links two global VLANs on an access link. The results are "suboptimal". For example, the VLANs get different IP prefixes but all the VLAN interfaces get IP addresses from one of the VLANs.

IIRC this behavior arose from the idea that one could have VLAN domains limited to a single node, and that in that case it might make sense to link two such domains.

I think we should disable this capability as it only leads to confusion, or at the very minimum enforce that one cannot do this with two global VLANs while generating a warning saying "this is not supported, you are on your own" if someone does that with per-node VLANs.

This might be the root cause for #1436 and is probably related to #1432, so I'll wait for the feedback from @jbemmel before proceeding.

### Lab topology

```
---
module: [ vlan ]

defaults.device: eos

vlans:
  access_1:
  access_2:

nodes:
  a1:
  a2:

links:
- a1:
    vlan.access: access_1
  a2:
    vlan.access: access_2
```
