### ISSUE TITLE
[BUG] Conflicting vlan access links list items not reported

### ISSUE THREAD

**Issue by jbemmel** [ipspace/netlab#1446]
Modified integration test case 63, removing the ```links``` section:
```
groups:
  _auto_create: True
  hosts:
    members: [ h1, h2, h3, h4 ]
    device: linux
    provider: clab
  switches:
    members: [ s1, s2 ]
    module: [ vlan, ospf ]

vlans:
  red:
    mode: bridge
    links: [ s1-h1, s2-h2, s1-s2 ]  # Added s1-s2
  blue:
    mode: route
    links: [ s1-h3, s2-h4, s1-s2 ]  # Added s1-s2
```

Wanted to test if this would create a trunk; it doesn't (which is fine) but we end up with a routed vlan (blue?) on s1-s2 and no warning or error:
```
- bridge_group: 2
  ifindex: 4
  ifname: eth4
  ipv4: 10.1.0.1/30
  linkindex: 6
  mtu: 1500
  name: s1 -> s2
  neighbors:
  - ifname: eth4
    ipv4: 10.1.0.2/30
    node: s2
  ospf:
    area: 0.0.0.0
    network_type: point-to-point
    passive: false
  type: p2p
  vlan:
    mode: route
```

If I change the blue vlan to ```mode: bridge``` we end up with 4 interfaces (2xred, 2xblue) on s1.

We could argue whether this is a bug or a new feature, and we may decide this is low priority; just wanted to document the oddity I noticed. And yes I read https://github.com/ipspace/netlab/blob/dev/docs/module/vlan.md#create-access-vlan-links and 's1-s2' shouldn't be in there, but you can put a duplicate host access link and it has the same issue

**Comment by jbemmel** [comment]
Minimal topology:
```
groups:
  _auto_create: True
  hosts:
    members: [ h1 ]
    device: linux
    provider: clab
  switches:
    members: [ s1 ]
    module: [ vlan ]

vlans:
  red:
    links: [ s1-h1 ]
  blue:
    links: [ s1-h1 ]  # Conflict
```
