### ISSUE TITLE
[BUG] duplicate IP assigned on "rt" in rt-vlan-mode-link-route.yml

### ISSUE THREAD

**Issue by jbemmel** [ipspace/netlab#1457]
On vlan ```red``` node ```rt``` is assigned the ip ```172.16.0.2/24``` on 2 different interfaces

https://github.com/ipspace/netlab/blob/352e8ba94664b5a3e92e23c9b40bf3efc6cbde19/tests/topology/expected/rt-vlan-mode-link-route.yml#L660

https://github.com/ipspace/netlab/blob/352e8ba94664b5a3e92e23c9b40bf3efc6cbde19/tests/topology/expected/rt-vlan-mode-link-route.yml#L695

FRR accepts this, but SR Linux does not

It arises from these 2 test cases:
```
defaults.device: frr
module: [ vlan ]

vlans:
  red:
    mode: route           # red VLAN is primarily routed

nodes:
  rt:
  br:
    vlan.mode: bridge     # And set the default VLAN mode to bridge

links:
- rt:
  br:
  vlan.trunk:
    red:                  # This one should be routed on S1 and bridged on S3
  name: Trunk with bridge
#  disable: True
- rt:
  br:                               # replace with a Linux host -> works, 2 different IPs
  vlan.access: red        # This one should be routed on S1 and bridged on S3
  name: Access link to bridge
```

Granted, this is not a common or "sane" topology. Replace ```br``` with a Linux host in the second link and it works; you get 2 different IPs
