### ISSUE TITLE
[BUG] Cannot set link address allocation mode without setting static prefix

### ISSUE THREAD

**Issue by ipspace** [ipspace/netlab#1458]
Let's assume we'd like to set the link allocation mode to "sequential" to support (for example) the same node having two attachments to the link (potentially in different VRFs).

The **prefix.allocation** parameter is accepted, but because the `links` module checks for presence of prefix (not whether it contains any data), a prefix is never allocated to the link.

### Expected behavior

The link should get a prefix from the default pool and the pool prefix parameters should be merged with the link prefix parameters.

Please note that this applies only to link prefix parameters that do not have the **ipv4** or **ipv6** attributes in which case there are no changes to the link addressing.

### Lab topology

```
defaults.device: frr

nodes: [ r1, r2 ]
links:
- prefix:
    allocation: sequential
  interfaces: [ r1, r1, r1, r2, r2, r3 ]
```

**Comment by ipspace** [comment]
@jbemmel This is based on your idea that we should be able to connect the same node to the same link more than once.

Would you agree with my assessment of what should be done in this case?

**Comment by jbemmel** [comment]
This isn't specific to self-links:
```
defaults.device: frr

nodes: [ r1, r2 ]
links:
- prefix:
    allocation: sequential
  interfaces: [ r1, r2 ]

```

result:
```
af:
  ipv4: true
box: generic/ubuntu2004
interfaces:
- ifindex: 1
  ifname: eth1
  libvirt:
    type: tunnel
  linkindex: 1
  name: r1 -> r2
  neighbors:
  - ifname: eth1
    node: r2
  remote_id: 2
  remote_ifindex: 1
  type: p2p
loopback:
  ifindex: 0
  ifname: lo
  ipv4: 10.0.0.1/32
  neighbors: []
  type: loopback
  virtual_interface: true
mgmt:
  ifname: eth0
  ipv4: 192.168.121.101
  mac: 08:4f:a9:00:00:01
```
