### ISSUE TITLE
[BUG] Check ifindex and ifname uniqueness

### ISSUE THREAD

**Issue by ipspace** [ipspace/netlab#1462]
Manual changes to **ifindex** or **ifname** could result in a scenario where multiple interfaces have the same ifindex or node name. We should add a mechanism to detect that and report it as a non-negotiable error.

### Lab topology

```
provider: clab
defaults.device: frr

nodes:
  n1:

links:
- n1:
    ifindex: 2
- n1:
```
