### ISSUE TITLE
[BUG] Consecutive 'netlab up --snapshot' invocations break Vagrant/libvirt

### ISSUE THREAD

**Issue by ipspace** [ipspace/netlab#1469]
If you execute "netlab up --snapshot" on a running libvirt-based topology you'll get a complete disaster due to the removal
and redefinition of management network.

### To Reproduce

Execute "netlab up" followed by "netlab up --snapshot"

### Expected behavior

The "netlab up --snapshot" command should realize Vagrant VMs are already running and leave the management network in place.

### Lab topology

```
defaults.device: cumulus

nodes:
  r1:
  r2:

links:
- r1-r2
```
