### ISSUE TITLE
Question: setting stp.priority for a set of VLANs

### ISSUE THREAD

**Issue by ddutt** [ipspace/netlab#1534]
The classic access-agg network has 2 aggregation switches where one of them is the primary root for one set of VLANs, and the other is root for the other set of VLANs. 

How do I do this in netlab? Stp priority is node specific it seems, and doesn't take vlan as a parameter

**Comment by DanPartelly** [comment]
nodes:
 s1:
  vlans.red.stp.priority: 4096

where vlan red is defined.

**Comment by jbemmel** [comment]
Hot off the press this week: global VLAN groups https://github.com/ipspace/netlab/pull/1529

For large numbers of vlans, node-level VLAN groups might be desirable for this use case:

```
---
nodes:
  agg1:
   groups:
    members: [v1,v2,v3,v4]
    type: vlan
    stp.priority: 4096
    
  agg2:
   groups:
    members: [v5,v6,v7,v8]
    type: vlan
    stp.priority: 4096
```

However, lacking that one could do:
```
agg1:
 vlans:
  v1.stp.priority: 4096
  v2.stp.priority: 4096
  ... etc
```
