### ISSUE TITLE
Ping validate check should print the address it's trying to reach

### ISSUE THREAD

**Issue by jbemmel** [ipspace/netlab#1540]
While working on ```lag``` I had to swap out the Linux hosts for FRR nodes. This resulted in more interfaces on the nodes, and it took me a while to realize that the simple ```ping``` validation checks had to be adjusted to account for the right target interface

Original:
```
plugin: ping('h2')
```

New:
```
plugin: ping(nodes.h2.interfaces[0].ipv4,af='ipv4')
```

**Comment by ipspace** [comment]
I don't get it. Are you saying what you want to have doesn't work today?

**Comment by jbemmel** [comment]
```
---
provider: clab
defaults.device: frr

groups:
 _auto_create: True
 hosts:
  members: [h1,h2]

links: [h1-h2]

validate:
 working_ping:
    description: IPv4 ping to device loopback
    wait: 10
    wait_msg: Waiting for IPv4 interfaces to become ready
    nodes: [ h1 ]
    plugin: ping(nodes.h2.loopback.ipv4)
 broken_ping:
    description: IPv4 ping to device
    nodes: [ h1 ]
    plugin: ping('h2')
```

Result:
```
jvanbemmel@vm:~/netlab/tests$ netlab validate
[working_ping] IPv4 ping to device loopback [ node(s): h1 ]
[WAITING]      Waiting for IPv4 interfaces to become ready (retrying for 10 seconds)
[FAIL]         Node h1: Ping to 10.0.0.2 failed

[broken_ping]  IPv4 ping to device [ node(s): h1 ]
[FAIL]         Node h1: Ping to h2 failed

[FAIL]         2 tests completed, 2 tests failed
```

The IP address it's trying to reach isn't shown until the 'FAIL' in the first case, and not at all in the second case.
This happened when I switched ```linux``` devices for ```frr``` devices
