### ISSUE TITLE
[BUG] Libvirt pre_transform hook is too aggressive in setting link.type='lan'

### ISSUE THREAD

**Issue by jbemmel** [ipspace/netlab#1546]
Encountered in the mlag feature branch
```
provider: clab

groups:
  _auto_create: True
  core:
    members: [ c1,c2 ]
    module: [ lag, vlan ]
    device: dellos10
    provider: clab

  tor:
    members: [ s1 ]
    device: linux
    provider: libvirt  # <- mixed provider causes issues with mlag_peer link

links:
- lag:
   mlag.peergroup: 255
   members: [c1-c2]
```

Without ```provider: libvirt``` this creates a link of type ```mlag_peer``` as intended. However, adding libvirt causes the link type to be set to ```lan```

The issue is here: https://github.com/ipspace/netlab/blob/e5f6268db24f70a5d0abaa5564ee5fa30a21068e/netsim/providers/libvirt.py#L281

This link is not a multi-provider link, both nodes are clab
