### ISSUE TITLE
Undefined behavior for BGP in case of ipv4:True with numbered ipv6

### ISSUE THREAD

**Issue by jbemmel** [ipspace/netlab#1562]
https://github.com/ipspace/netlab/blob/a1e1076bb4459eb85c75fe23bc13e2a7889a8fb9/tests/topology/expected/bgp-unnumbered-dual-stack.yml#L205

```
# interface 6 - IPv6 AF over IPv6 numbered, no IPv4 session/AF
- test:
  x4:
  prefix:
    ipv4: True
    ipv6: 2001:db8:1::/64
```

As the test case states, no IPv4 session should be created here. However, it does get created
