### ISSUE TITLE
[BUG] ping validation plugin does not honor 'af' parameter

### ISSUE THREAD

**Issue by jbemmel** [ipspace/netlab#1567]
```
nodes:
  dut:
  x1:
    bgp.as: 65100
    loopback:
      ipv4: 172.42.43.0/32
  x2:
    bgp.as: 65101
    loopback:
      ipv4: 172.42.42.1/24
      ipv6: 2001:db8:cafe:1::1/64

validate:
  ping:
    description: Check that the ipv4 datapath works
    nodes: [ x1 ]
    plugin: ping('x2',src=nodes.x1.loopback.ipv4,af='ipv4')
```

Results in:
```
[ping]    Check that the ipv4 datapath works [ node(s): x1 ]
run_command executing: ['docker', 'exec', '-it', 'clab-bgp-x1', 'bash', '-c', 'ping -c 5 -W 1 -A -I 172.42.43.0 x2 || true']
[FAIL]    Node x1: Ping to ipv4 x2 from 172.42.43.0/32 failed
Input data: {"stdout": "PING x2 (2001:db8:cafe:1::1): 56 data bytes\n\n--- x2 ping statistics ---\n5 packets transmitted, 0 packets received, 100% packet loss\n"}
Plugin expression: ping('x2',src=nodes.x1.loopback.ipv4,af='ipv4')
```

Branch: dev
