### ISSUE TITLE
[BUG] lag module fails in case of Multiprovider labs

### ISSUE THREAD

**Issue by jbemmel** [ipspace/netlab#1581]
Just a note that Multiprovider labs don't combine with the lag module at the moment, due to libvirt changing the link type from "lag" to "lan"

```
groups:
 _auto_create: True
 core:
  members: [ c1, c2 ]
  device: dellos10
  provider: clab
  module: [ lag ]
 edge:
  members: [ e1, e2 ]
  device: cumulus_nvue
  provider: libvirt
  module: [ lag ]
 hosts:
  members: [ h1, h2, h3, h4 ]
  device: linux

links:
- lag:
   mlag.peergroup: 1
   members: [c1-c2]
- lag:
   mlag: True
   members: [e1-c1,e1-c2]
- lag:
   mlag: True
   members: [e2-c1,e2-c2]
```
