### ISSUE TITLE
LAG: Support M:N MLAG configurations

### ISSUE THREAD

**Issue by jbemmel** [ipspace/netlab#1602]
The lag module currently assumes MLAG is between 1 device and N other devices. It should be possible to configure M:N mlags:

```
links:
- lag:
  mlag.peergroup: 1
  members: [ a1-a2 ]
- lag:
  mlag.peergroup: 1
  members: [ b1-b2 ]
- lag:
    mlag: True
    members: [ a1-b1, a2-b2 ]
```

The above example shows 2 pairs of switches, each configured as an MLAG pair and interconnected
