### ISSUE TITLE
[BUG] Duplicate IP assignment in VLAN P2P scenario

### ISSUE THREAD

**Issue by jbemmel** [ipspace/netlab#1610]
"bug" may be a strong word, "odd corner case" in an admittedly unusual topology - sharing for awareness.

Netlab fails to allocate IPs in the following topology:
```
prefix:
 p2p1:
  pool: p2p
  allocation: p2p # Oddly needed to trigger the bug

vlans:
 v1:
  prefix: p2p1

groups:
  _auto_create: True

  switches-a:
    members: [ a1, a2 ]
    module: [ vlan ]

    vlans:
     v1:
```

(adding a link with a trunk removes the bug)

The context is MLAG peers with a peerlink that trunks vlans implicitly.

### Output
```
jeroen@vm:~/Projects/netlab/tests$ netlab create integration/vlan/90-vlan-duplicate-ip.yml -d frr
[ERRORS]  Errors found in 90-vlan-duplicate-ip.yml
[VALUE]   vlan: Duplicate address 10.1.0.1/30 found on vlan v1: a2 and a1
[HINT]    Set defaults.warnings.duplicate_address to False to disable this check
[FATAL]   Cannot proceed beyond this point due to errors, exiting
```

### Version

'dev' branch
