### ISSUE TITLE
[BUG] Failure to allocate IP from P2P pool in case of access VLAN

### ISSUE THREAD

**Issue by jbemmel** [ipspace/netlab#1611]
Consider the following topology:
```
vlans:
 v1:
  pool: p2p

nodes:
  r:
    module: [vlan]
  h1:
    device: linux
    provider: clab
    id: 5

links:
- r:
    vlan.access: v1   # Fails: Cannot assign host index 5 in ipv4 from prefix 10.1.0.0/30 to node h1
  h1:
- r:
  h1:
  pool: p2p           # Works fine (assigns from subnet 10.1.0.4/30 if vlan is still defined)
```

The ```p2p``` pool should imply a ```p2p``` allocation strategy, which works in the case without an access vlan. However, when the VLAN is added an ```id_based``` allocation strategy gets applied - which fails

Release: dev branch
