### ISSUE TITLE
[BUG] Host static routes don't work if the first host interface is not a L3 interface

### ISSUE THREAD

**Issue by ipspace** [ipspace/netlab#1641]
The Linux configuration template assumes that the first data-plane interface is used for default in-lab routing. When that interface does not have an IP address, the static routes are not configured and the Linux host cannot reach anything but directly-connected subnets.

### Expected behavior

We need either a better Linux configuration template or additional logic in the "default gateway" code to set a flag when an interface can be used for default routing.

### Lab topology

```
---
provider: clab

nodes:
  rtr:
    device: frr
  h:
    device: linux

links:
- rtr:
  h:
  pool: l2only
- rtr:
  h:
```
