### ISSUE TITLE
[BUG] P2P links wrongly marked as 'multi-provider' LAN links

### ISSUE THREAD

**Issue by jbemmel** [ipspace/netlab#1658]
### Lab topology
```
---
defaults.device: frr
groups:
 _auto_create: True
 core:
  members: [ c1, c2 ]
  provider: clab
 edge:
  members: [ e1, e2 ]
  provider: libvirt

links:
- c1-c2
- e1-c1
- e2-c2
```

### Output
For host_vars/c1/topology.yml
```yaml
af:
  ipv4: true
box: quay.io/frrouting/frr:10.0.1
clab:
  binds:
  - clab_files/c1/daemons:/etc/frr/daemons
  - clab_files/c1/hosts:/etc/hosts
  config_templates:
  - daemons:/etc/frr/daemons
  - hosts:/etc/hosts
  kind: linux
hostname: clab-Automation-c1
interfaces:
- bridge: Automation_1   <-- bridge added
  ifindex: 1
  ifname: eth1
  ipv4: 172.16.0.1/24
  linkindex: 1
  mtu: 1500
  name: c1 -> c2
  neighbors:
  - ifname: eth1
    ipv4: 172.16.0.2/24
    node: c2
  type: lan                      <-- p2p changed to 'lan'
```

Version: netlab ```dev``` branch
