### ISSUE TITLE
[BUG] OSPF/ISIS BFD configuration ignores address family 

### ISSUE THREAD

**Issue by jbemmel** [ipspace/netlab#1661]
IGP modules have separate ```bfd.ipv4``` and ```bfd.ipv6``` flags, but they both get mapped to a single ```<igp>.bfd``` parameter.
It is therefore not possible to configure something like:
```
module: [ isis, bfd ]

isis:
 bfd:
  ipv4: False  <-- no BFD on ipv4 sessions
  ipv6: True
```

Version: all Netlab versions since bfd was introduced
