### ISSUE TITLE
[BUG] Unable to explicitly activate localas_ibgp sessions

### ISSUE THREAD

**Issue by jbemmel** [ipspace/netlab#1663]
Consider the following subtopology:
```
module: [ bgp ]

bgp.sessions:
  ipv4: [ebgp]

nodes:
  a:
    bgp.as: 65001
  b:
    bgp.as: 65002
  c:
    bgp.as: 65003

links:
- a-b
- a-c
- b:
    bgp.local_as: 65003
  c:
```

If left as default, ```bgp.sessions.ipv4``` is ```['ibgp','ebgp','localas_ibgp']```. However, "localas_ibgp" is not a valid value in https://github.com/ipspace/netlab/blob/c88777ae908877a4074cb2b522b9e51fa9d21ec9/netsim/modules/bgp.yml#L31
