### ISSUE TITLE
[BUG] IPv6 is not working over multi-access clab links

### ISSUE THREAD

**Issue by ipspace** [ipspace/netlab#1669]
IPv6 is not working between three nodes connected to the same link. The same setup works with libvirt, meaning we probably have a problem with the setup of the netlab-created Linux bridge.

### To Reproduce

Run the following topology with **libvirt** provider. X1 can ping X2. Restart the same topology with **clab** provider. X1 can reach X2 over IPv4 but not over IPv6.

### Lab topology

```
---
addressing:
  loopback:
    ipv6: 2001:db8:1::/48
  lan:
    ipv6: 2001:db8:2::/48

defaults.device: linux

nodes:
  x1:
  x2:
  x3:

links:
- x1-x2-x3
```

### Version

```
$ lsb_release -a
No LSB modules are available.
Distributor ID:	Ubuntu
Description:	Ubuntu 22.04.4 LTS
Release:	22.04
Codename:	jammy
```
