### ISSUE TITLE
[BUG] Vagrant fails to start when VM name starts with UPPERcase

### ISSUE THREAD

**Issue by adamcirillo** [ipspace/netlab#1675]
### Describe the bug

My lab I made can't start up using libvirt for nexus getting the following error. using the image nexus9300v64-lite.10.5.2.F.box
i used the instructions in the documentation to mutate the box and deleted the virtual box version as well.

plugins listed below and versions

```
vagrant-libvirt (0.12.2, global)
  - Version Constraint: 0.12.2
vagrant-mutate (1.2.0, global)
```

```
[CREATED] creating libvirt management network vagrant-libvirt
provider libvirt: executing vagrant up --provider libvirt
Vagrant failed to initialize at a very early stage:

There is a syntax error in the following Vagrantfile. The syntax error
message is reproduced below for convenience:

/home/netlab/adamlab/Vagrantfile:9: formal argument cannot be a constant
...onfig.vm.define vm_name do |NX1|
...                            ^~~
/home/netlab/adamlab/Vagrantfile:108: formal argument cannot be a constant
...onfig.vm.define vm_name do |NX2|
...                            ^~~
/home/netlab/adamlab/Vagrantfile:207: formal argument cannot be a constant
...onfig.vm.define vm_name do |NX3|
...                            ^~~
/home/netlab/adamlab/Vagrantfile:330: formal argument cannot be a constant
...onfig.vm.define vm_name do |NX4|
...                            ^~~
Error executing vagrant up --provider libvirt:
  Command '['vagrant', 'up', '--provider', 'libvirt']' returned non-zero exit status 1.
[FATAL]   netlab up: vagrant up --provider libvirt failed, aborting...
```

also if i do provider via defaults.device.nxos.provider: libvirt i get this error instead.

```
[ERRORS]  Errors found in topology.yml
[ATTR]    links: Incorrect link attribute 'provider' in links.CE107[2].clab
[ATTR]    links: Incorrect link attribute 'provider' in links.CE107[3].clab
[ATTR]    links: Incorrect link attribute 'provider' in links.CE107[4].clab
[ATTR]    links: Incorrect link attribute 'provider' in links.CE107[5].clab
[ATTR]    links: Incorrect link attribute 'provider' in links.CE107[6].clab
[ATTR]    links: Incorrect link attribute 'provider' in links.CE108[2].clab
[ATTR]    links: Incorrect link attribute 'provider' in links.CE108[3].clab
[ATTR]    links: Incorrect link attribute 'provider' in links.CE108[4].clab
[ATTR]    links: Incorrect link attribute 'provider' in links.CE108[5].clab
[ATTR]    links: Incorrect link attribute 'provider' in links.CE108[6].clab
[FATAL]   Cannot proceed beyond this point due to errors, exiting
```

### To Reproduce

load the topology

### Expected behavior

the topology should load

### Lab topology

```
defaults:
    device: iosxr
    provider: clab
    defaults.providers.clab.bridge_type: ovs-bridge
    devices.iosxr.clab.image: ios-xr/xrd-control-plane
    devices.ioll2.clab.image: vrnetlab/cisco_iol:L2-17.15.01
    devices.iol.clab.image: vrnetlab/cisco_iol:17.15.01
    devices.nxos.memory: 8192
    devices.nxos.libvirt.image: cisco/nexus9300v
    devices.nxos.clab.image: vrnetlab/cisco_nxos9000v
    devices.nxos.clab.group_vars.netlab_check_retries: 30


nodes:
    CE107:
        device: iosxr
        graphite.icon: router
        id: 13
    NX1:
        device: nxos
        provider: libvirt
        graphite.icon: nexus5000
        id: 24
links:
    CE107:
     - NX1:
        ifindex: 7
        ipv4: 192.168.117.1/24
       CE107:
        ifindex: 1
        ipv4: 192.168.117.109/24

```

### Output

```
[WARNING] providers: Topology provider changed from clab to libvirt. Nodes are not affected
[CREATED] provider configuration file: Vagrantfile
[INFO]    Creating configuration file for secondary provider clab
[CREATED] provider configuration file: clab-augment.yml
[CREATED] transformed topology dump in YAML format in netlab.snapshot.yml
[GROUPS]  group_vars for all
[GROUPS]  group_vars for iosxr
[HOSTS]   host_vars for CE107
[GROUPS]  group_vars for nxos
[HOSTS]   host_vars for NX1
[CREATED] minimized Ansible inventory hosts.yml
[CREATED] Ansible configuration file: ansible.cfg
```
netlab up on the minimum topology gives this
```
┌──────────────────────────────────────────────────────────────────────────────────┐
│ CREATING configuration files                                                     │
└──────────────────────────────────────────────────────────────────────────────────┘
[WARNING] providers: Topology provider changed from clab to libvirt. Nodes are not affected
 [DEPRECATED] PARAMIKO_HOST_KEY_AUTO_ADD option. Reason: This option was moved to the plugin itself
Alternatives: Use the option from the plugin itself., to be removed in 2.20
[CREATED] provider configuration file: Vagrantfile
[INFO]    Creating configuration file for secondary provider clab
[CREATED] provider configuration file: clab-augment.yml
[CREATED] transformed topology dump in YAML format in netlab.snapshot.yml
[GROUPS]  group_vars for all
[GROUPS]  group_vars for iosxr
[HOSTS]   host_vars for CE107
[GROUPS]  group_vars for nxos
[HOSTS]   host_vars for NX1
[CREATED] minimized Ansible inventory hosts.yml
[CREATED] Ansible configuration file: ansible.cfg

┌──────────────────────────────────────────────────────────────────────────────────┐
│ CHECKING virtualization provider installation                                    │
└──────────────────────────────────────────────────────────────────────────────────┘
[SUCCESS] libvirt installed and working correctly
[SUCCESS] clab installed and working correctly

┌──────────────────────────────────────────────────────────────────────────────────┐
│ STARTING libvirt nodes                                                           │
└──────────────────────────────────────────────────────────────────────────────────┘
[CREATED] creating libvirt management network vagrant-libvirt
provider libvirt: executing vagrant up --provider libvirt
Vagrant failed to initialize at a very early stage:

There is a syntax error in the following Vagrantfile. The syntax error
message is reproduced below for convenience:

/home/netlab/testlab/Vagrantfile:9: formal argument cannot be a constant
...onfig.vm.define vm_name do |NX1|
...                            ^~~
Error executing vagrant up --provider libvirt:
  Command '['vagrant', 'up', '--provider', 'libvirt']' returned non-zero exit status 1.
[FATAL]   netlab up: vagrant up --provider libvirt failed, aborting...
```
### Version

* 1.9.2-post1

### Additional context

also netlab down --cleanup gives a similar error as well

```
[SUCCESS] Read transformed lab topology from snapshot file netlab.snapshot.yml

┌──────────────────────────────────────────────────────────────────────────────────┐
│ CHECKING virtualization provider installation                                    │
└──────────────────────────────────────────────────────────────────────────────────┘
[SUCCESS] libvirt installed and working correctly
[SUCCESS] clab installed and working correctly

┌──────────────────────────────────────────────────────────────────────────────────┐
│ STOPPING clab nodes                                                              │
└──────────────────────────────────────────────────────────────────────────────────┘
INFO[0000] Parsing & checking topology file: clab-augment.yml 
INFO[0000] no containerlab containers found             


┌──────────────────────────────────────────────────────────────────────────────────┐
│ STOPPING libvirt nodes                                                           │
└──────────────────────────────────────────────────────────────────────────────────┘
Vagrant failed to initialize at a very early stage:

There is a syntax error in the following Vagrantfile. The syntax error
message is reproduced below for convenience:

/home/netlab/testlab/Vagrantfile:9: formal argument cannot be a constant
...onfig.vm.define vm_name do |NX1|
...                            ^~~
Error executing vagrant destroy -f:
  Command '['vagrant', 'destroy', '-f']' returned non-zero exit status 1.
[FATAL]   netlab down: vagrant destroy -f failed, aborting...
```

**Comment by jbemmel** [comment]
The syntax of your ```links:``` section is wrong - it should be a list

```
CE107:
     - NX1:
        ifindex: 7
        ipv4: 192.168.117.1/24
       CE107:
        ifindex: 1
        ipv4: 192.168.117.109/24
```

try
```
links:
- NX1:
    ifindex: 7
    ipv4: 192.168.117.1/24
  CE107:
    ifindex: 1
    ipv4: 192.168.117.109/24
```

Still a potential "bug" in the sense that the error should get caught before invoking libvirt

**Comment by adamcirillo** [comment]
i tried ths topology got the same error

```
defaults:
    device: iosxr
    provider: clab
    defaults.providers.clab.bridge_type: ovs-bridge
    devices.iosxr.clab.image: ios-xr/xrd-control-plane
    devices.ioll2.clab.image: vrnetlab/cisco_iol:L2-17.15.01
    devices.iol.clab.image: vrnetlab/cisco_iol:17.15.01
    devices.nxos.memory: 8192
    devices.nxos.libvirt.image: cisco/nexus9300v
    devices.nxos.clab.image: vrnetlab/cisco_nxos9000v
    devices.nxos.clab.group_vars.netlab_check_retries: 30


nodes:
    CE107:
        device: iosxr
        graphite.icon: router
        id: 13
    NX1:
        device: nxos
        provider: libvirt
        graphite.icon: nexus5000
        id: 24
links:
- NX1:
    ifindex: 7
    ipv4: 192.168.117.1/24
  CE107:
    ifindex: 1
    ipv4: 192.168.117.109/24
```

```
┌──────────────────────────────────────────────────────────────────────────────────┐
│ CREATING configuration files                                                     │
└──────────────────────────────────────────────────────────────────────────────────┘
[WARNING] providers: Topology provider changed from clab to libvirt. Nodes are not affected
[CREATED] provider configuration file: Vagrantfile
[INFO]    Creating configuration file for secondary provider clab
[CREATED] provider configuration file: clab-augment.yml
[CREATED] transformed topology dump in YAML format in netlab.snapshot.yml
[GROUPS]  group_vars for all
[GROUPS]  group_vars for iosxr
[HOSTS]   host_vars for CE107
[GROUPS]  group_vars for nxos
[HOSTS]   host_vars for NX1
[CREATED] minimized Ansible inventory hosts.yml
[CREATED] Ansible configuration file: ansible.cfg

┌──────────────────────────────────────────────────────────────────────────────────┐
│ CHECKING virtualization provider installation                                    │
└──────────────────────────────────────────────────────────────────────────────────┘
[SUCCESS] libvirt installed and working correctly
[SUCCESS] clab installed and working correctly

┌──────────────────────────────────────────────────────────────────────────────────┐
│ STARTING libvirt nodes                                                           │
└──────────────────────────────────────────────────────────────────────────────────┘
[CREATED] creating libvirt management network vagrant-libvirt
provider libvirt: executing vagrant up --provider libvirt
Vagrant failed to initialize at a very early stage:

There is a syntax error in the following Vagrantfile. The syntax error
message is reproduced below for convenience:

/home/netlab/testlab/Vagrantfile:9: formal argument cannot be a constant
...onfig.vm.define vm_name do |NX1|
...                            ^~~
Error executing vagrant up --provider libvirt:
  Command '['vagrant', 'up', '--provider', 'libvirt']' returned non-zero exit status 1.
[FATAL]   netlab up: vagrant up --provider libvirt failed, aborting...
```
