### ISSUE TITLE
[BUG] IBGP sessions are not established with routing daemons in host mode

### ISSUE THREAD

**Issue by ipspace** [ipspace/netlab#1686]
In a single-AS BGP network with a BGP router and bird daemon (running as host), the IBGP neighbor is not created on the router side

### Lab topology

```
module: [ bgp, ospf ]

provider: clab
defaults.bgp.as: 65000
defaults.interfaces.mtu: 1500

nodes:
  dut:
    device: bird
  x1:
    device: frr

links:
- dut-x1
```

### Output

```
$ netlab inspect --node dut bgp.neighbors
- _source_ifname: {}
  activate:
    ipv4: true
  as: 65000
  ipv4: 10.0.0.2
  name: x1
  type: ibgp
$ netlab inspect --node x1 bgp.neighbors
[]
```
