### ISSUE TITLE
[BUG] unnumbered interfaces are not transformed into "ipv4: True" for host-node routing daemons

### ISSUE THREAD

**Issue by ipspace** [ipspace/netlab#1692]
bird does not support unnumbered interfaces or BGP unnumbered. However, netlab does not report that leaves "unnumbered: True" in interface data.

### Lab topology

```
module: [ bgp ]

provider: clab
bgp.as: 65000

nodes:
  dut:
    device: bird
  x1:
    device: iosv

links:
- dut:
  x1:
  unnumbered: True
```

### Output

The "unnumbered interfaces are unsupported" error is generated for IOSv but not for bird

```
$ netlab create test.yml
[ERRORS]  Errors found in test.yml
[VALUE]   interfaces: Device iosv does not support unnumbered IPv4 interfaces
[HINT]    Used on node x1 interface GigabitEthernet0/1 (link x1 -> dut)
[FATAL]   Cannot proceed beyond this point due to errors, exiting
```

Also, the x1 interface has "ipv4: True" (when changing X1 device type to FRR) while the bird interface has "unnumbered: True"

```
$ netlab inspect --node x1 interfaces
- _parent_intf: lo
  _parent_ipv4: 10.0.0.2/32
  bridge: X_1
  ifindex: 1
  ifname: eth1
  ipv4: true
  linkindex: 1
  mtu: 1500
  name: x1 -> dut
  neighbors:
  - ifname: eth1
    node: dut
  type: lan
  unnumbered: true

$ netlab inspect --node dut interfaces
- bridge: X_1
  ifindex: 1
  ifname: eth1
  linkindex: 1
  mtu: 1500
  name: dut -> x1
  neighbors:
  - ifname: eth1
    ipv4: true
    node: x1
  type: lan
  unnumbered: true
```
