### ISSUE TITLE
bgp.session attributes do not get applied in bgp.multihop lab

### ISSUE THREAD

**Issue by jbemmel** [ipspace/netlab#1693]
https://github.com/ipspace/netlab/blob/379026a2127f2512d6c9b1ecc1d4cbcaa91fcb1b/tests/integration/bgp.multihop/01-global.yml#L31

The ```passive``` attribute defined towards neighbor PE2 is not processed by the ```bgp.session``` plugin, "bgp.session" is not added to the list of configuration scripts to be applied

**Comment by jbemmel** [comment]
The resulting topology from
```
bgp.multihop.sessions:
- dut:
  pe2:
    passive: True
```

is actually confusing to me - I would expect pe2 to apply the 'passive' configuration, not dut

**Comment by ipspace** [comment]
Lab topology:

```
module: [ bgp ]
plugin: [ bgp.session, ebgp.multihop ]

defaults.device: frr

bgp.multihop.sessions:
- a:
  c:
    passive: True

nodes:
  a:
    bgp.as: 65000
  b: { module: [ routing ] }
  c:
    bgp.as: 65001

links: [ a-b, b-c ]
```

Final BGP configuration on A:

```
router bgp 65000
 bgp router-id 10.0.0.1
 no bgp default ipv4-unicast
 bgp bestpath as-path multipath-relax
 neighbor 10.0.0.3 remote-as 65001
 neighbor 10.0.0.3 description c
 neighbor 10.0.0.3 ebgp-multihop
 neighbor 10.0.0.3 update-source lo
 !
 address-family ipv4 unicast
  network 10.0.0.1/32
  neighbor 10.0.0.3 activate
  no neighbor 10.0.0.3 send-community extended
 exit-address-family
exit
```

Final BGP configuration on C:

```
router bgp 65001
 bgp router-id 10.0.0.3
 no bgp default ipv4-unicast
 bgp bestpath as-path multipath-relax
 neighbor 10.0.0.1 remote-as 65000
 neighbor 10.0.0.1 description a
 neighbor 10.0.0.1 passive
 neighbor 10.0.0.1 ebgp-multihop
 neighbor 10.0.0.1 update-source lo
 !
 address-family ipv4 unicast
  network 10.0.0.3/32
  neighbor 10.0.0.1 activate
  no neighbor 10.0.0.1 send-community extended
 exit-address-family
exit
```

It looks to me like exactly what I was asking for.
