### ISSUE TITLE
[BUG] Using "config" on a group with no members disables it on other group(s)

### ISSUE THREAD

**Issue by ipspace** [ipspace/netlab#1705]
This is the weirdest one I found so far. If you have a group with no members and a **config** attribute, the **config** attribute _from another group_ does not get applied to its members.

### Lab topology

```
defaults.device: eos
provider: clab

nodes:
  a:

groups:
  spines:
    members: [ a ]
    config: [ X ]
  leaves:
    config: [ X ]
```

### Output

```
% netlab create test.yml -o yaml:nodes.S1
_fabric_count: 1
af:
  ipv4: true
box: ceos:4.32.1F
clab:
  env:
    CLAB_MGMT_VRF: management
    INTFTYPE: et
  kind: ceos
device: eos
hostname: clab-X-S1
id: 2
...
```

As you can see, there's no **config** attribute in S1.
