### ISSUE TITLE
[BUG] Topology with unmanaged nodes fails to create/deploy

### ISSUE THREAD

**Issue by jbemmel** [ipspace/netlab#1773]
Sample topology:
```
---
nodes:
  n1:
  n2:
    unmanaged: True

links: [ n1-n2 ]
```

Using Containerlab, ```create``` works but deployment fails as there is a link with only 1 endpoint

Using Libvirt, ```create``` fails with "Cannot find remote node ID on a P2P link"
