### ISSUE TITLE
[BUG] Bonding plugin fails to move VLAN subinterfaces to bond

### ISSUE THREAD

**Issue by jbemmel** [ipspace/netlab#1802]
The bonding plugin needs more work in combination with VLANs, the following does not work correctly:

```
plugin: [ bonding ]

vlans:
  v1:

groups:
 _auto_create: True
 nodes:
  members: [ n1, n2, n3 ]
  device: frr
  module: [ vlan ]

links:
- n1:
   bonding.ifindex: 1
  n2:
  vlan.trunk: [ v1 ]
- n1:
   bonding.ifindex: 1
  n3:
  vlan.trunk: [ v1 ]
```

Need to create integration test cases for the basic use case with Linux hosts, and the VLAN case
