### ISSUE TITLE
Data model needed to support RFC 8950 (extended BGP next hops)

### ISSUE THREAD

**Issue by ipspace** [ipspace/netlab#181]
With RFC 8950 (and 5549, but nobody ever implemented that one apart from Cumulus for unnumbered EBGP) it became possible to freely mix BGP transport sessions, address families, and next hop AFIs. We might need a data model (in the future once EVPN, L3VPN and SRv6 are implemented on a wide range of devices) to support that Jenga tower of Cluedo-like combinatorial complexity.

We need to be able to specify:

* What happens on IBGP versus EBGP sessions
* Which transport sessions we'd like to have (assuming they are possible according to addressing setup)
* Which address families we'd like to run over which transport session
* What next hop we'd like to use for individual address families.

The only generic way to address that at the moment would be a giant data structure _type_._transport_._af_._next hop_. For example, the default setup would be:

```
bgp.af_map:
  ibgp:
    ipv4: [ ipv4 ]
    ipv6: [ ipv6 ]
  ebgp:
    ipv4: [ ipv4 ]
    ipv6: [ ipv6 ]
    unnumbered: [ ipv4, ipv6 ]  # to support implicit RFC 5549 used by Cumulus on EBGP unnumbered
```

Standard BGP-LU would be:

```
bgp.af_map:
  ibgp:
    ipv4:
      ipv4:
        nexthop: mpls
    ipv6:
      ipv6:
        nexthop: mpls
  ebgp:
    ipv4: [ ipv4 ]
    ipv6: [ ipv6 ]
```

What we'd need to support 6PE would be (where **mpls** stands for _Labeled Unicast_)

````
bgp.af_map:
  ibgp:
    ipv4:
      ipv4: True
      ipv6:
        nexthop: mpls
  ebgp:
    ipv4: [ ipv4 ]
    ipv6: [ ipv6 ]
    unnumbered: [ ipv4, ipv6 ]  # to support implicit RFC 5549 used by Cumulus on EBGP unnumbered
````

What @jbemmel would like to see for his SRv6 example would be:

```
bgp.af_map:
  ibgp:
    ipv6:
      ipv4:
        next_hop: ipv6
  ebgp:
    ipv4: [ ipv4 ]
```

Hopefully noone in his right mind would tweak that map by hand, it should be done by other modules/plugins. Also, you might have noticed "please keep me sane" shortcuts (list instead of nested dictionaries) that would be expanded at the evaluation time.

Finally, the **bgp.af_map** would be a no-propagate attribute so we won't end with the fully-evaluated map in node data. It should only be used inside the BGP module to build BGP neighbor data:

* Trim unnecessary transport sessions in bgp.py based on first two levels of **bgp.af_map** hierarchy
* Build **activate** attribute in **node.bgp.neighbors** list to activate individual AF over transport sessions based on the third and optionally fourth level of the hierarchy.

Thoughts anyone? /cc @jbemmel @ssasso @petercrocker
