### ISSUE TITLE
[BUG] BGP localas_ibgp session becomes ebgp on VLAN interface

### ISSUE THREAD

**Issue by jbemmel** [ipspace/netlab#1812]
While trying to address https://github.com/ipspace/netlab/issues/1808:

```yaml
module: [ bgp, vlan ]

vlans:
  v1:

groups:
  probes:
    device: frr
    provider: clab
    members: [ x1, x2 ]

defaults.bgp.as: 65000
defaults.interfaces.mtu: 1500

nodes:
  dut:
    bgp.originate: 172.42.42.0/24
  x1:
    bgp.as: 65100
    loopback.ipv4: 172.42.1.1/24
  x2:
    bgp.as: 65101
    loopback.ipv4: 172.42.2.1/24

links:
- dut:
    bgp.local_as: 65002
  x1:
- dut:
    bgp.local_as: 65101
  x2:
  vlan.trunk: [ v1 ]
```

This is ```bgp/08-ibgp-localas.yml``` with a VLAN added; unfortunately the localas_ibgp session to ```x2``` becomes an ebgp session
