### ISSUE TITLE
[BUG] Config template variable values containing spaces are not passed correctly

### ISSUE THREAD

**Issue by jbemmel** [ipspace/netlab#1820]
```
e2_add_vlan1001:
    description: Add VLAN 1001 to the trunk on e2
    nodes: [ e2 ]
    config:
      template: add_vlan
      variable:
       vlan: 1001
       intf: "ethernet 1/1/2"
    pass: VLAN 1001 added to E2 trunk
    stop_on_error: True
```

The above snippet fails because "ethernet 1/1/2" is passed without quotes on the command line
