### ISSUE TITLE
[BUG] Cumulus_NVUE VRRPv6 validation fails because EOS is forwarding its router advertisements

### ISSUE THREAD

**Issue by jbemmel** [ipspace/netlab#1821]
Weird but happening: test lab
```
links:
- r_eos:
  r_cumulus_nvue:
  h1:
  prefix.ipv6: 2001::/64
- r_eos:
  r_cumulus_nvue:
  h2:
  prefix.ipv6: 2002::/64
```

the test fails when h1 tries to ping h2; this fails because h1 believes h2 is on the same link, as it received a RA for 2002::/64 from r_cumulus_nvue forwarded by r_eos (received as multicast on eth2, forwarded on eth1)

It works fine with regular Cumulus (which uses older image ```CumulusCommunity/cumulus-vx:4.4.5```). The RA packets are the same, only the timing differs (regular Cumulus starts sending RA earlier in the process)

![Image](https://github.com/user-attachments/assets/11d4ad68-bded-46c8-b056-96e1dba01abf)

This is captured inside the EOS Containerlab namespace; packet #69 is a RA sent by Cumulus_NVUE, in packet #71 it gets forwarded
