### ISSUE TITLE
[BUG] Static routes with IPv4/IPv6 next hops work on FRR but not Linux

### ISSUE THREAD

**Issue by ipspace** [ipspace/netlab#1822]
The Linux static route quirk check expects to see an outgoing interface for each static route (Linux does not support static routes to remote next hops), but the https://github.com/ipspace/netlab/blob/dev/netsim/modules/routing.py#L728 does not add interface information to routes that have **ipv4** or **ipv6** next-hop attributes.

### Lab topology

```
nodes:
  h1:
    device: linux
    module: [ routing ]
    routing.static:
    - prefix: target
      nexthop:
        ipv4: 172.16.33.42

links:
- h1:
  prefix.ipv4: 172.16.33.0/24
```

### Output

```
[ERRORS]  Errors found in 02-vrrp.yml
[TYPE]    quirks: Linux (node h1) does not support static routes to non-connected next hops
[DATA]    Static route data: {'prefix': 'target', 'nexthop': {'ipv4': '172.16.33.42', 'idx': 0}, 'ipv4': '172.16.44.0/24' }
```
