### ISSUE TITLE
[BUG] Do not allow MTU lower than 1280 on IPv6-enabled interfaces

### ISSUE THREAD

**Issue by ipspace** [ipspace/netlab#1846]
The minimum MTU allowed by IPv6 standards is 1280. netlab should not allow setting interface MTU below 1280 for IPv6-enabled interfaces/links.

### Lab topology

```
---
defaults.device: eos
provider: clab
module: [ ospf, vlan ]

addressing:
  lan.ipv6: 2001:db8:cafe::/48

nodes: [ r1, r2 ]

links:
- r1:
  r2:
  pool: lan
  mtu: 800
```

### Output

Some devices throw an error during the configuration process, others silently disable IPv6. For example:

```
r1#show ipv6 int
Ethernet1 is up, line protocol is up (connected)
  IPv6 is stalled, link-local is unassigned
  Configured MTU value (800) is less than the IPv6 minimum of 1280, IPv6 is disabled
  Global unicast address(es):
    2001:db8:cafe::1, subnet is 2001:db8:cafe::/64 [INACTIVE]
  No joined group addresses
  ND DAD status is unavailable
  ND Reachable time is 30000 milliseconds
  ND retransmit interval is 1000 milliseconds
  ND enhanced duplicate address detection disabled
  ND advertised reachable time is 1 milliseconds (using 1)
  ND advertised retransmit interval is 1000 milliseconds
  ND router advertisements are sent every 5 seconds
  ND router advertisements live for 1800 seconds
  ND advertised default router preference is Medium
  ND advertised maximum hop count limit is 64
  Hosts use stateless autoconfig for addresses.
  ND unsolicited NAs are not accepted
  ND cache expiry time is 14400 seconds
```
