### ISSUE TITLE
[BUG] Group node-data should be copied by value, not by reference

### ISSUE THREAD

**Issue by ipspace** [ipspace/netlab#1847]
Sometimes complex data structures get copied from **groups** to **nodes** by reference. Modifying those structures in one node changes them in another node.

### Lab topology

```
defaults.device: eos
provider: clab

groups:
  probes:
    members: [ p1, p2 ]
    module: [ routing ]
    device: eos
    provider: clab
    routing.static:
    - ipv4: 0.0.0.0/0
      nexthop.node: dut

nodes: [ dut, p1, p2 ]
links:
- p1:
  dut:
  pool: lan
- p2:
  dut:
  pool: lan
```

### Output

The routing.static data for P2 is completely wrong:

```
$ netlab inspect --node p1,p2 routing.static
┏━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━━━━┓
┃ p1                   ┃ p2                   ┃
┡━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━━┩
│ - ipv4: 0.0.0.0/0    │ - ipv4: 0.0.0.0/0    │
│   nexthop:           │   nexthop:           │
│     idx: 0           │     idx: 0           │
│     intf: Ethernet1  │     intf: Ethernet1  │
│     ipv4: 172.16.0.1 │     ipv4: 172.16.0.1 │
│                      │ - ipv4: 0.0.0.0/0    │
│                      │   nexthop:           │
│                      │     idx: 0           │
│                      │     intf: Ethernet1  │
│                      │     ipv4: 172.16.0.1 │
└──────────────────────┴──────────────────────┘
```
