### ISSUE TITLE
[BUG] Cumulus templates do not bring up L2-only interfaces

### ISSUE THREAD

**Issue by jbemmel** [ipspace/netlab#1863]
When extending ```31-vlan-bridge-trunk.yml``` with untagged ports:
```
links:
- s1:
  s2:
  vlan.trunk: [ red, blue ]

- s1:
    ipv4: False
  h5:
  prefix:
    ipv4: 172.31.1.0/24
- s2:
    ipv4: False
  h6:
  prefix:
    ipv4: 172.31.1.0/24
```

```swp2``` on each Cumulus device doesn't come up

Fix: move https://github.com/ipspace/netlab/blob/d07e481703cc6fb5851a3699fb3c25059c6a7aed/netsim/ansible/templates/initial/cumulus.j2#L76 a few lines down, just before ```if l.ipv4 == True```

We'd probably also want to disable ipv6 on l2-only interfaces

**Comment by jbemmel** [comment]
Note that FRR does not have this issue due to https://github.com/ipspace/netlab/blob/d07e481703cc6fb5851a3699fb3c25059c6a7aed/netsim/ansible/templates/initial/frr.j2#L132

It might be better to uncomment https://github.com/ipspace/netlab/blob/d07e481703cc6fb5851a3699fb3c25059c6a7aed/netsim/ansible/templates/initial/cumulus.j2#L140 - it does make a difference, as 'no shutdown' brings the interface up (but still doesn't configure the MTU)

**Comment by ipspace** [comment]
I agree that it's not nice that the interfaces are not brought up, but as you didn't configure anything on them, it's not a big problem anyway ;)

**Comment by ipspace** [comment]
Also, the minimum topology to reproduce the problem has nothing to do with VLANs or trunks:

```
---
nodes:
  s1:
    device: cumulus
  h:
    device: linux

links:
- s1:
    ipv4: False
  h:
```
