### ISSUE TITLE
[BUG] Cumulus_NVUE enables IPv6 LLA on L2-only interfaces

### ISSUE THREAD

**Issue by jbemmel** [ipspace/netlab#1864]
Similar to previous issue, modify ```31-vlan-bridge-trunk.yml```:
```
links:
- s1:
  s2:
  vlan.trunk: [ red, blue ]

- s1:
    ipv4: False
  h5:
  prefix:
    ipv4: 172.31.1.0/24
- s2:
    ipv4: False
  h6:
  prefix:
    ipv4: 172.31.1.0/24
```

On Cumulus NVUE, ```swp2``` gets an IPv6 LLA. Same applies to all VLAN interfaces

Suggested fix: https://github.com/ipspace/netlab/blob/d07e481703cc6fb5851a3699fb3c25059c6a7aed/netsim/ansible/templates/initial/cumulus_nvue.j2#L44

```
{%  else %}
        ip:
          ipv6:
            enable: off
{%    if i.type=='lag' %}
        bridge:
          domain:
            br_default: {}
{%    endif %}
{%  endif %}
```
