### ISSUE TITLE
[BUG] Cumulus_NVUE and Dell OS10 pass native VLAN on trunks by default

### ISSUE THREAD

**Issue by jbemmel** [ipspace/netlab#1866]
Following up on https://github.com/ipspace/netlab/issues/1862

Modified ```31-vlan-bridge-trunk``` test:
```
vlans:
  red:
    mode: bridge
    prefix:
      ipv4: 172.31.1.0/24
    links: [ s1-h1, s2-h2 ]
  blue:
    mode: bridge
    prefix:
      ipv4: 172.31.1.0/24
    links: [ s1-h3, s2-h4 ]

  untagged: # Untagged links to test that device isn't passing the default VLAN on the trunk
    id: 1
    mode: bridge
    prefix:
      ipv4: 172.31.1.0/24
    links: [ s1-h5, s2-h6 ]

validate:
  ...
  untagged_vlan:
    description: Ping-based reachability test on untagged VLAN
    nodes: [ h5 ]
    plugin: ping('h6',expect='fail')
```

Both Cumulus_NVUE and Dell OS10 currently fail this test
