### ISSUE TITLE
[BUG] Different interpretations of VLAN 1 in trunk: Cumulus tagged, EOS untagged

### ISSUE THREAD

**Issue by jbemmel** [ipspace/netlab#1876]
https://github.com/ipspace/netlab/pull/1869/commits/ddec12cdaf11c54d9586bd3b7d0e237cdf82bbd1 removed a test targeting a topology with VLAN 1 in a trunk:
```
vlans:
  red:
    id: 1 # VLAN 1 on trunk, but not marked as 'native'
    mode: bridge
    prefix:
      ipv4: 172.31.1.0/24
    links: [ s1-h1, s2-h2 ]
  blue:
    mode: bridge
    prefix:
      ipv4: 172.31.1.0/24
    links: [ s1-h3, s2-h4 ]

links:
- s1:
  s2:
  vlan.trunk: [ red, blue ]
  # vlan.native: red
```

This test highlights an interop issue between Cumulus NVUE and EOS: Cumulus configures the ```red``` VLAN as tagged, while EOS makes it untagged
