### ISSUE TITLE
[DOC] Explain that l2-only interface does not imply bridging

### ISSUE THREAD

**Issue by ipspace** [ipspace/netlab#1895]
Sample topology:

```
---
message: |
 Tests a basic L2 link between 2 hosts

groups:
 _auto_create: True
 switches:
  members: [ dut ]
 hosts:
  members: [ h1, h2 ]
  device: linux
  provider: clab

links:
- dut:
    ipv4: False
  h1:
    ipv4: 10.0.0.1/24
- dut:
    ipv4: False
  h2:
    ipv4: 10.0.0.2/24

validate:
  ping:
    description: IPv4 ping H1 => H2
    wait_msg: Waiting for STP to enable the ports
    wait: 45
    nodes: [ h1 ]
    plugin: ping('h2')
```

This currently fails for both EOS and FRR...

_Originally posted by @jbemmel in https://github.com/ipspace/netlab/pull/1886#discussion_r1943846620_
