### ISSUE TITLE
lag module should model peerlink as regular VLAN

### ISSUE THREAD

**Issue by jbemmel** [ipspace/netlab#1909]
Most MLAG platforms support things like OSPF on the peerlink between the MLAG router pair; the ```lag``` module should create a subinterface as appropriate, and allow these modules to do their job

For example, this should work as expected:
```
module: [ ospf, lag, vlan ]

links:
- lag:
    members: [ s1, s2 ]
    mlag.peergroup: True
```

Likewise:
```
module: [ ospf, lag, vlan ]

links:
- lag:
    members: [ s1, s2 ]
    mlag.peergroup: True
  ospf: False
```
