### ISSUE TITLE
[BUG] VXLAN module includes IP of alternate local VTEP in floodlist

### ISSUE THREAD

**Issue by jbemmel** [ipspace/netlab#1916]
Context: https://github.com/ipspace/netlab/pull/1915

Lab: ```netlab up integration/mlag.vtep/01-vxlan-bridging.yml -p clab -d dellos10 -v```

This fails because Dell OS10 complains about the local VTEP IP being provisioned as a remote VTEP

in host_vars/dut_a/b:
```
vxlan:
  domain: global
  flooding: static
  vlans:
  - red
  - blue
  vtep: 10.101.101.1                <==
  vtep_interface: loopback1
  vtep_list:
  - 10.0.0.8
  - 10.101.101.1                       <== same IP
```
