### ISSUE TITLE
[BUG] Gateway protocol 'anycastanycast'

### ISSUE THREAD

**Issue by jbemmel** [ipspace/netlab#1927]
Lab:
```yaml
---

module: [ vlan, gateway ]

vlans:
  v1:
    gateway.id: 1
    links: [ s1-s2 ]

groups:
  _auto_create: True
  switches:
    members: [ s1,s2 ]
    gateway.protocol: anycast
```

Results in ```s1/topology.yml```
```yaml
- bridge_group: 1
  gateway:
    anycast:
      mac: 0200.cafe.00ff
      unicast: true
    id: 1
    ipv4: 172.16.0.1/24
    protocol: anycastanycast  <!-- ***
  ifindex: 40000
  ifname: vlan1000
  ipv4: 172.16.0.2/24
  mtu: 1500
  name: VLAN v1 (1000) -> [s2]
```
