### ISSUE TITLE
[BUG] Gateway protocol configured at group level ignored

### ISSUE THREAD

**Issue by jbemmel** [ipspace/netlab#1981]
Topology:
```
---
groups:
 _auto_create: True

 switches:
  members: [ s1, s2 ]
  module: [ gateway ]
  gateway.protocol: vrrp

links:
- s1:
  s2:
  prefix: 10.0.0.0/29
  gateway: True
```

The generated topology has an ```anycast``` gateway:
```
gateway:
  anycast:
    mac: 0200.cafe.00ff
    unicast: true
```
