### ISSUE TITLE
[BUG] Prefix on routed VLAN ignored

### ISSUE THREAD

**Issue by jbemmel** [ipspace/netlab#2020]
Topology:
```YAML
---

defaults.device: frr
provider: clab

module: [ vlan ]

groups:
  _auto_create: True

  nodes:
   members: [ n1, n2 ]

vlans:
  v1:
    mode: route
    prefix:
      ipv4: False
      ipv6: True

links:
- n1:
  n2:
  vlan.trunk: [ v1 ]
```

Result:
```
...
- bridge_group: 1
  ifindex: 2
  ifname: eth1.700
  ipv4: 10.1.0.1/30
  name: n1 -> n2
  neighbors:
  - ifname: eth1.700
    ipv4: 10.1.0.2/30
    node: n2
  parent_ifindex: 1
  parent_ifname: eth1
  type: vlan_member
  virtual_interface: true
  vlan:
    access_id: 700
    mode: route
    name: v1
    routed_link: true
```

I was expecting a link with IPv6 LLA and no ipv4 (as you get when removing ```mode: route```)

**Comment by jbemmel** [comment]
It happens because of this: https://github.com/ipspace/netlab/blob/dc483dfdcf22cce3cf559d28309b328f46cd2b02/netsim/modules/vlan.yml#L30

The same list is used in 3 places, 2 having to do with vlan-to-link copy and 1 vlan-to-svi copy. ```prefix``` shouldn't be copied in the latter case, but in the other cases perhaps it should?

**Comment by jbemmel** [comment]
I do realize that prefixes on routed VLANs make limited sense; my use case is a peering vlan for mlag for which I'm trying to set ```ipv6: True```. There are other ways to achieve this, bypassing VLAN prefix copying behaviors; I just wanted to share the use case for discussion

**Comment by ipspace** [comment]
I think this is a duplicate or at least a close relative of #1814.

Anyway, assigning a static prefix to a routed VLAN shouldn't work because we need a unique subnet per segment. Assigning a different pool (using IPv6 LLA and no IPv4 in your case) should work, and could be even better documented in https://netlab.tools/module/vlan/#vlan-interface-parameters

**Comment by jbemmel** [comment]
> Anyway, assigning a static prefix to a routed VLAN shouldn't work because we need a unique subnet per segment.

Strictly speaking there are a couple of exceptions to this:
1. Unnumbered / LLA flags
2. Link-local address ranges ( 169.254.0.0/16 and fe80::/64 )

(1) can be addressed through pools, but (2) cannot [ for designs in which the same link-local prefix gets assigned to different devices ]

I could submit a PR to throw an error when the user tries to assign a prefix to a routed VLAN; would you be ok with the above exceptions, or would you prefer an error for any value of ```prefix```?

**Comment by ipspace** [comment]
> 2. Link-local address ranges ( 169.254.0.0/16 and fe80::/64 )

You can set the interface addresses to fixed values.

```
links:
- vlan.trunk: [ red, blue ]
  r1:
    vlan.trunk.red:
      ipv4: 169.254.0.1/26
  r2:
    vlan.trunk.red:
      ipv4: 169.254.0.2/26
```

I know it's not elegant, but it's such a niche scenario that I don't think it warrants additional code.

> I could submit a PR to throw an error when the user tries to assign a prefix to a routed VLAN; would you be ok with the above exceptions, or would you prefer an error for any value of `prefix`?

We should report an error if a routed VLAN has a **prefix**.
