### ISSUE TITLE
intf.vlan.native not always set

### ISSUE THREAD

**Issue by jbemmel** [ipspace/netlab#2032]
https://github.com/ipspace/netlab/blob/5077bccee36a00aba30f4b61be10a838d70d8937/netsim/modules/vlan.py#L307

should be
```
node_native = get_effective_module_attribute('vlan.native',intf=intf,link=link)
if node_native:                                         # Does this node use native VLAN?
  if not node_trunk:                                    # ... no trunk data for this node, cannot use native VLAN
    log.error(
      f'Node {intf.node} is using native VLAN without VLAN trunk\n... {link}',
      log.IncorrectValue,
      'vlan')
  elif node_native not in node_trunk:                   # ... native VLAN not in trunk, that's not valid
```

**Comment by ipspace** [comment]
Test case?

**Comment by jbemmel** [comment]
```
---
module: [ vlan ]

groups:
  _auto_create: True
  nodes:
    members: [ n1, n2 ]

vlans:
  v1:

links:
- n1:
    vlan.trunk:
      v1:
        vlan.mode: route
  n2:
  vlan.trunk: [ v1 ]
  vlan.native: v1
```
File "/home/user/netlab/netsim/modules/vlan.py", line 1353, in link_pre_transform
    if not validate_link_vlan_attributes(link,v_attr,topology):
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/user/netlab/netsim/modules/vlan.py", line 307, in validate_link_vlan_attributes
    elif not intf.vlan.native in node_trunk:              # ... native VLAN not in trunk, that's not valid
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "box/box.py", line 406, in box.box.Box.__contains__
  File "box/box.py", line 386, in box.box.Box.__hash__
box.exceptions.BoxTypeError: unhashable type: "Box"
```
