### ISSUE TITLE
Cleanup empty VLAN prefix

### ISSUE THREAD

**Issue by jbemmel** [ipspace/netlab#2039]
When creating a pure L2 bridged VLAN

```YAML
---

module: [ vlan ]

groups:
  _auto_create: True
  nodes:
    members: [ n1, n2 ]

vlans:
  v1:
    mode: bridge
    prefix: False
    links: [ n1-n2 ]
```

the vlan has a ```prefix``` attribute with only ```allocation``` defined:
```
vlans:
  v1:
    bridge_group: 1
    id: 700
    mode: bridge
    prefix:
      allocation: id_based
```

Suggestion: vlan.py line 132:
```Python
    vdata.prefix = addressing.rebuild_prefix(pfx_list)
    if not vdata.prefix:
      vdata.pop('prefix',None)
    elif not 'allocation' in vdata.prefix:
      vdata.prefix.allocation = 'id_based'
```
