### ISSUE TITLE
[BUG] Prefer "internal" over "external" interface for control-plane interface

### ISSUE THREAD

**Issue by ipspace** [ipspace/netlab#2044]
Bird is failing the IBGP local-as test because the IBGP neighbor tries to establish an IBGP session with its external IP subnet which is not advertised in OSPF.

### Incorrect data structure

BGP neighbors on X3:

```
neighbors:
- _source_intf:
    ifindex: 0
    ifname: lo
    ipv4: 10.0.0.4/32
    neighbors: []
    type: loopback
    virtual_interface: true
  activate:
    ipv4: true
  as: 65000
  ipv4: 172.16.0.1
  name: dut
  type: ibgp
```

The neighbor (dut) IPv4 address should be an address of an interface without the 'external' role.
