### ISSUE TITLE
[BUG] VRF loopback address should not be defined in the global VRF definition

### ISSUE THREAD

**Issue by ipspace** [ipspace/netlab#2068]
It's perfectly OK to set the "I want to have a loopback in this VRF" flag in the global VRF definition (so it's applied to all nodes using the VRF) but it makes no sense to specify the IP address in the global VRF definition as that would be applied to all nodes using that VRF.

### To Reproduce

This is the config snippet that should trigger an error.

```
vrfs:
  red:
    loopback: 10.0.0.42/32
    links: [ dut-r1, dut-r2 ]
  blue:
    loopback: 10.0.0.43/32
    links: [ dut-r3, dut-r4 ]
```
