### ISSUE TITLE
[BUG] Prefix allocation ignored on VLAN in trunk

### ISSUE THREAD

**Issue by jbemmel** [ipspace/netlab#2090]
Lab:
```
---
module: [vlan]

groups:
  _auto_create: True
  nodes:
    members: [ n1, n2 ]

nodes:
  n1:
    id: 3

vlans:
  v1:
    pool: p2p
    prefix:
      allocation: p2p

links:
- n1:
  n2:
  vlan.trunk: [ v1 ]
```

Result:
```
[ERRORS]  Errors found in prefix_allocation.yml
[VALUE]   links: Address 10.1.0.3/30 on node n1/links[1].v1 is a subnet broadcast address
```

(because the default ```id_based``` allocation gets applied)

Bug is here: https://github.com/ipspace/netlab/blob/2e824422fbd26fb31496f09f7f5845972c55b78d/netsim/modules/vlan.py#L132

```links.assign_link_prefix``` copies the 'allocation' attribute to ```vdata.prefix```, but it gets overwritten
