### ISSUE TITLE
[BUG] FRR presents wrong anycast gateway MAC address in EVPN scenario

### ISSUE THREAD

**Issue by jbemmel** [ipspace/netlab#2099]
Lab: ``` netlab up integration/evpn/03-vxlan-symmetric-irb.yml -d srlinux -p clab -v```
Latest dev branch

h1 (connected to s1 SR Linux)
```
h1:/# ping 172.16.0.254
PING 172.16.0.254 (172.16.0.254): 56 data bytes
64 bytes from 172.16.0.254: seq=0 ttl=64 time=1.746 ms
64 bytes from 172.16.0.254: seq=1 ttl=64 time=0.730 ms
^C
--- 172.16.0.254 ping statistics ---
2 packets transmitted, 2 packets received, 0% packet loss
round-trip min/avg/max = 0.730/1.238/1.746 ms
h1:/# arp
? (172.16.0.254) at 02:00:ca:fe:00:ff [ether]  on eth1
? (172.16.0.254) at 02:00:ca:fe:00:ff [ether]  on eth1
```

h2 (connected to s2 FRR):
```
h2:/# ping 172.16.0.254
PING 172.16.0.254 (172.16.0.254): 56 data bytes
64 bytes from 172.16.0.254: seq=0 ttl=64 time=0.303 ms
64 bytes from 172.16.0.254: seq=1 ttl=64 time=0.080 ms
^C
--- 172.16.0.254 ping statistics ---
2 packets transmitted, 2 packets received, 0% packet loss
round-trip min/avg/max = 0.080/0.191/0.303 ms
h2:/# arp
? (172.16.0.254) at 52:dc:ca:fd:06:00 [ether]  on eth1
? (172.16.0.254) at 52:dc:ca:fd:06:00 [ether]  on eth1

```

the MAC address belongs to the 'vlan1000' interface with IP 172.16.0.6/24

**Comment by jbemmel** [comment]
To fix:
```
 sysctl -w net.ipv4.conf.varp-40000.arp_accept=1
```

Not sure how FRR manages to pass the gateway test, which checks for the MAC

**Comment by ipspace** [comment]
Linux is bizarre :(

* Pinging a remote host (going _through_ anycast GW) creates ARP entry with the anycast MAC address
* Pinging the anycast IP address creates ARP entry with VLAN MAC address

Go figure 🤦‍♂️

**Comment by ipspace** [comment]
> sysctl -w net.ipv4.conf.varp-40000.arp_accept=1

No change in behavior. Pinging the default gateway still generates an ARP entry with the VLAN MAC address.

**Comment by jbemmel** [comment]
> Pinging across the anycast GW results in correct ARP entry, pinging the anycast GW itself always results in the VLAN MAC address.

> Looks like we're still missing something - if I had to guess, I'd say it's a FRR config issue

> It's definitely a Linux interface config issue, not sure FRR has anything to do with that (it's not involved in the anycast case anyway).

Agreed, Linux config issue on the frr device is what I meant to say

**Comment by jbemmel** [comment]
The issue is with the ARP request the ```dut``` node sends out:
```
09:45:39.271018 52:dc:ca:fd:02:00 > ff:ff:ff:ff:ff:ff, ethertype ARP (0x0806), length 42: Ethernet (len 6), IPv4 (len 4), Request who-has 172.16.33.4 tell 172.16.33.42, length 28
```

It sends the ARP with the source MAC of the VLAN interface, but the target IP of the anycast gateway

Changing:
```
sysctl -w net.ipv4.conf.{{ intf.ifname }}.arp_announce=2 # was 1
```
fixes it (probably also needed for VRRP)

Pinging the gateway causes the node to send out such an inconsistent ARP request

Another way might be to disable sending ARPs on the underlying interface, and let the anycast interface send those out instead.

**Comment by ipspace** [comment]
Here's the test we can use:

```
module: [ gateway ]

groups:
  hosts:
    device: linux
    provider: clab
    members: [ h1, h2, h3 ]

gateway.protocol: anycast
gateway.id: 1
gateway.anycast.mac: 0200.cafe.c001

nodes: [ dut, h1, h2, h3 ]

links:
- interfaces: [ h1, h2, dut ]
  gateway: True
- dut-h3

validate:
  ping_h1_h3:
    description: IPv4 ping H1 -> H3
    nodes: [ h1 ]
    plugin: ping('h3',af='ipv4')
  h1_arp:
    description: Check the ARP entry for the anycast gateway (routing)
    nodes: [ h1 ]
    devices: [ linux ]
    exec: arp -n {{ interfaces[0].gateway.ipv4|ipaddr('address') }}
    valid: |
      '02:00:ca:fe:c0:01' in stdout
  ping_h2_gw:
    description: IPv4 ping H1 -> H3
    nodes: [ h2 ]
    plugin: ping(nodes.h2.interfaces[0].gateway.ipv4)
  h2_arp:
    description: Check the ARP entry for the anycast gateway (ping)
    nodes: [ h2 ]
    devices: [ linux ]
    exec: arp -n {{ interfaces[0].gateway.ipv4|ipaddr('address') }}
    valid: |
      '02:00:ca:fe:c0:01' in stdout
```
