### ISSUE TITLE
[BUG] unnumbered interfaces in VRF fail to check for presence of loopback

### ISSUE THREAD

**Issue by jbemmel** [ipspace/netlab#2119]
Edited version of ```ospf/ospfv2/05-unnumbered```:
```YAML
---
message: |
  This lab tests OSPF running over unnumbered IPv4 interfaces.

module: [ ospf ]

groups:
  probes:
    device: frr
    provider: clab
    members: [ x1 ]
    module: [ ospf, vrf ]

nodes:
  dut:
  x1:

vrfs:
  X:

links:
- dut:
  x1:
    vrf: X
  prefix.ipv4: True
  mtu: 1500
```

The OSPF neighborship fails to establish, because the loopback interface supporting the unnumbered interface on x1 isn't present inside the vrf X
