### ISSUE TITLE
[BUG] Unable to declare routing.community in groups

### ISSUE THREAD

**Issue by jbemmel** [ipspace/netlab#2154]
Lab:
```
---
groups:
  test:
    members: [ x ]
    module: [ routing ]
    routing:
     community:
      c1: '65233:101'
     policy:
      set_pref:
      - match.community: c1
        set.locpref: 120

nodes:
  x:
   routing:
     community:
      c2: '65233:102'
     policy:
      set_pref:
      - match.community: c2
        set.locpref: 130
```

Result:
```
user@vm:~/$ netlab create /tmp/community_in_group.yml
[ERRORS]  Errors found in community_in_group.yml
[TYPE]    routing: attribute 'topology.groups.test.routing.community.c1[1]' must be a dictionary, found str
[HINT]    use 'netlab show attributes --module routing' to display valid attributes
[FATAL]   Cannot proceed beyond this point due to errors, exiting
```

Commenting out the 'groups' part, things work fine at the node level
