### ISSUE TITLE
[BUG] BGP sessions over unnumbered IPv4 interfaces use IPv6 but top level 'af' only lists ipv4

### ISSUE THREAD

**Issue by jbemmel** [ipspace/netlab#2193]
Lab: ```netlab create integration/bgp/06-unnumbered.yml -d bird -p clab```

Result:
```
# Ansible inventory created from ['/home/jeroen/Projects/netlab/tests/integration/bgp/06-unnumbered.yml', '/home/jeroen/.netlab.yml', 'package:topology-defaults.yml']
#

_daemon: true
_daemon_config:
  bgp: /etc/bird/bgp.mod.conf
  bird: /etc/bird/bird.conf
_daemon_parent: linux
af:
  ipv4: true   <!-- only ipv4 here
bgp:

... [ cut ] ...

hostname: clab-bgp-dut
interfaces:
- _parent_intf: lo
  _parent_ipv4: 10.0.0.1/32
  _unnumbered_peer: 10.0.0.2/32
  ifindex: 1
  ifname: eth1
  ipv4: true
  ipv6: true
```

Consequently, bird doesn't enable router advertisements because that depends on ```af.ipv6``` being true

Likely happens because https://github.com/ipspace/netlab/blob/170ac871b8e6f87dd490a31b21727fee5fdbee05/netsim/modules/bgp.py#L301 enables ipv6 without updating the global ```af```

It's kind of moot for now if we remove IPv6 LLA support - but fyi
