### ISSUE TITLE
[BUG] FRR templates stumble over inconsistent IS-IS interface settings

### ISSUE THREAD

**Issue by jbemmel** [ipspace/netlab#2203]
Lab (may not make complete sense as such, just to highlight and reproduce the issue)
```
---
message: Issue with interfaces having no overlapping address families enabled

addressing:
  p2p:
    ipv4: False       # ipv6-only
    ipv6: 2001:1::/48

  loopback:
    ipv4: False       # No ipv4 loopbacks
    ipv6: 2001::/48

isis.af:
  ipv4: True          # IPv4-only

groups:
  _auto_create: True
  hosts:
    members: [ h1, h2 ]
    device: linux
    provider: clab
  p:
    members: [ dut, p2 ]
    module: [ isis ]
    device: frr
    provider: clab

links:
- h1:
  dut:
    isis.passive: True
- dut-p2
- p2:
    isis.passive: True
  h2:
```

Result for p2:
```
% Configuration failed.
  
    Error type: validation
    Error description: YANG error(s):
     Path: Data location "/frr-interface:lib/interface[name='eth1']/frr-isisd:isis".
     Error: Mandatory node "area-tag" instance does not exist.
  
    The following commands were dynamically grouped into the same transaction and rejected:
    -  isis network point-to-point
```

The issue is that IS-IS only has AF ipv4 enabled, while the loopback and dut-p2 interface only have ipv6:
```YAML
{% for l in interfaces|default([]) if 'isis' in l %}
interface {{ l.ifname }}
! {{ l.name|default("") }}
{%   if 'ipv4' in l and 'ipv4' in isis.af %}
 ip router isis {{ isis.instance }}
{%   endif %}
{%   if 'ipv6' in l and 'ipv6' in isis.af  %}
 ipv6 router isis {{ isis.instance }}
{%   endif %}
{%   if l.isis.network_type is defined %}
 isis network {{ l.isis.network_type }}
{%   endif %}
{%   if l.isis.cost is defined or l.isis.metric is defined %}
 isis metric {{ l.isis.metric|default(l.isis.cost) }}
{%   endif %}
{%   if l.isis.passive %}
 isis passive
{%   endif %}
!
{% endfor %}
```
The above loop configures isis parameters without including either ```ip``` or ```ipv6``` router isis X

Similar issue may exist with other IGPs; if there is no overlap between the address families enabled on an interface and those enabled for the IGP, the IGP config should be removed from the interface
