### ISSUE TITLE
[BUG] Unable to activate VPNv4 over IPv6

### ISSUE THREAD

**Issue by jbemmel** [ipspace/netlab#2209]
Based on https://onvox.net/2024/12/16/srv6-frr/#frr-verification:

```
---
addressing:
  p2p:
    ipv4: 10.1.0.0/24
    ipv6: 2001:1::/48

  loopback:
    ipv4: 10.0.0.0/24
    ipv6: 2001::/48

mpls.vpn: True        # Enable BGP VPN family on VRFs for ibgp neighbors
mpls.ldp: False

bgp.as: 65000

bgp.advertise_loopback: False # Using IS-IS for this

vrfs:
  customer:

groups:
  _auto_create: True
  hosts:
    members: [ h1, h2 ]
    device: linux
    provider: clab
  pe:
    members: [ dut, pe2 ]
    module: [ isis, bgp, vrf, mpls ]
    bgp.import: [ connected ]
    bgp.sessions:
      ipv4: []           # Adding 'ibgp' here fixes things
      ipv6: [ ibgp ]
    bgp.activate: # Activate only BGP VPNv4 over IPv6
      ipv4: []
      ipv6: []
  x_switches:
    members: [ pe2 ]
    device: frr
    provider: clab

links:
- h1:
  dut:
    isis.passive: True
  vrf: customer
- dut-pe2
- pe2:
    isis.passive: True
  h2:
  vrf: customer
```

The intent is to activate VPNv4 over IPv6, but this does not happen:
```
neighbors:
  - _source_intf:
      ifindex: 0
      ifname: lo
      ipv4: 10.0.0.3/32
      ipv6: 2001:0:0:3::1/64
      neighbors: []
      type: loopback
      virtual_interface: true
    activate:
      ipv6: false
    as: 65000
    ipv6: 2001:0:0:4::1
    name: pe2
    type: ibgp
  next_hop_self: true
  router_id: 10.0.0.3
  sessions:
    ipv4: []
    ipv6:
    - ibgp
```
Missing: ```vpnv4: 2001:0:0:3::1/64```. 

This happens because Netlab supports only ipv4: https://github.com/ipspace/netlab/blob/9a9e4b54dd2bce753524754f2c042c496a1d7bde/netsim/modules/mpls.py#L180

(I'm aware that you're not a big fan of srv6, and it may seem like I'm working on all the things that annoy you the most - but I can assure you that's not the case...)
