### ISSUE TITLE
[BUG] mpls.vpn BGP session types not honored

### ISSUE THREAD

**Issue by jbemmel** [ipspace/netlab#2216]
Lab:
```
---
mpls.vpn:
  ipv4: [ ibgp ] # Default setting
mpls.ldp: False

groups:
  _auto_create: True
  nodes:
    members: [ n1, n2 ]
    device: frr
    module: [ bgp, mpls, vrf ]
    vrfs:
      v1:
        loopback: True

vrfs:
  v1:

nodes:
  n1:
    bgp.as: 65001
  n2:
    bgp.as: 65002

links:
- n1-n2
```

By default, ```mpls.bgp: True``` enables BGP VPNv4/v6 on all iBGP sessions, per the documentation.
However, this is not what happens: An EBGP neighbor also gets ```vpnv4: xxx``` and templates like FRR https://github.com/ipspace/netlab/blob/eae496df05f025ad733e9e1650321b66109e35f1/netsim/ansible/templates/mpls/frr.mplsvpn.j2#L7 happily configure it - even though 'ebgp' is not included in the list

```
router bgp 65001
 bgp router-id 10.0.0.1
 no bgp default ipv4-unicast
 bgp bestpath as-path multipath-relax
 neighbor 10.1.0.2 remote-as 65002
 neighbor 10.1.0.2 description n2
 !
 address-family ipv4 unicast
  network 10.0.0.1/32
  neighbor 10.1.0.2 activate
  no neighbor 10.1.0.2 send-community extended
 exit-address-family
 !
 address-family ipv4 vpn
  neighbor 10.1.0.2 activate
 exit-address-family
exit
```

In addition, note how the ```bgp.community``` attributes for ebgp neighbors are not applied to the VPN AF (separate issue, also applies to ibgp VPN neighbors)
