### ISSUE TITLE
[BUG] Activating IPv4 over IPv6-only

### ISSUE THREAD

**Issue by jbemmel** [ipspace/netlab#2218]
Lab:
```
---
bgp.sessions:
  ipv4: []
  ipv6: [ ebgp ]
bgp.activate: # Only BGP v4 AF over IPv6
  ipv4: [ ebgp ]
  ipv6: []

groups:
  _auto_create: True
  nodes:
    members: [ r1, r2 ]
    module: [ bgp ]

nodes:
  r1:
    bgp.as: 65001
  r2:
    bgp.as: 65002

links:
- r1:
  r2:
  prefix:
    ipv4: False
    ipv6: 2001::/64  # IPv6 only
```

This results in BGP neighbors with no af families activated, due to ```bgp.activate_bgp_default_af```:
```Python
"""
activate_bgp_default_af -- activate default AF on IPv4 and/or IPv6 transport sessions

Based on transport session(s) with a BGP neighbor, local BGP AF, and BGP AF configuration
parameters, set neighbor.activate.AF flags
"""
def activate_bgp_default_af(node: Box, activate: Box, topology: Box) -> None:
  for ngb in node.bgp.neighbors:
    for af in ('ipv4','ipv6'):
      if af in ngb:
        ngb.activate[af] = node.bgp.get(af) and af in activate and ngb.type in activate[af]
```

i.e. Netlab assumes the transport protocol must be enabled to activate the corresponding address family - a.k.a. the ["sane" default](https://blog.ipspace.net/2022/01/bgp-af-nerd-knobs/)

From the bgp docs: 
"* You might need **‌bgp.sessions** parameter in scenarios where you're transporting global IPv4 or IPv6 over an overlay network, for example 6PE or IPv4-over-SRv6 (requires custom configuration template).
"
IPv4 over IPv6 is needed for SRv6, do you prefer to fix it there rather than modify the sane default?
```
def activate_bgp_default_af(node: Box, activate: Box, topology: Box) -> None:
  for af in ('ipv4','ipv6'):
    if af in activate and node.af.get(af):
      for ngb in node.bgp.neighbors:
        if ngb.type in activate[af]:
          if af in ngb:
            ngb.activate[af] = True
          elif af=='ipv4' and 'ipv6' in ngb:
            ngb.activate.ipv4 = True
            ngb.ipv4_rfc8950 = True
```
