### ISSUE TITLE
[BUG] Switching default provider breaks the node augmentation process

### ISSUE THREAD

**Issue by ipspace** [ipspace/netlab#2219]
The following topology results in an error because **clab.kind** is not set correctly:

```
nodes:
  rtr:
    provider: clab
    device: frr
```

Setting the lab provider to **clab** obviously works.
