### ISSUE TITLE
[BUG] must_be_ipv4/subnet_prefix should check for reserved IP addresses

### ISSUE THREAD

**Issue by jbemmel** [ipspace/netlab#2229]
Lab:
```
---
addressing:
  loopback:
    ipv4: 0.0.0.0/24

groups:
  _auto_create: True
  routers:
    members: [ n1, n2 ]
    device: frr
    provider: clab

links:
- n1-n2
```

A corner case for sure, but it highlights several issues: ```netlab create lab.yml```
* Invalid range accepted for loopback.ipv4
* 'kind' is set to 'frr' in the generated clab.yml file; the clab provider setting of 'linux' doesn't get applied
* the invalid loopback 0.0.0.1/32 generates an error, but the Ansible script does not report it. The interface IP address does not get applied
