### ISSUE TITLE
[BUG] Removed interface attribute is overwritten with link attribute

### ISSUE THREAD

**Issue by ipspace** [ipspace/netlab#2232]
An interface attribute that is removed because it's set to **False** is later overwritten with a link attribute.

Topology:

```
provider: clab
defaults.device: frr

plugin: [ bgp.session ]
module: [ bgp ]

nodes:
  r1:
    bgp.as: 65000
  r2:
    bgp.as: 65001

links:
- r1:
    bgp.gtsm: False
  r2:
    bgp.gtsm: 2
  bgp.gtsm: 3
```

Results:

```
$ netlab inspect --node all bgp.neighbors
┏━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━┓
┃ r1               ┃ r2               ┃
┡━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━┩
│ - activate:      │ - _removed_attr: │
│     ipv4: true   │   - gtsm         │
│   as: 65001      │   activate:      │
│   gtsm: 3        │     ipv4: true   │
│   ifindex: 1     │   as: 65000      │
│   ipv4: 10.1.0.2 │   gtsm: 2        │
│   name: r2       │   ifindex: 1     │
│   type: ebgp     │   ipv4: 10.1.0.1 │
│                  │   name: r1       │
│                  │   type: ebgp     │
└──────────────────┴──────────────────┘
```

Expected results:

* gtsm should not be set on R1
* **_removed_attr** should not be set on R2
