### ISSUE TITLE
[BUG] Deleting extended communities on EOS

### ISSUE THREAD

**Issue by jbemmel** [ipspace/netlab#2242]
Lab:
```
---
message: |
  Use this topology to test 'set.community.delete' route-map option.

plugin: [ bgp.policy ]
module: [ bgp, routing ]

groups:
  probes:
    device: frr
    provider: clab
    members: [ probe, x1 ]

nodes:
  dut:
    bgp.as: 65000
    routing.policy.set_comm:
      set.community:
        extended: 'LB:65000:12500000'
        delete: True
    id: 1
  probe:
    bgp.as: 65100
  x1:
    bgp.as: 65101
    routing.policy.set_comm:
      set.community:
        extended:  'LB:65000:12500000 LB:65000:12500001'
```

After ```netlab up -d eos```:
```
TASK [eos_config: deploying routing from /home/jvanbemmel/netlab/netsim/ansible/templates/routing/eos.j2] *******************************************************************************************************************************************************************************************************************
fatal: [dut]: FAILED! => changed=false
  data: |-
    set extcommunity LB:65000:12500000 delete
    % Invalid input
    dut(config-s-ansible_17-route-map-set_comm-ipv4)#
  msg: |-
    set extcommunity LB:65000:12500000 delete
    % Invalid input
    dut(config-s-ansible_17-route-map-set_comm-ipv4)#
```
