### ISSUE TITLE
Community lists for extended and large communities

### ISSUE THREAD

**Issue by ipspace** [ipspace/netlab#2243]
The **routing.community** object currently supports only standard BGP communities. It would be nice to have community lists that would match extended or large communities.

Unfortunately, that probably means we'll have to restructure the **routing.community** data format to add **type** (or something) top-level attribute that specifies which type of community list we're describing.

**Comment by ipspace** [comment]
@jbemmel @ssasso @DanPartelly @Muddyblack @steffann @ddutt @nmodena -- any preference on how we'd structure the extended/large community lists?

I see three options:

### Per-entry community type

```
routing.community:
  std_1:
  - action: permit
    list: [ 65000:1 ]
  - action: deny
    regexp: _65000:1.._
  ext_1:
  - action: permit
    list: [ rt:65000:1 ]
    type: extended
  - action: deny
    list: [ rt:65000:.* ]
    type: extended
```

In this case, we could potentially split a single community list with different **type** values into multiple device ACLs (potentially confusing). Alternatively, we would report an error if **type** does not match across entries.

### Specify community list type

```
routing.community:
  std_1:          # Simplified standard community list
  - action: permit
    list: [ 65000:1 ]
  ext_1:          # Extended community list
    type: extended
    value:
    - action: permit
      list: [ rt:65000:1 ]
```

Advantage: clean data model

Drawback: more verbose for large/extended community lists

### Guesswork

If the entries are "a:b", then it's a standard community list, if they're "a:b:c" then it's a large community list, if they're "rt:..." or "soo:..." then it's an extended community list.

Drawback: doesn't work well when the user starts using regular expressons :(
