### ISSUE TITLE
Ubuntu initial script references 'bond' interfaces before they are created

### ISSUE THREAD

**Issue by jbemmel** [ipspace/netlab#2245]
https://github.com/ipspace/netlab/blob/f57b25bb693df1eeb57fb9f2c8bd034e5155cfcc/netsim/ansible/templates/initial/linux/ubuntu.j2#L93

In case of a 'bond' interface, the device doesn't exist until the Netplan config gets applied. The sysctl settings should be moved after that

Lab:
```YAML
---

groups:
  _auto_create: True
  nodes:
    members: [ n1, n2 ]
    device: linux
    provider: libvirt
    module: [ lag ]

links:
- lag:
    members: [ n1-n2 ]
```
