### ISSUE TITLE
[BUG] lag.ifindex ignored when descending order is used

### ISSUE THREAD

**Issue by jbemmel** [ipspace/netlab#2246]
Lab:
```
---
groups:
  _auto_create: True
  nodes:
    members: [ n1, n2 ]
    module: [ lag ]

links:
- lag:
    ifindex: 2
    members:
    - n1:
      n2:
- lag:
    ifindex: 1
    members:
    - n1:
      n2:
```

An FRR device gets ```bond2``` and ```bond3```, not ```bond1``` as specified
