### ISSUE TITLE
[BUG] Ansible crashes with 'loopback' attributes on a Linux host

### ISSUE THREAD

**Issue by sdargoeuves** [ipspace/netlab#2261]
### Describe the bug

Not really a bug, as it's described in the [doc](https://netlab.tools/labs/linux/#loopback-interface), so it's expected that it doesn't work.

> netlab does not configure a global loopback IP address on Linux nodes with role set to host (the default netlab setting).
A loopback IP address is [allocated](https://netlab.tools/example/addressing-tutorial/#loopback-addresses) to a Linux node if you set role to any other value, and the initial configuration script configures an additional IP address on the lo interface, for example:

But maybe it could fail nicely by informing during the creation phase.

### To Reproduce

I was trying to create a loopback with an IPv4 to a linux host, which was working prior to `2.0.0` (I've just tested on `1.9.5`)

### Expected behavior

It would be nice to fail faster, during the `netlab create` phase

### Lab topology

```
  h1:
    device: linux
    provider: clab
    role: bridge
    loopback:
      ipv4: 172.16.0.50/32
```

### Output

```
TASK [Create container setup script from /home/sa/code/quick-netlab-lab/netlab/netsim/ansible/templates/initial/linux-clab.j2] *********************************************
An exception occurred during task execution. To see the full traceback, use -vvv. The error was: ansible.errors.AnsibleUndefinedVariable: 'dict object' has no attribute 'ifname'
fatal: [h1 -> localhost]: FAILED! => changed=false 
  msg: 'AnsibleUndefinedVariable: ''dict object'' has no attribute ''ifname'''
changed: [h2 -> localhost]
```

### Version

`2.0.0`

**Comment by jbemmel** [comment]
```
# Ansible inventory created from ['/tmp/lb.yml', '/home/jeroen/.netlab.yml', 'package:topology-defaults.yml']
#

af: {}
box: python:3.13-alpine
clab:
  binds:
  - clab_files/h1/hosts:/etc/hosts
  config_templates:
  - hosts:/etc/hosts
  kind: linux
hostname: clab-tmp-h1
interfaces: []
loopback:
  ipv4: 172.16.0.50/32
mgmt:
  ifname: eth0
  ipv4: 192.168.121.101
  mac: 08:4f:a9:01:00:00
module:
- vlan
mtu: 1500
role: bridge
vlan:
  mode: bridge
vlans:
  br_default:
    id: 1
    mode: bridge
    prefix:
      allocation: id_based
      ipv4: 172.16.0.0/24
```

There are additional issues, for example ```af.ipv4``` is not set

Netlab doesn't allocate a loopback, but if the user defines one it should be provisioned
