### ISSUE TITLE
[DOC] Need an example for static addressing on VLANs and IRB interfaces

### ISSUE THREAD

**Issue by penguin02007** [ipspace/netlab#2269]
Hi Team,

I am having issue creating SVI on the correct irb with JunOS, I read through documentation and issues, read again on vlan module and [this](https://netlab.tools/module/vlan/#vlan-interface-parameters) blog post that vlan config must be configured on vlans dictionary model.

It looks like `ipv4` should be one level down in the vlan.trunk dictionary? I can't find an example yaml on how to to create a irb with static addressing, any documentation would be helpful, thanks!

Diagram:

![Image](https://github.com/user-attachments/assets/62a147d0-b65e-4249-b029-cf78a3f25294)

Given the following yaml:

<details>
  <summary>topology.yml</summary>

```
---
provider: clab
defaults.device: vmx

nodes:
  r1:
    id: 1
    mgmt.ipv4: 10.10.1.101
    mgmt.ifname: fxp0
  r2:
    id: 2
    mgmt.ipv4: 10.10.1.102
    mgmt.ifname: fxp0
  r3:
    module: [ vlan ]
    id: 3
    mgmt.ipv4: 10.10.1.103
    mgmt.ifname: fxp0
    vlans:
      vlan103:
        ipv4: 192.168.2.0/31
  r4:
    id: 4
    mgmt.ipv4: 10.10.1.104
    mgmt.ifname: fxp0
  r5:
    id: 5
    mgmt.ipv4: 10.10.1.105
    mgmt.ifname: fxp0
  r6:
    id: 6
    mgmt.ipv4: 10.10.1.106
    mgmt.ifname: fxp0
  r7:
    id: 7
    mgmt.ipv4: 10.10.1.107
    mgmt.ifname: fxp0
  r8:
    id: 8
    mgmt.ipv4: 10.10.1.108
    mgmt.ifname: fxp0
  p2-1:
    module: [ vlan ]
    id: 9
    mgmt.ipv4: 10.10.1.121
    mgmt.ifname: fxp0
    vlans:
      vlan103:
        ipv4: 192.168.2.1/31
  p3-1:
    module: [ vlan ]
    id: 10
    mgmt.ipv4: 10.10.1.122
    mgmt.ifname: fxp0

vlans:
  vlan103:
    id: 103
    mode: irb
    ipv4: 192.168.2.0/31
    links:
    - r3:
        ifindex: 2
        name: r3->p2-1
        vlan.trunk: [ vlan103 ]
        type: p2p
        pool: p2_ptp
      p2-1:
        ifindex: 1
        name: p2-1->r3
        vlan.trunk: [ vlan103 ]
        type: p2p
        pool: p2_ptp
  vlan104:
    id: 104
    mode: irb
    ipv4: 192.168.3.0/31
    links:
    - r3:
        ifindex: 2
        name: r3->p3-1
        vlan.trunk: [ vlan104 ]
        type: p2p
        pool: p2_ptp
      p3-1:
        ifindex: 1
        name: p3-1->r3
        vlan.trunk: [ vlan104 ]
        type: p2p
        pool: p2_ptp

links:
  - r1:
      ifindex: 0
      name: r1->r2 (ae0)
    r2:
      ifindex: 0
      name: r2->r1 (ae0)
    pool: l2only
  - r1:
      ifindex: 1
      name: r1->r2 (ae0)
    r2:
      ifindex: 1
      name: r1->r2 (ae0)
    pool: l2only
  - r5:
      ifindex: 0
      name: r5->r6
    r6:
      ifindex: 0
      name: r6->r5
  - r5:
      ifindex: 1
      name: r5->r6
    r6:
      ifindex: 1
      name: r6->r5
  - r2:
      ifindex: 4
      name: r2->r3
      ipv4: 172.20.0.18/31
      type: p2p
    r3:
      ifindex: 1
      name: r3->r2
      ipv4: 172.20.0.19/31
      type: p2p
  - r1:
      ifindex: 3
      name: r1->r4
      ipv4: 172.20.0.25/31
      type: p2p
    r4:
      ifindex: 2
      name: r4->r1
      ipv4: 172.20.0.24/31
      type: p2p
  - r2:
      ifindex: 3
      name: r2->r7
      ipv4: 172.20.0.16/31
      type: p2p
    r7:
      ifindex: 2
      name: r7->r2
      ipv4: 172.20.0.17/31
      type: p2p
  - r3:
      ifindex: 4
      name: r3->r4
      ipv4: 172.20.0.21/31
      type: p2p
    r4:
      ifindex: 1
      name: r4->r3
      ipv4: 172.20.0.20/31
      type: p2p
  - r3:
      ifindex: 5
      name: r3->r6
      ipv4: 172.20.0.23/31
      type: p2p
    r6:
      ifindex: 3
      name: r6->r5
      ipv4: 172.20.0.24/31
      type: p2p
  - r4:
      ifindex: 3
      name: r4->r5
      ipv4: 172.20.0.26/31
      type: p2p
    r5:
      ifindex: 3
      name: r5->r4
      ipv4: 172.20.0.27/31
      type: p2p
  - r5:
      ifindex: 2
      name: r5->r8
      ipv4: 172.20.0.29/31
      type: p2p
    r8:
      ifindex: 3
      name: r6->r5
      ipv4: 172.20.0.28/31
      type: p2p
  - r6:
      ifindex: 2
      name: r6->r7
      ipv4: 172.20.0.30/31
      type: p2p
    r7:
      ifindex: 3
      name: r7->r6
      ipv4: 172.20.0.31/31
      type: p2p
  - r7:
      ifindex: 1
      name: r7->r8
      ipv4: 172.20.0.33/31
      type: p2p
    r8:
      ifindex: 1
      name: r8->r7
      ipv4: 172.20.0.34/31
      type: p2p
  - r8:
      ifindex: 4
      name: r8->r1
      ipv4: 172.20.0.32/31
      type: p2p
    r1:
      ifindex: 4
      name: r1->r8
      ipv4: 172.20.0.31/31
      type: p2p
addressing:
  mgmt:
    ipv4: 10.10.1.0/24
    prefix: 24
    start: 100
  loopback:
    ipv4: 172.16.0.0/24
    prefix: 32
  p2p:
    ipv4: 172.20.0.0/24
    prefix: 31
  p2_p2p:
    ipv4: 192.168.2.0/24
    prefix: 31
  p3_p2p:
    ipv4: 192.168.3.0/24
    prefix: 31

```
</details>

I got this instead:
```
#  netlab report addressing
...
p2-1 (172.16.0.9/32)
  ge-0/0/1.0             192.168.2.1/31                                          p2-1 -> r3
  ge-0/0/1.103                                                                   [SubIf VLAN vlan103] p2-1 -> r3
  irb.103                                                                        VLAN vlan103 (103) -> [r3]

p3-1 (172.16.0.10/32)
  ge-0/0/1.0             192.168.3.3/31                                          p3-1 -> r3
  ge-0/0/1.104                                                                   [SubIf VLAN vlan104] p3-1 -> r3
  irb.104                                                                        VLAN vlan104 (104) -> [r3]
...
```

 I am seeing the static addressing got landed in the default vlan instead of the vlan defined in the irb..hm.

```
# netlab inspect
...
    - ifindex: 2
      name: r3 -> p2-1
      ipv4: 192.168.2.0/31
      type: p2p
      pool: p2_ptp
      linkindex: 9
      ifname: ge-0/0/2.0
      clab:
        name: eth3
      neighbors:
      - ifname: ge-0/0/1
        node: p2-1
        ipv4: 192.168.2.1/31
      subif_index: 1
      junos_interface: ge-0/0/2
      junos_unit: '0'
      _vlan_master: true

...
    - vlan:
        access: vlan103
        access_id: 103
      type: vlan_member
      ifindex: 0
      ifname: ge-0/0/2.103
      parent_ifindex: 2
      parent_ifname: ge-0/0/2
      virtual_interface: true
      junos_interface: ge-0/0/2
      junos_unit: '103'
      neighbors:
      - ifname: ge-0/0/0
        node: p2-1
      name: '[SubIf VLAN vlan103] r3 -> p2-1'

```

**Comment by jbemmel** [comment]
Hi @penguin02007,

Is this what you're looking for?
```
module: [ vlan ]

vlans:
  v1:
    mode: irb

nodes:
  n1:
    vlans:
      v1:
        ipv4: 10.0.0.1/30
  n2:
    vlans:
      v1:
        ipv4: 10.0.0.2/30

links:
- n1:
  n2:
  vlan.access: v1
```

**Comment by ipspace** [comment]
Long story short:

* The VLAN **ipv4** prefixes should be configured in global **vlans** dictionary (for example, **vlans.vlan103.ipv4**, the node IP addresses should be configured in the node **vlans** dictionary (for example, **r3.vlans.vlan103.ipv4**)
* I obviously did a very bad job documenting some things. I apologize for that and will do my best to fix stuff (including some additional examples).
* Thanks a million for the detailed example. It includes a few things I never tried out, but should have.

> It looks like `ipv4` should be one level down in the vlan.trunk dictionary?

In most cases, you shouldn't configure anything on a VLAN trunk. After all, IP addresses on IRB interfaces don't belong to trunks but to boxes. The only exception are routed VLANs (for example, what you would use in a VRF lite scenario).

Now for the details:

```
vlans:
  vlan103:
    id: 103
    mode: irb
  links:
    - r3:
        ifindex: 2
        name: r3->p2-1
        vlan.trunk: [ vlan103 ]
        type: p2p
        pool: p2_ptp
        ipv4: 192.168.2.0/31
```

* I hope the **links** is indented (aligned with **mode**), otherwise we have an interesting parsing problem
* The **links** within a VLAN definition is intended to specify access VLAN links. netlab should reject a VLAN link with a **vlan** attribute.
* Because the link has **vlan.trunk** attribute, the L3 attributes are applied to the native VLAN, and unfortunately Junos is one of those platforms that survives the mix of routed native VLAN and a VLAN trunk (most switches would report an error). However, it might be a good idea to generate a warning saying "hey, do you know what you're doing?"

Any more thoughts @jbemmel @ssasso? After we figure out all the things we have to fix I'll open separate issues.

**Comment by jbemmel** [comment]
> Any more thoughts [@jbemmel](https://github.com/jbemmel)

I am unable to process the YAML, even with indentation corrections and assumptions around ```module``` and ```nodes```:
```
jeroen@j:~/Projects/netlab/tests$ netlab create /tmp/bug.yml -d frr -p clab
[ERRORS]  Errors found in bug.yml
[VALUE]   vlan: Cannot mix trunk and access VLANs on the same link
```

Perhaps the OP could share a complete topology file that gets processed by Netlab?

**Comment by ipspace** [comment]
> I am unable to process the YAML, even with indentation corrections and assumptions around `module` and `nodes`:

I get the same results (after fixing my blunder -- VLAN IPv4 prefix should be **prefix.ipv4**). The VLAN module correctly complains about **vlan.trunk** and **vlan.access** on the same link (and I have to cleanup the error message ;)

@penguin02007 What version of netlab are you using (**netlab version** displays it)

**Comment by penguin02007** [comment]
> What version of netlab are you using (netlab version displays it)
```
$ netlab version
netlab version 1.9.6
```

>I hope the links is indented (aligned with mode), otherwise we have an interesting parsing problem

I did not aligned with mode... I ran` netlab report addressing` or `;netlab up --dry-run` but it did not complain.

> Perhaps the OP could share a complete topology file that gets processed by Netlab?

Sorry I should have done it, see updated post for diagram and topology.yml. Everything works fine except when it gets into vlan module.

> The VLAN ipv4 prefixes should be configured in global vlans dictionary (for example, vlans.vlan103.ipv4, the node IP addresses should be configured in the node vlans dictionary (for example, r3.vlans.vlan103.ipv4)

I will give this another shot later this evening. thanks!

**Comment by ipspace** [comment]
> netlab version 1.9.6

Upgrading to 2.0.0 couldn't hurt, but 1.9.6 is a pretty recent version.

> I did not aligned with mode... I ran` netlab report addressing` or `;netlab up --dry-run` but it did not complain.

Please post the original topology (it looks like you already modified it based on our suggestions), I would love to understand what's going on.

Also, please note that changing topology file does not change the reports (or results of **netlab inspect**) until you run **netlab create** or **netlab up** (you should get a warning saying that), so if you go from a working topology to one that doesn't parse, you won't get an error until the next **netlab up**/**netlab create**.

**Comment by penguin02007** [comment]
> Please post the original topology (it looks like you already modified it based on our suggestions), I would love to understand what's going on.

See below - 

https://github.com/penguin02007/junoslab/blob/8b9ae7f1c03502b2e5b8f341e96f8e894c3e655e/3-bgp-routing-policy/topology.yml

**Comment by jbemmel** [comment]
> > Please post the original topology (it looks like you already modified it based on our suggestions), I would love to understand what's going on.
> 
> See below -
> 
> https://github.com/penguin02007/junoslab/blob/8b9ae7f1c03502b2e5b8f341e96f8e894c3e655e/3-bgp-routing-policy/topology.yml

Thanks for sharing, some thoughts that come to mind (somewhat overlapping with what Ivan already mentioned)

* ```vlan.links``` is intended to be used for *access* vlans, not trunk ports. To model VLAN 103 for example:
```
links:
- r3:
  p2-1:
  vlan.trunk: [ v103 ]
```

* In your diagram, VLAN 103 and 104 seem to be used as p2p routed vlans with different ip addresses on each interface , not irb vlans with a per-node ip address on the vlan. Something like this:
```
module: [ vlan ]

addressing:
  routed_p2p:
    ipv4: 192.168.0.0/16
    prefix: 31

vlans:
  v103:
    id: 103
    mode: route
    pool: routed_p2p

nodes:
  n1:
  n2:

links:
- n1:
  n2:
  vlan.trunk: [ v103 ]
```

If you want more control over which IPs get allocated, you can override them:
```
links:
- n1:
   vlan.trunk:
     v103:
       ipv4: 10.0.0.0/31
  n2:
   vlan.trunk:
     v103:
       ipv4: 10.0.0.1/31
  vlan.trunk: [ v103 ]
```

**Comment by penguin02007** [comment]
@jbemmel / @ipspace,

After trial and learning, I was able to get it working! That was mix of user error and not defining variables in the correct dictionary.

> Also, please note that changing topology file does not change the reports (or results of netlab inspect) until you run netlab create or netlab up (you should get a warning saying that)

I was able to to get away with  `--cleanup` to check addressing without waiting for netlab.
```
netlab up --dry-run; netlab report addressing
```

Here is the my setup (shorten) now, I ended up spinning a smaller lab to troubleshoot my original lab.

```
$ netlab version
netlab version 2.0.0
```

```
# topology.yml
---
provider: clab
defaults.device: vmx
module: [ vlan ]

nodes:
  r1:
    vlans:
      red:
        ipv4: 192.168.1.0/31
  r2:
    vlans:
      red:
        ipv4: 192.168.1.1/31
  r3:
  r4:
    vlans:
      blue:
        ipv4: 192.168.2.0/31

  r5:
    vlans:
      blue:
        ipv4: 192.168.2.1/31

vlans:
  red:
    id: 100
    mode: route
  blue:
    id: 101
    mode: route

links:
  - r1:
    r2:
    vlan.trunk: [ red ]
  - r2:
    r3:
  - r3:
    r4:
  - r4:
    r5:
    vlan.trunk: [ blue ] 

addressing:
  red:
    ipv4: 192.168.1.0/24
    prefix: 31
  blue:
    ipv4: 192.168.2.0/24
    prefix: 31

```

```
# netlab report addressing with an alias
$ nra
  Node/Interface           IPv4 address                             IPv6 address Description
====================================================================================================
r1 (10.0.0.1/32)
  ge-0/0/0.0                                                                     r1 -> r2
  ge-0/0/0.100           192.168.1.0/31                                          r1 -> r2

r2 (10.0.0.2/32)
  ge-0/0/0.0                                                                     r2 -> r1
  ge-0/0/1.0                10.1.0.1/30                                          r2 -> r3
  ge-0/0/0.100           192.168.1.1/31                                          r2 -> r1

r3 (10.0.0.3/32)
  ge-0/0/0.0                10.1.0.2/30                                          r3 -> r2
  ge-0/0/1.0                10.1.0.5/30                                          r3 -> r4

r4 (10.0.0.4/32)
  ge-0/0/0.0                10.1.0.6/30                                          r4 -> r3
  ge-0/0/1.0                                                                     r4 -> r5
  ge-0/0/1.101           192.168.2.0/31                                          r4 -> r5

r5 (10.0.0.5/32)
  ge-0/0/0.0                                                                     r5 -> r4
  ge-0/0/0.101           192.168.2.1/31                                          r5 -> r4


```
