### ISSUE TITLE
[BUG] Netlab crashes with invalid node name in a VLAN link

### ISSUE THREAD

**Issue by ipspace** [ipspace/netlab#2273]
### Lab topology

```
---
defaults.device: eos
provider: clab

groups:
  _auto_create: True
  hosts:
    members: [ h3, h4 ]
    device: linux
    provider: clab
  switches:
    members: [ dut, s2 ]
    module: [ vlan, vxlan, ospf ]

vlans:
  blue:
    role: external
    links: [ dut-h3, dut-h3a, s2-h4 ]
```

### Output

```
[FATAL]   nodes: Internal error: node does not have a name {'id': 5, 'name': {}}
```

### Diagnosis

It looks like **h3a** is referenced without checking whether it exists. The topology has to be big enough to trigger the error (the above topology is the minimum one I could reproduce the bug with)

**Comment by jbemmel** [comment]
```
---
defaults.device: frr
provider: clab

groups:
  _auto_create: True
  hosts:
    members: [ h3 ]
    device: linux
    provider: clab
  switches:
    members: [ dut ]
    module: [ vlan ]

vlans:
  blue:
    role: external
    links: [ dut-h3a ]
```

Same issue with only 2 nodes
