### ISSUE TITLE
[BUG] Invalid CL NVUE OSPF configuration when running OSPF on VRF loopback

### ISSUE THREAD

**Issue by ipspace** [ipspace/netlab#2274]
CL NVUE OSPF VRF configuration template generates device "lo1" (which is invalid) when a device has OSPF running on a VRF loopback. The error is here:

https://github.com/ipspace/netlab/blob/dev/netsim/ansible/templates/ospf/cumulus_nvue.j2#L29

I could "fix" that replacing l.ifname with 'loopback' but that would then crash if there's more than one loopback in the VRF. Either the configuration template has to be completely redesigned, or we need a device quirk that will throw an error when a VRF has more than one loopback on CL NVUE

### Lab topology

```
---
vrfs:
  tenant:
    loopback: True
    links: [ dut ]
    ospf.active: True

nodes:
  dut:
    device: cumulus_nvue
    module: [ vrf, ospf ]
```
