### ISSUE TITLE
[BUG] OSPF is activated in VXLAN-backed VRF with no OSPF neighbors

### ISSUE THREAD

**Issue by ipspace** [ipspace/netlab#2275]
When a device has no OSPF-capable neighbors in a VRF, it should not run OSPF in it. It looks like the test is incomplete -- in a VXLAN-backed VRF, the neighbor seems to be OSPF-capable even though it has no IP address on the VRF interface.

### Lab topology

It seems you can't make it much smaller -- we need VXLAN to keep OSPF running

```
---
defaults.device: frr
provider: clab

groups:
  _auto_create: True
  hosts:
    members: [ h1, h2 ]
    device: linux

vlans:
  red:
    vrf: tenant
    links: [ s1-h1 ]
  blue:
    vrf: tenant
    links: [ s1-h2 ]

vrfs:
  tenant:
    loopback: True

nodes:
  s1:
    module: [ vlan, vxlan, ospf ]
    vlan.mode: bridge
  ros:
    module: [ vlan, vxlan, ospf, vrf ]
    vlans:                                      # Bring VLANs to ROS (until we agree on a better solution)
      red:
      blue:

links:
- s1:
  ros:
  mtu: 1600
```
