### ISSUE TITLE
[BUG] topology components don't work with libvirt nodes

### ISSUE THREAD

**Issue by ipspace** [ipspace/netlab#2279]
### Lab topology

```
defaults.device: iosv

components:
  site:
    nodes:
      p:

nodes:
  s1:
    include: site
  s2:
    include: site

links: [ s1_p-s2_p ]
```

### Output

```
[FATAL]   Cannot find remote interface for P2P link
... node p
... intf {'ipv4': '10.1.0.1/30', 'linkindex': 1, 'type': 'p2p', 'name': 's1_p -> s2_p', 'ifindex': 1, 'ifname': 'GigabitEthernet0/1', 'neighbors': [{'ipv4': '10.1.0.2/30', 'ifname': 'GigabitEthernet0/1', 'node': 's2_p'}], 'libvirt': {'type': 'tunnel'}}
... link {'interfaces': [{'node': 's1_p', 'ipv4': '10.1.0.1/30', 'ifindex': 1, 'ifname': 'GigabitEthernet0/1'}, {'node': 's2_p', 'ipv4': '10.1.0.2/30', 'ifindex': 1, 'ifname': 'GigabitEthernet0/1'}], '_linkname': 'links[1]', 'linkindex': 1, 'node_count': 2, 'type': 'p2p', 'prefix': {'ipv4': '10.1.0.0/30'}, 'provider': {'libvirt': True}}
... iflist [Box({'node': 's1_p', 'ipv4': '10.1.0.1/30', 'ifindex': 1, 'ifname': 'GigabitEthernet0/1'}), Box({'node': 's2_p', 'ipv4': '10.1.0.2/30', 'ifindex': 1, 'ifname': 'GigabitEthernet0/1'})]
[ DEVICE: iosv PROVIDER: libvirt X_GROUP: frr ]
```
