### ISSUE TITLE
[BUG] Link "interfaces" cannot be used with components

### ISSUE THREAD

**Issue by ipspace** [ipspace/netlab#2284]
### Lab topology

```
defaults.device: frr

components:
  site:
    nodes:
      p:

nodes:
  s1:
    include: site
  s2:
    include: site

links:
- interfaces: [ s1_p, s2_p ]
- s1_p:
  s2_p:
```

### Proposed fix

The code that checks link **interfaces** has to use the same mechanisms to validate node names as the code that parses link strings.
