### ISSUE TITLE
[BUG] netlab crashes with IPv6 /128 prefix on VRF loopback

### ISSUE THREAD

**Issue by ipspace** [ipspace/netlab#2382]
Using the following lab topology:

```
nodes:
  rtr:
    device: frr
    module: [ vrf ]
    vrfs:
      tenant:
        loopback.ipv6: 2001:db8::1/128
```

... results in a crash in **netlab create**
