### ISSUE TITLE
[BUG] pool attribute is accepted on VRF loopback but does nothing

### ISSUE THREAD

**Issue by ipspace** [ipspace/netlab#2383]
Topology:

```
addressing:
  x.ipv6: 2001:db8:1::/48

nodes:
  rtr:
    device: frr
    module: [ vrf ]
    vrfs:
      tenant:
        loopback.pool: x
```

Result:

```
$ netlab inspect --node rtr vrfs
tenant:
  af:
    pool: true
  export:
  - '65000:1'
  id: 1
  import:
  - '65000:1'
  loopback:
    pool: x
  loopback_address:
    pool: x
  networks:
  - pool: x
  rd: '65000:1'
  vrfidx: 100
```
