### ISSUE TITLE
Specify custom pool in VRF loopbacks

### ISSUE THREAD

**Issue by ipspace** [ipspace/netlab#2384]
We should be able to specify custom pool used for VRF loopbacks (for example, to have dual-stack and IPv6-only VRFs)

Sample topology:

```
addressing:
  x.ipv6: 2001:db8:1::/48

vrfs:
  pfx:
    loopback.pool: x

nodes:
  rtr:
    device: frr
    module: [ vrf ]
    vrfs:
      pfx:
```
