### ISSUE TITLE
OSPF: Disable per AF within VRF

### ISSUE THREAD

**Issue by jbemmel** [ipspace/netlab#2398]
https://github.com/ipspace/netlab/blob/f7a4fb9ea0755381a20f561e5333a565977835c2/netsim/modules/ospf.yml#L56

I can disable OSPF for a node per AF, but not within a VRF

Use case is the bgp.multihop VRF test case which requires OSPFv3 within a VRF, which Dell OS10 does not support

Suggestion:
```
vrf:
    af:
      _list_to_dict: True
      _alt_types: [ NoneType ]
      ipv4: bool
      ipv6: bool
```
