### ISSUE TITLE
[BUG] Unnumbered tunnels might work on IOSv (Classic)

### ISSUE THREAD

**Issue by ipspace** [ipspace/netlab#2402]
It's probably possible to configure **ip unnumbered** on tunnel interfaces even on IOSv, but the current "can we do it" device feature check fails because it does not differentiate between interface types.

We need to modify that logic to support a list of interface types which can be unnumbered.

Based on discussion in #2399 started by @DanPartelly

**Comment by DanPartelly** [comment]
It works. Tested on iosv 15.9(3)M8.
 How do you want to proceed from here ?

```
r1#show ip route | inc O 
      
O        10.0.0.2/32 [110/1001] via 10.0.0.2, 00:00:44, Tunnel0
O        172.16.1.0/24 [110/1001] via 10.0.0.2, 00:00:44, Tunnel0

```


Test topology:

r1tun0.j2:

```
interface Tunnel0
 tunnel source GigabitEthernet0/1
 tunnel destination 10.1.0.2
!
```
r2tun0.j2:
```
interface Tunnel0
 tunnel source GigabitEthernet0/1
 tunnel destination 10.1.0.1
!
```

```
defaults:
  provider: clab
  device: iosv


module: [ospf]


nodes:
  r1: 
    config: r1tun0
  r2:
    config: r2tun0  

links:
  underlay:
  - r1:  
    r2:
    role: external
  - r1:
  - r2:
  
  overlay:
  - r1:
    r2:
    type: tunnel
    unnumbered: true
```
