### ISSUE TITLE
[BUG] Static routes are created for fake ebgp.multihop "interface"

### ISSUE THREAD

**Issue by ipspace** [ipspace/netlab#2414]
EBGP multihop plugin creates a fake "interface" that is used to create BGP neighbors for the EBGP multihop session. Unfortunately, the static routing code sees the opportunity to use that "interface" as another next hop for the static routes, resulting in "somewhat" incorrect configuration.

### Lab topology

```
defaults.device: eos
provider: clab
module: [ bgp, routing ]
plugin: [ ebgp.multihop ]

nodes:
  r1:
    bgp.as: 65000
    routing.static:
    - node: r2
      nexthop.node: r2
  r2:
    bgp.as: 65001
    routing.static:
    - node: r1
      nexthop.node: r1

links: [ r1, r1-r2, r1-r2, r2 ]

bgp.multihop.sessions: [ r1-r2 ]
```

### Resulting static route configuration

```
ip route 10.0.0.2/32 Ethernet2 10.1.0.2
ip route 10.0.0.2/32 Ethernet3 10.1.0.6
ip route 10.0.0.2/32 _ebgp_multihop_5 10.0.0.2
```

### Version

I'm positive this bug is in every _netlab_ version that supports static routes
