### ISSUE TITLE
[BUG] BGP community validation error

### ISSUE THREAD

**Issue by ipspace** [ipspace/netlab#2467]
I was trying to validate BGP communities in the same way that I validate BGP session types in #2462 and hit a wall:

The exact same setup as for BGP sessions fails with a weird error message:

```
    community:
      ibgp: { type: list, _subtype: bgp_community_type }
      ebgp: { type: list, _subtype: bgp_community_type }
      _alt_types: [ str, BoxList ]
```

I was also trying to do:

```
    community:
      type: dict
      _keytype: bgp_session_type
      _subtype: { type: list, _subtype: bgp_community_type }
      _alt_types: [ str, BoxList ]
```
... and failed even worse. Obviously, there must still be gremlins hiding in the validation code.
