### ISSUE TITLE
Incorrect interface neighbor list on single-node VLANs

### ISSUE THREAD

**Issue by ipspace** [ipspace/netlab#287]
The following topology incorrectly calculates neighbors on R1 and R2, resulting in no EBGP session between them.

```
nodes:
  r1:
    module: [ bgp ]
    bgp.as: 65000
  s1:
    module: [ vlan ]
    vlans:
      red:
  r2:
    module: [ bgp ]
    bgp.as: 65001

links:
- r1:
  s1:
    vlan.access: red
- r2:
  s1:
    vlan.access: red
```

We should convert single-node VLANs into fake global VLANs (example: vlan@node), and clean them up after the topology transformation.
