### ISSUE TITLE
Incorrect next hop for host static routes in bridged VLANs

### ISSUE THREAD

**Issue by ipspace** [ipspace/netlab#311]
Using this topology:

```
groups:
  hosts:
    members: [ h1, h2 ]
    device: linux
  switches:
    members: [ s1,s2 ]
    module: [ vlan ]
  routers:
    members: [ r1 ]

vlans:
  red:
    mode: bridge
  blue:
    mode: bridge

nodes:
  h1:
  h2:
  s1:
  s2:
  r1:

links:
- s1:
  s2:
  vlan.trunk: [ red, blue ]
- h1:
  s1:
    vlan.access: red
- h2:
  s1:
    vlan.access: blue
- r1:
  s2:
    vlan.access: red
- r1:
  s2:
    vlan.access: blue
```

... the next hop of static routes on h1 and h2 point to s1 which does not have an IP address. We should block assignment of IP address on bridge-only VLANs before the main link transformation.
