### ISSUE TITLE
Incorrect interface neighbor list in VRF lite topology

### ISSUE THREAD

**Issue by ipspace** [ipspace/netlab#325]
The VRF Lite topology in tests/integration/vlan/vlan-vrf-lite.yml results in all three routers apparently being connected to the same core trunk. Here's one of the relevant interfaces on R1:

```
- bridge_group: 2
  ifindex: 4
  ifname: Ethernet1.1
  ipv4: 172.16.6.1/24
  name: r1 -> [r2,r3]
  neighbors:
  - ifname: Ethernet2.1
    ipv4: 172.16.8.2/24
    node: r2
  - ifname: Ethernet1.1
    ipv4: 172.16.8.3/24
    node: r3
  parent_ifindex: 1
  parent_ifname: Ethernet1
  type: vlan_member
  virtual_interface: true
  vlan:
    access_id: 1001
    mode: route
  vrf: blue
```
