### ISSUE TITLE
ebgp-local_as plugin does not recognize bgp.local_as attribute

### ISSUE THREAD

**Issue by jbemmel** [ipspace/netlab#361]
The following does not work:
```
vrfs:
  red:
  blue:

vlans:
  red:
    mode: route
    vrf: red
  blue:
    mode: route
    vrf: blue
  vrf-leak:
    mode: route

nodes:
  r1:
  r2:
    module: [ vlan,vrf,ospf,bgp ]
    bgp.as: 65000
  r3:

links:
- r1:
  r2:
  vlan.trunk: [ red, blue ]
- r2:
  r3:
  vlan.trunk: [ red, blue ]
- interfaces: # VRF route leaking between red and blue, using BGP peering
  - node: r2
    vrf: red
    ipv6: True
    ipv4: False
    bgp.local_as: 65001
    vlan.access: vrf-leak
  - node: r2
    vrf: blue
    ipv6: True
    ipv4: False
    bgp.local_as: 65002
    vlan.access: vrf-leak
```

The r2 link loops to itself, causing it to get excluded from the neighbor list (non-VLAN links do have logic to handle this case)
