### ISSUE TITLE
OSPF is broken on Cumulus Linux 5.0.1

### ISSUE THREAD

**Issue by ipspace** [ipspace/netlab#387]
I tried to set up an OSPF+BGP lab with CL 5.0.1/NVUE (topology `tests/tests/integration/bgp/default-af/topology.yml') and OSPF wouldn't work -- the loopback interface was not in the OSPF process because NVUE **ospf network** statement doesn't make it into FRR.

**nv config show** reports:

```
- set:
    router:
      ospf:
        enable: on
    vrf:
      default:
        router:
          ospf:
            area:
              0.0.0.0:
                network:
                  10.0.0.1/32: {}
            enable: on
            router-id: 10.0.0.1
    interface:
      eth0:
        ip:
          address:
            dhcp: {}
          vrf: mgmt
        type: eth
      lo:
        ip:
          address:
            10.0.0.1/32: {}
            2001:db8:0:1::1/64: {}
        type: loopback
      swp1:
        description: r1 -> r2
        ip:
          address:
            10.1.0.1/30: {}
            2001:db8:2::1/64: {}
        link:
          state:
            up: {}
        router:
          ospf:
            area: 0.0.0.0
            enable: on
            network-type: point-to-point
        type: swp
```

FRR config:

```
!
interface swp1
 ip ospf area 0.0.0.0
 ip ospf network point-to-point
!
router ospf
 ospf router-id 10.0.0.1
```

Please note theres no loopback interface in FRR config, and no OSPF network statement. Interestingly, the IP address on the Linux loopback interface is set correctly.

I tried to migrate to 5.2.0, no change. Looks like CL 5.x is broken, and I don't have the willpower to argue with whoever should fix this. How about you @petercrocker?

I would suggest that we put CL 5.x on hold, document its brokenness in caveats, and wait for them to fix stuff. Alternatively, we could document how to run CL 5.x as CL 4.x (hoping all it takes is changing the Vagrant box). Any other ideas?
