### ISSUE TITLE
Link level vxlan.vlans

### ISSUE THREAD

**Issue by jbemmel** [ipspace/netlab#401]
vxlan.vlans is currently a global or node level parameter. 

Consider a scenario in which a leaf switch uses VXLAN towards some hosts, and regular VLANs towards other hosts:

```
nodes:
 leaf:
 h1:
 h2:

links:
- leaf:
  h1:
  vxlan.vlans: [ red, blue ]
- leaf:
  h2:
  vlan.trunk: [ red, blue ]
```

This does not currently work of course - but could it be supported?
