### ISSUE TITLE
Inconsistency in vlan-routed-trunk test case

### ISSUE THREAD

**Issue by jbemmel** [ipspace/netlab#418]
https://github.com/ipspace/netlab/blob/1f7287d33fb70f7fc089bef90a4e9a7c3b0ea22f/tests/integration/vlan/vlan-routed-trunk.yml#L29

vlan.mode is set to 'route', but in the generated topology for 'ros' we get:
```
vlan:
  max_bridge_group: 2
  mode: route
vlans:
  blue:
    bridge_group: 1
    id: 1001
    mode: irb   <--- !!
```

Similarly, the svi interfaces contain ```mode: irb```
