### ISSUE TITLE
Native routed VLAN breaks all other VLANs on the same trunk

### ISSUE THREAD

**Issue by ipspace** [ipspace/netlab#421]
The following topology creates three routed segments on the R1-R2 link (native, red, and blue):

```
defaults.device: iosv
module: [ vlan ]
vlans:
  red:
  blue:
  pxeboot:
    mode: route

nodes:
  r1:
  r2:

links:
- r1:
  r2:
  vlan.trunk: [ red, blue, pxeboot ]
  vlan.native: pxeboot
```

Removing native VLAN results in correct data structure (two bridged VLANs, one routed VLAN on a VLAN-tagged subinterface). It looks like the **vlan.mode** from **pxeboot** VLAN is copied to the main interface (too soon?). Bad idea...
