### ISSUE TITLE
Incorrect first-hop gateway is calculated for host-only LAN

### ISSUE THREAD

**Issue by ipspace** [ipspace/netlab#427]
There should be no gateway on host-only LAN, but the interfaces on h1 from `tests/integration/vlan/vlan-bridge-multiple.yml` have:

```
- bridge: vlan_1
  gateway:
    ipv4: 172.16.0.2/24
  ifindex: 1
  ifname: eth1
  ipv4: 172.16.0.1/24
  linkindex: 1
  mtu: 1500
  name: h1 -> [s1,h2]
  neighbors:
  - ifname: vlan1000
    node: s1
  - ifname: eth1
    ipv4: 172.16.0.2/24
    node: h2
  role: stub
  type: lan
```

Likewise, **h2** has **h1** as default gateway.

Expected result: no gateway is set.
