### ISSUE TITLE
BGP unnumbered config not working for routed trunk vlan

### ISSUE THREAD

**Issue by jbemmel** [ipspace/netlab#430]
Test case:
```
addressing:
  fabric:
    # unnumbered: true
    ipv4: true
    ipv6: true

provider: clab

module: [ bgp, vlan ]

vlans:
  irb:
    mode: irb
    role: fabric

  route:
    mode: route
    role: fabric

defaults:
 devices:
  srlinux.image: ghcr.io/nokia/srlinux:22.6.3 # Release with BGP unnumbered

nodes:
- name: spine
  device: srlinux
  loopback.ipv4: 1.1.1.1/32
  bgp.as: 65111

- name: leaf
  device: srlinux
  loopback.ipv4: 2.2.2.2/32
  bgp.as: 65222

links:
- spine: #ok
  leaf:
  role: fabric # Without this, default role is 'external'

- spine: #ok
  leaf:
  vlan.trunk: [ irb ]

- spine: #fails, regular ipv4 peering
  leaf:
  vlan.trunk: [ route ]
# role: fabric Without this, the role does not get applied unless 'irb' is used

- spine: #ok
  leaf:
  vlan.access: irb

- spine: #ok
  leaf:
  vlan.access: route
```

The case with ```vlan.trunk: [route]``` fails - a regular IPv4 peering is created, instead of ipv6 unnumbered.
Adding 'role' on the link does fix things

**Comment by jbemmel** [comment]
Difference is here: https://github.com/ipspace/netlab/blob/dev/netsim/modules/vlan.py#L498

```
if routed_access_vlan(link_data,topology,vname):
        link_data.vlan.mode = 'route'
        for intf in link_data.interfaces:
          intf.vlan.mode = 'route'
      else:
        link_data.prefix = prefix
```

The { ipv4: True, ipv6: True } prefix does not get set when mode=='route'

**Comment by ipspace** [comment]
Interesting one, thank you. The VLAN prefix definitely should NOT be copied to the virtual link created from a trunk VLAN (because it's a routed VLAN), the question is whether the role is copied or not, or how this thingy should be configured (IIRC there's the option of having attributes on individual VLANs in a trunk).

Will figure out what's going on and either document the "correct" way of doing it or fix whatever needs to be fixed. Might take a day or two though.

**Comment by jbemmel** [comment]
If the prefix is unnumbered, it **can** be set even on routed vlans. That would fix the issue I'm having. The more general case would probably involve allocation from an address pool (getting the pool to use from the trunk vlan -> node vlan -> global vlan)

Note that the current dev branch does not pass tests - vrf-lite case is broken (no IPs are assigned)

**Comment by ipspace** [comment]
Yes, it's a nasty bug. Minimal test case:

```
addressing:
  fabric:
    ipv4: true
    ipv6: true

defaults.device: eos
module: [ vlan,ospf ]

vlans:
  rvlan:
    mode: route
    role: fabric
    ospf.cost: 10

nodes: [ a,b ]

links:
- a:
  b:
  vlan.trunk: [ rvlan ]
```

Both **role** and **ospf.cost** get copied into node **vlans** and **interfaces**, but the IP prefix is assigned from the LAN pool:

```
interfaces:
...
- bridge_group: 1
  ifindex: 2
  ifname: Ethernet1.1
  ipv4: 172.16.0.1/24
  name: a -> [b]
  neighbors:
  - ifname: Ethernet1.1
    ipv4: 172.16.0.2/24
    node: b
  ospf:
    area: 0.0.0.0
    cost: 10
    network_type: point-to-point
    passive: false
  parent_ifindex: 1
  parent_ifname: Ethernet1
  role: fabric
  type: vlan_member
  virtual_interface: true
  vlan:
    access_id: 1000
    mode: route
    routed_link: true
...
vlans:
  rvlan:
    bridge_group: 1
    id: 1000
    mode: route
    ospf:
      cost: 10
    prefix:
      ipv4: true
      ipv6: true
    role: fabric
    vni: 101000
```
