### ISSUE TITLE
Missing loopback interfaces when using role: host with frr

### ISSUE THREAD

**Issue by jbemmel** [ipspace/netlab#449]
When declaring an frr node in 'host' role:
```
provider: clab

nodes:
  frr-host:
    device: frr
    role: host
```

There is no 'loopback' in the generated YAML -> template fails
