### ISSUE TITLE
VLAN trunks on self-links don't get populated

### ISSUE THREAD

**Issue by jbemmel** [ipspace/netlab#450]
Sample topology:
```
provider: clab

module: [ vrf, vlan ]

vrfs:
  global: # Global VRF

  customer1:

vlans:
  route-leak-to-global-customer1:

nodes:
  leaf1:
    device: srlinux

links:
- interfaces:
  - node: leaf1
    name: Global side
    vlan.trunk: [route-leak-to-global-customer1]
    vlan.trunk:
      route-leak-to-global-customer1:
        vrf: global
  - node: leaf1 # leaf2 for testing
    name: Customer side
    vlan.trunk: [route-leak-to-global-customer1]
    vlan.trunk:
      route-leak-to-global-customer1:
        vrf: customer1
```
The resulting model:
```
nodes:

  leaf1:
...
    interfaces:
    - clab:
        name: e1-1
      ifindex: 1
      ifname: ethernet-1/1
      linkindex: 1
      name: leaf1 -> leaf1
      neighbors:
      - ifname: ethernet-1/2
        node: leaf1
      subif_index: 2
      type: p2p
      vlan: {}   <--- empty
    - clab:
        name: e1-2
      ifindex: 2
      ifname: ethernet-1/2
      linkindex: 1
      name: leaf1 -> leaf1
      neighbors:
      - ifname: ethernet-1/1
        node: leaf1
      type: p2p
      vlan:
        trunk:
          route-leak-to-global-customer1:
            vrf: customer1
        trunk_id:
        - 1000
```

The issue is here: https://github.com/ipspace/netlab/blob/dev/netsim/modules/vlan.py#L725
There are 2 interfaces on the link that match the node; only the first one is ever returned
Consequently, 2 vlan_members are created with the same parent_ifindex=1, instead of one for each side of the link
