### ISSUE TITLE
Adjust link addressing for subnets with small prefix sizes

### ISSUE THREAD

**Issue by jbemmel** [ipspace/netlab#455]
For LAN links, the absolute node.id is used as an index into the prefix: https://github.com/ipspace/netlab/blob/dev/netsim/augment/links.py#L320

This can lead to issues e.g. in case of the following topology: (edited)
```
defaults.device: srlinux

provider: clab

module: [ vlan ]

addressing:
  lan: # Default pool used for vlans, together with 'vlan'
    ipv4: 192.0.0.0/24  # Carve out /31 point-to-point prefixes from this range
    prefix: 31

vlans:
  routed-with-p2p-addressing:
    mode: route

  some-other: # to avoid 'thou shalt not use routed access vlans'
    mode: bridge

nodes:
  r1:
  r2:
  r3:

links:
- r1:
  r2:
  vlan.trunk: [ routed-with-p2p-addressing, some-other ]

- r2:
  r3:
  vlan.trunk: [ routed-with-p2p-addressing, some-other ]
```

This attempts to assign /31 IPs to each pair of IPs on routed vlan links, but results in an error:
```
jeroen@jvm:~/srlinux/netlab/tests$ netlab create -o json topology/input/todo/vlan-routed-p2p-addressing.yml 
IncorrectValue in links: Cannot assign ipv4 address from prefix 192.0.0.6/31 to node r3 with ID 3
... index out range for address range size!
... link data: {'linkindex': 5, 'parentindex': 2, 'vlan': {'access':
      'routed-with-p2p-addressing', 'mode': 'route'}, 'vlan_name':
      'routed-with-p2p-addressing', 'type': 'vlan_member',
      'interfaces': [{'node': 'r2', '_selfloop_ifindex': 0, 'vlan':
      {'access': 'routed-with-p2p-addressing', 'mode': 'route'},
      'ipv4': '192.0.0.7/31', 'ifindex': 5}, {'node': 'r3',
      '_selfloop_ifindex': 1, 'vlan': {'access': 'routed-
      with-p2p-addressing', 'mode': 'route'}}], 'node_count': 2,
      'bridge': 'todo_5', 'prefix': {'ipv4': '192.0.0.6/31'}}
Fatal error in netlab: Cannot proceed beyond this point due to errors, exiting
```
