### ISSUE TITLE
'vlan-routed-native.yml' test case triggers the test for 'vlan.mixed_trunk' feature flag

### ISSUE THREAD

**Issue by ipspace** [ipspace/netlab#456]
The test case is a pure router-on-a-stick scenario where one of the VLANs happens to be native (untagged) -- the **ros** device is routing tagged and untagged IP traffic on its interface.

For whatever weird reason, the test case fails on Arista EOS because it triggers the test for 'vlan.mixed_trunk' feature flag, which should only happen on VLAN trunks with a mix of bridged and routed VLANs.

**Comment by jbemmel** [comment]
FWIW, on SR Linux there is no concept of a 'trunk'. There are interfaces with one or more subinterfaces - conceptually I map 'mixed_trunk' as an interface with vlan tagging enabled, and the vlan-routed-native example falls in that category

Given this mapping, ```mixed_trunk``` is supported, but ```native_routed``` is not

**Comment by ipspace** [comment]
Minimal test topology:

```
defaults.device: eos

vlans:
  red:
  blue:

nodes:
  s1:
    module: [ vlan ]
  ros:
    module: [ ospf,vlan ]
    vlan.mode: route

links:
- s1:
  ros:
  vlan.trunk: [ red, blue ]
  vlan.native: red
```
