### ISSUE TITLE
Module dependency check is not strict enough

### ISSUE THREAD

**Issue by ipspace** [ipspace/netlab#475]
The current module dependency check verifies that the global list of modules is consistent (all required modules are included in the global **module** list) and that the device-specific requirements are met by each node. It obviously does not check whether a node module list is consistent, or this topology wouldn't make it through (causing #466 as a side effect):

```
defaults.device: eos

nodes:
  r1:
    module: [ vlan, vxlan ]
  r2:
    module: [ vxlan ]
```
