### ISSUE TITLE
If OSPF is used only on VRFs, OSPF deployment is miserably failing for almost all the templates

### ISSUE THREAD

**Issue by ssasso** [ipspace/netlab#506]
Assume a topology similar to this one:
```
vrfs:
  common:
    import: [ red, blue, common ]
  blue:
    import: [ blue, common ]
  red:
    import: [ red, common ]

nodes:
  core1:
    module: [ bgp, ospf, vrf ]
    bgp.as: 65000
  aggr1:
    module: [ ospf ]
  aggr2:
    module: [ bgp ]
    bgp.as: 65111
    bgp.originate: [ 100.64.0.0/24 ]
  host1:
    module: []
    device: linux
  host2:
    module: []
    device: linux
  server:
    module: []
    device: linux

links:
- core1: { vrf: red }
  aggr1:
- core1: { vrf: blue }
  aggr2:
- aggr1:
  host1:
  ospf.cost: 22
- aggr2:
  host2:
- core1: { vrf: common }
  server:
```

Where, on `core1`, all the interfaces are inside a VRF.

The generated *host_var* file for Ansible does not have a `ospf` "root object", which leads to this hard failure:
```
    The task includes an option with an undefined variable. The error was: 'ospf' is undefined
```
due to the fact that almost all ospf templates have sth like:
```
{% if ospf.af.ipv4 is defined %}
```

see i.e., 
* https://github.com/ipspace/netlab/blob/dev/netsim/ansible/templates/ospf/eos.j2#L2
* https://github.com/ipspace/netlab/blob/dev/netsim/ansible/templates/ospf/cumulus.j2#L1
* https://github.com/ipspace/netlab/blob/dev/netsim/ansible/templates/ospf/ios.j2#L2

I think we should always add the root `ospf:` object, when the *ospf* module is loaded.
