### ISSUE TITLE
Anycast gateway support and other extended IP addressing features

### ISSUE THREAD

**Issue by jbemmel** [ipspace/netlab#520]
We've mentioned a potential 'gw' module before, but I'm thinking it may be easier to modify the addressing.py code and various initial scripts for platforms, without introducing a separate module (that users may forget to enable, requires separate scripts per platform, etc.)

* Add 'anycast_gateway' attribute to addressing pools - if True or int (offset), allocate an ipv4/ipv6 ip from each prefix and configure it as anycast gateway (on interfaces that enable it)
* Add anycast_ipv4 and anycast_ipv6 to vlans and interfaces (allow 'False' to disable picking up the gateway from an associated vlan and/or pool)
* Modify interface data structures:

```
interfaces:
- ifname: e1-1
  ip:
   v4:
   - address: 172.16.0.1/24  # Primary, anycast
     anycast: True
   - address: 10.0.0.1/24    # Secondary, same subnet or different
   v6: True  # LLA only
```
In other words, allow for multiple addresses per interface, one of which can be anycast.
Platform support for this new addressing structure including anycast can be signaled through a device feature flag

Thoughts/objections? 1.4 feature candidate?
