### ISSUE TITLE
Including unmanaged devices in lab topology

### ISSUE THREAD

**Issue by ssasso** [ipspace/netlab#547]
### Discussed in https://github.com/ipspace/netlab/discussions/538

<div type='discussions-op-text'>

<sup>Originally posted by **ssasso** October  4, 2022</sup>
I have a setup when I want netlab to take care of some network gear equipment config (using the *external* provider), but at the same time I need to establish *peerings* with their counterparts which should not be configured by netlab.
(i.e. configure a BGP session on a device controlled by netlab)

I was thinking to use the **none** device type for that kind of stuff, with sth like:
```
vrfs:
  RED:
  BLUE:

vlans:
  site1red:
    mode: route
    id: 41
    vrf: RED
    bgp: false
  site1blue:
    mode: route
    id: 61
    vrf: BLUE

module: [ vlan,vrf,ospf,bgp,mpls ]
bgp.as: 65000

nodes:
  pe1:
  site1a:
    device: none
    module: [ vlan,vrf,bgp ]
    bgp.as: 65101
  site1b:
    device: none
    module: [ vlan,vrf,bgp ]
    bgp.as: 65101

links:
- pe1:
    ifname: eth3
    vlan.trunk:
      site1red.ipv4: 172.24.111.33/28
      site1blue.ipv4: 10.211.211.1/28
  site1a:
    vlan.trunk:
      site1red.ipv4: 172.24.111.34/28
      site1blue.ipv4: 10.211.211.11/28
  site1b:
    vlan.trunk:
      site1red.ipv4: 172.24.111.35/28
      site1blue.ipv4: 10.211.211.12/28
  vlan.trunk: [ site1red, site1blue ]
```

(for this specific example, I need *pe1* to have two configured bgp sessions towards *10.211.211.11* and *10.211.211.12*.)

But unfortunately the *none* device does not support vlan, vrf, and bgp.

Do you think it would be a good idea to allow the *none* device type to support all modules,
or should I use a *real platform* on all the devices, and the rely on a **group** of configurable devices to limit the ansible config with `-l group`?</div>
