### ISSUE TITLE
Do not use "sequential" IPAM allocation method on VLAN links

### ISSUE THREAD

**Issue by ipspace** [ipspace/netlab#564]
VLAN trunks that are part of the same VLAN with **mode** set to **irb** or **route** are stretched across multiple virtual links (we never create a single VLAN-wide virtual link), so we cannot use "sequential" IPAM method on them.

Sample topology:

```
groups:
  hosts:
    members: [ h1, h2 ]
    device: linux
  switches:
    members: [ s1, s2 ]
    device: cumulus
    module: [ vlan ]

vlans:
  red:
    prefix:
      ipv4: 192.168.1.0/28

nodes:
  h1:
    id: 150
  h2:
  s1:
  s2:

links:
- h1:
  s1:
  vlan.access: red
- s1:
  s2:
  vlan.access: red
- s2:
  h2:
  vlan.access: red
```

Duplicate IP addresses can be observed in the neighbors list on S1 interfaces:

```
- bridge_group: 1
  ifindex: 3
  ifname: vlan1000
  ipv4: 192.168.1.2/28
  name: VLAN red (1000) -> [h1,s2,h2]
  neighbors:
  - ifname: eth1
    ipv4: 192.168.1.1/28
    node: h1
  - ifname: vlan1000
    ipv4: 192.168.1.3/28
    node: s2
  - ifname: eth1
    ipv4: 192.168.1.1/28
    node: h2
  type: svi
  virtual_interface: true
  vlan:
    mode: irb
```
