### ISSUE TITLE
[bug]: clab binds not parsed correctly

### ISSUE THREAD

**Issue by ryanmerolle** [ipspace/netlab#597]
I am labing the gnmic to kafka lab from the [gnmic example deployments](https://github.com/openconfig/gnmic/blob/main/examples/deployments/1.single-instance/2.kafka-output/containerlab/kafka.clab.yaml) but with Arista EOS.

My topology file is as follows:

```yaml
---
provider: clab
defaults:
  device: eos
  devices:
    eos:
      clab:
        image: arista/ceos:4.28.3M

nodes:
  - name: spine1
  - name: spine2
  - name: leaf1
  - name: leaf2
  - name: leaf3
  - name: leaf4

  - name: gnmic
    device: linux
    image: ghcr.io/openconfig/gnmic:latest
    clab:
      binds:
        './gnmic.yaml': '/app/gnmic.yaml:ro'
        '/var/run/docker.sock': '/var/run/docker.sock'
      cmd: '--config /app/gnmic.yaml --log subscribe'

  - name: kafka-server
    device: linux
    image: bitnami/kafka:latest
    clab:
      ports:
        - 9092:9092
        - 9000:9000
      env:
        KAFKA_CFG_ZOOKEEPER_CONNECT: clab-lab12-zookeeper-server:2181
        KAFKA_CFG_ADVERTISED_LISTENERS: PLAINTEXT://clab-lab12-kafka-server:9092
        ALLOW_PLAINTEXT_LISTENER: "yes"
        JMX_PORT: 9000

  - name: zookeeper-server
    device: linux
    image: bitnami/zookeeper:latest
    clab:
      ports:
        - 2181:2181
      env:
        ALLOW_ANONYMOUS_LOGIN: "yes"

  - name: kafka-ui
    device: linux
    image: provectuslabs/kafka-ui:latest
    clab:
      ports:
        - 8080:8080
      env:
        KAFKA_CLUSTERS_0_NAME: "local"
        KAFKA_CLUSTERS_0_BOOTSTRAPSERVERS: "PLAINTEXT://clab-lab12-kafka-server:9092"
        KAFKA_CLUSTERS_0_ZOOKEEPER: "localhost:2181"

links:
# spine1 links
  - spine1-leaf1
  - spine1-leaf2
  - spine1-leaf3
  - spine1-leaf4
# spine2 links
  - spine2-leaf1
  - spine2-leaf2
  - spine2-leaf3
  - spine2-leaf4
```

Instead of seeing a bind setup like [the example file](https://github.com/openconfig/gnmic/blob/main/examples/deployments/1.single-instance/2.kafka-output/containerlab/kafka.clab.yaml#L27-L33), 

```yaml
    gnmic:
      kind: linux
      image: ghcr.io/openconfig/gnmic:latest
      binds:
        - ./gnmic.yaml:/app/gnmic.yaml:ro
        - /var/run/docker.sock:/var/run/docker.sock
      cmd: '--config /app/gnmic.yaml --log subscribe'
```

I see netlab outputs an incorrect set of bind config.

```yaml
    gnmic:
      mgmt_ipv4: 192.168.121.107
      kind: linux
      image: ghcr.io/openconfig/gnmic:latest
      binds:
      - :{'/gnmic': {'yaml': '/app/gnmic.yaml:ro'}}
      - /var/run/docker:{'sock': '/var/run/docker.sock'}
```

As always I very much appreciate the work you do here and with the site.
