### ISSUE TITLE
VRF instance 'as' parameter

### ISSUE THREAD

**Issue by jbemmel** [ipspace/netlab#613]
Not really an 'issue', more of a side note: topology-defaults allows 'as' as a global and per-node parameter for the "vrf" module

This means the following is accepted:
```
vrf.as: 1234
vrfs:
 a:
  as: 4321
```

'vrf.as' is referenced, but 'as' at the individual vrf level isn't read/used anywhere (as far as I can tell)

Conceptually, the two options illustrated above are different - shouldn't they be modeled differently?

For example:
``` yaml title="topology-defaults.yml"
vrf: # Basic VRF support
  supported_on: [ eos, iosv, csr, routeros, dellos10, vyos, cumulus_nvue, nxos, srlinux, frr, cumulus, sros, routeros7, none ]
  config_after: [ vlan, ospf, isis, bgp, mpls ]
  transform_after: [ vlan, bgp ]
  as: 65000
  attributes:
    global: [ as,loopback ]
    node: [ as,loopback ]
    vrf: [as,loopback ]    # <-- *NEW*
    link: str
    interface: str
    extra:
      global: [ vrfs ]
      node: [ vrfs ]
```

**Comment by ipspace** [comment]
IIRC, `vrf.as` is used to generated RD/RT sometimes needed for local route leaking. Have to check where exactly it's used and remove it from all other attribute lists. 

Thank you!

**Comment by ipspace** [comment]
When you wrote 'the following is accepted', was it 'I had a topology and it behaved this way' (in which case I'd love to see it) or was it 'I think this might happen'? When I tried to recreate the behavior to have a test to validate that the bug has been fixed, I used this topology:

```
defaults.device: eos
module: [ vrf ]

vrf.as: 1234
vrfs:
 a:
  as: 4321

nodes: [ r1 ]
```

... and got the following error:

```
$ netlab create -o none x.yml
IncorrectAttr in vrf: Invalid VRF attribute 'as' found in vrfs.a
Fatal error in netlab: Cannot proceed beyond this point due to errors, exiting
```

Would love to hear what you've experienced and what topology triggered it.
