### ISSUE TITLE
EVPN VLAN bundle data model

### ISSUE THREAD

**Issue by jbemmel** [ipspace/netlab#636]
I have some pending changes to add MPLS support for SR OS, but they depend on a change to the data model to support both VLAN-aware and non-VLAN-aware bundles

Proposal:
```
evpn.bundle:
  vrf: xyz
  vlan_aware: True # Omit to auto-select based on device supported feature(s)
```

```
features:
 evpn:
  vlan_bundle: True
  vlan_aware_bundle: False
```

_Originally posted by @jbemmel in https://github.com/ipspace/netlab/discussions/554#discussioncomment-3897927_
