### ISSUE TITLE
[BUG] Propagation of VLANs and VRFs is too aggressive

### ISSUE THREAD

**Issue by ipspace** [ipspace/netlab#643]
### Describe the bug

Globally VXLAN-enabled VLANs are propagated to nodes that have no reason to use them

### Expected behavior

S3 in the following lab topology has no need for red or blue VRF, or for red_transport or blue_transport VLAN.

### Lab topology

```
defaults.device: eos

groups:
  hosts:
    members: [ rh1, rh2 ]
    device: linux
  pe:
    members: [ s1,s2,s3 ]
    module: [ vlan,vxlan,ospf,vrf ]

vrfs:
  red:
  blue:

vlans:
  red_transport:
    vrf: red
  blue_transport:
    vrf: blue

vxlan.vlans: [ red_transport, blue_transport ]

nodes: [ rh1, rh2, s1, s2, s3 ]

links:
- s1-s2
- s2-s3

# Red VRF
- rh1:
  s1:
  vrf: red
- rh2:
  s2:
  vrf: red
```

### Version

* netlab version 1.4.0
