### ISSUE TITLE
[BUG] Unable to use 'plugin' in group data

### ISSUE THREAD

**Issue by jbemmel** [ipspace/netlab#655]
### Describe the bug

Netlab allows users to set attributes for groups of nodes, but the 'plugin' attribute cannot be set this way

### To Reproduce
```
groups:
  X:
   members: [ a,b,c ]
   plugin: [ ebgp.utils ]
```

### Expected behavior

Plugin should be applied to all members of the group

### Lab topology

```
groups:
  routers:
    members: [ r1, r2 ]
    plugin: [ ebgp.utils ] # doesn't work

nodes: [ r1,r2 ]

links: 
- r1-r2
```

### Output (after adding 'plugin' as an allowed group attribute in topology-defaults)

```
jeroen@jvm:~/srlinux/netsim-examples/EVPN/mpls-routing$ netlab create -v

Read YAML data from topology.yml
loading netsim.providers.clab...
... found <class 'netsim.providers.clab.Containerlab'> 
loading netsim.modules.bgp...
... found <class 'netsim.modules.bgp.BGP'> 
loading netsim.modules.evpn...
... found <class 'netsim.modules.evpn.EVPN'> 
loading netsim.modules.mpls...
... found <class 'netsim.modules.mpls.MPLS'> 
loading netsim.modules.ospf...
... found <class 'netsim.modules.ospf.OSPF'> 
loading netsim.modules.vlan...
... found <class 'netsim.modules.vlan.VLAN'> 

IncorrectAttr in evpn: Invalid evpn interface attribute 'mh_lag' found in links[3].r1.evpn
IncorrectAttr in evpn: Invalid evpn interface attribute 'mh_lag' found in links[4].r1.evpn
IncorrectAttr in evpn: Invalid evpn interface attribute 'mh_lag' found in links[5].r2.evpn
IncorrectAttr in evpn: Invalid evpn interface attribute 'mh_lag' found in links[6].r2.evpn

Fatal error in netlab: Cannot proceed beyond this point due to errors, exiting
```

### Version

dev branch
