### ISSUE TITLE
netlab test clab fails

### ISSUE THREAD

**Issue by steffann** [ipspace/netlab#663]
### Describe the bug

The recommended test to run after installation fails.

### To Reproduce

- sudo python3 -m pip install networklab
- netlab install ubuntu ansible libvirt containerlab
- netlab test clab

### Expected behavior

A succesful test :)

### Lab topology

```
sander@netlab:~$ cat test/topology.yml
#
# Simple libvirt lab using three Cumulus VX devices
#
---
defaults:
  device: cumulus

provider: clab

module: [ ospf ]
nodes:
  s1:
    runtime: docker
  s2:
    runtime: docker
  s3:
    runtime: docker
links: [ s1-s2, s2-s3 ]
```

### Output

When finishing the installation I see:
```
=====================================================================
Docker and Containerlab were successfully installed.

To test the installation:

* Log out
* Log back in
* Run 'netlab test clab'
=====================================================================
```

I log out, log back in, and execute `netlab test clab`, and get:

```
sander@netlab:~$ netlab test clab

Step 1: Checking virtualization provider installation
============================================================
.. all tests succeeded, moving on

Step 2: creating configuration files
============================================================
Error executing netlab create:
  Command '['netlab', 'create']' returned non-zero exit status 1.
Fatal error in netlab test: netlab create failed, aborting...
```

Running `netlab create` manually in the test directory shows:

```
sander@netlab:~/test$ netlab create
IncorrectAttr in nodes: Invalid node attribute 'runtime' found in nodes.s1
IncorrectAttr in nodes: Invalid node attribute 'runtime' found in nodes.s2
IncorrectAttr in nodes: Invalid node attribute 'runtime' found in nodes.s3
Fatal error in netlab: Cannot proceed beyond this point due to errors, exiting
```

### Version

netlab version 1.4.1
