### ISSUE TITLE
[BUG] Nodes with VXLAN module should be connected to at least one link

### ISSUE THREAD

**Issue by ipspace** [ipspace/netlab#664]
### Describe the bug

Arista EOS refuses to configure the VXLAN interface if the node has no Ethernet interfaces. While that might be considered platform-specific, it does make sense to expect at least one usable interface on nodes with VXLAN module.

### Lab topology

```
---
nodes:
  s1:
    module: [ vxlan, vlan ]
    device: eos
```

### Version

* netlab version 1.4.1-post1
