### ISSUE TITLE
[BUG] OSPF bfd attribute is copied under host interfaces even if ospf is disabled

### ISSUE THREAD

**Issue by ssasso** [ipspace/netlab#679]
### Describe the bug

OSPF bfd attribute is copied under host interfaces even if ospf if disabled.
This makes the templates that use `l.ospf.area` to fail.

### Expected behavior

If ospf is disabled for a link, then the `ospf` dict shall not exist at all on the interface struct.

### Lab topology

```
---
defaults:
  device: vsrx

module: [ ospf ]
ospf:
  area: 0.0.0.0
  bfd: true

nodes:
  j1:
  j2:

links:
 - j1:
   j2:
 - j1:
   ospf.passive: true
   ospf.cost: 44
 - j2:
   ospf.passive: true
   ospf.cost: 55
 - j1:
   j2:
   ospf: false
```

### Output

j1's host_vars file (the interface with wrong ospf attributes is `ge-0/0/2`):
```
# Ansible inventory created from ['topology.yml', 'package:topology-defaults.yml']
#
---
af:
  ipv4: true
box: juniper/vsrx3
interfaces:
- ifindex: 0
  ifname: ge-0/0/0
  ipv4: 10.1.0.1/30
  libvirt:
    type: tunnel
  linkindex: 1
  name: j1 -> j2
  neighbors:
  - ifname: ge-0/0/0
    ipv4: 10.1.0.2/30
    node: j2
  ospf:
    area: 0.0.0.0
    bfd: true
    network_type: point-to-point
    passive: false
  remote_id: 2
  remote_ifindex: 0
  type: p2p
- bridge: bug_ospf_b_2
  ifindex: 1
  ifname: ge-0/0/1
  ipv4: 172.16.0.1/24
  linkindex: 2
  name: j1 -> stub
  neighbors: []
  ospf:
    area: 0.0.0.0
    bfd: true
    cost: 44
    passive: true
  type: stub
- ifindex: 2
  ifname: ge-0/0/2
  ipv4: 10.1.0.5/30
  libvirt:
    type: tunnel
  linkindex: 4
  name: j1 -> j2
  neighbors:
  - ifname: ge-0/0/2
    ipv4: 10.1.0.6/30
    node: j2
  ospf:
    bfd: true
  remote_id: 2
  remote_ifindex: 2
  type: p2p
loopback:
  ipv4: 10.0.0.1/32
mgmt:
  ifname: fxp0
  ipv4: 192.168.121.101
  mac: 08-4F-A9-00-00-01
module:
- ospf
ospf:
  af:
    ipv4: true
  area: 0.0.0.0
  bfd: true
  router_id: 10.0.0.1
```

### Version

* dev

**Comment by ipspace** [comment]
Thank you, will fix.

**Comment by ipspace** [comment]
Minimal topology:

```
module: [ ospf ]
ospf:
  area: 0.0.0.0
  bfd: true

nodes: [ j1, j2 ]

links:
 - j1:
   j2:
   ospf: false
```

Expected results: no **ospf** key on interfaces
