### ISSUE TITLE
[BUG] Cisco IOSv enables IPv4 BGP AF even when told not to do so

### ISSUE THREAD

**Issue by ipspace** [ipspace/netlab#680]
### Describe the bug

Using `tests/integration/ibgp-v6.yml` topology, IPv4 AF is enabled on IOSv

### Expected behavior

Only IPv6 AF should be enabled.

### Lab topology

```
addressing:
  loopback:
    ipv6: 2001:db8:0::/48
  lan:
    ipv6: 2001:db8:1::/48
  p2p:
    ipv6: 2001:db8:2::/48

module: [ ospf, bgp ]

bgp.activate:
  ipv4: [ ]
  ipv6: [ ibgp ]

bgp.as: 65000

nodes:
  r1:
  r2:

links:
- r1-r2
```

### Version

* dev
