### ISSUE TITLE
Composite topologies

### ISSUE THREAD

**Issue by ipspace** [ipspace/netlab#698]
Time to implement the discussion we had in #151:

* A new top-level attribute **components** would allow you to define reusable lab components.
* Each component would have **links** and **nodes** plus any valid top-level module attribute
* Links within a component could refer to nodes within the component or to global nodes (not recommended)
* Nodes within the component would have the usual **nodes** structure

Components would be used within **nodes** dictionary. The key (node name) would be the prefix used to include the component (see below), the value would have to have an **include** attribute that would refer to a valid component. The value could also include any valid node-level attribute.

Including a component would include all component nodes and links into the main **nodes** dictionary. Node names and references in links would be prefixed with the included component prefix. You could then use the prefixed names in top-level links to connect a component to the outside world.

Example: two leaf-and-spine clusters connected with a superspine. IBGP+OSPF within each cluster, EBGP with superspine.

```
defaults.device: frr

components:
   pod:
      nodes: [ l1, l2, s1, s2 ]
      module: [ ospf, bgp ]
      bgp.as: 65000
      links: [ l1-s1, l1-s2, l2-s1, l2-s2 ]

nodes:
  c1:
    bgp.as: 65100
  c2:
    bgp.as: 65100
  pod_1:
    include: pod
    bgp.as: 65101
  pod_2:
    include: pod
    bgp.as: 65102

links:
- c1-pod_1_s1
- c1-pod_2_s1
- c2-pod_1_s2
- c2-pod_2_s2
```
