### ISSUE TITLE
More thorough attribute checking framework

### ISSUE THREAD

**Issue by ipspace** [ipspace/netlab#700]
Right now we have a generic framework that checks the validity of attribute names, the values of attributes are checked throughout the code. We could get rid of most of the value checks if we describe attributes better.

Right now, the valid global/node/vlan/vrf/module... attributes are specified as lists of valid attribute names, for example:

```
bgp:
  attributes:
    global: [
      af, as, next_hop_self, rr_cluster_id, rr_list, ebgp_role, as_list, sessions, activate,
      advertise_loopback, advertise_roles, community, replace_global_as ]
    node: [
      af, as, next_hop_self, rr, rr_cluster_id, originate, advertise_loopback, sessions, activate,
      community, router_id, local_as, replace_global_as ]
    vrf: [ router_id ]
    node_copy: [ local_as, replace_global_as ]
    link: [ advertise ]
    interface: [ local_as, replace_global_as ]
```

Instead of using attribute lists, we could use dictionaries and (optionally) describe attributes with sub-dictionaries, for example (ignoring the question of whether we're supporting 4-byte ASN or not):

```
bgp:
  attributes:
    vrf: 
      router_id: { type: 'ipv4' }
    link:
      advertise: { type: 'bool' }
    interface:
      local_as: { type: 'int', min_value: 1, max_value: 65535, value_error: 'BGP AS number should be between 1 and 65535' }
```

We would need some shortcuts, like user-defined type (doesn't make sense to repeat 'what is AS' everywhere an AS is used) and simple inheritance (local_as can appear on node or interface).

**Migration process:** attributes specified in the new format would go through the thorough value tests, attributes specified as lists would get their names checked. We could thus gradually migrate individual attributes or modules to the new framework.
