### ISSUE TITLE
VRF and VLAN links

### ISSUE THREAD

**Issue by ipspace** [ipspace/netlab#707]
I like specifying links in the shorthand format (a-b instead of the full dictionary). That doesn't work well for VLAN and VRF links as they need additional attributes.

We could solve that by adding **links** list to global VRFs and VLANs, for example:

```
groups:
  routers:
    module: [ vrf ]
    members: [ r ]

nodes: [ r, h1, h2, h3, h4 ]

vrf:
  red:
    links: [ h1-r, h2-r ]
  blue:
    links: [ h3-r, h4-r ]
```

VRF and VLAN links would

* be transformed into the usual dictionary format
* get **vrf: X** or **vlan.access: X** attribute
* be appended to the global **links** list

Feedback appreciated ;)
