### ISSUE TITLE
Use a shared management network for libvirt and clab nodes

### ISSUE THREAD

**Issue by ipspace** [ipspace/netlab#714]
Based on #711 multi-provider topology with SSH-enabled containers won't work. We have to make sure that clab uses the same Linux bridge as vagrant-libvirt.

**Comment by ipspace** [comment]
Test case:

```
module: [ ospf ]
provider: libvirt

nodes:
  r1:
    device: cumulus
  r2:
    device: eos
    provider: clab

links:
- r1-r2
```
