### ISSUE TITLE
Inherit attribute checks (global->node, link->intf)

### ISSUE THREAD

**Issue by ipspace** [ipspace/netlab#715]
#713 requires multiple definitions of attribute data types for global and node-level module parameters and for link- and interface parameters, for example:

```
eigrp:
  attributes:
    global:
      af:
        ipv4: bool
        ipv6: bool
      as: { type: int, min_value: 1, max_value: 65535 }
    node:
      af:
        ipv4: bool
        ipv6: bool
      as: { type: int, min_value: 1, max_value: 65535 }
    link:
      passive: bool
```

Node attributes should inherit global data type checks if the data type is not specified. Similar inheritance should be established between links and interfaces and between nodes and interfaces for attributes listed in **node_copy** list.

For example, EIGRP attributes should be simplified to:

```
eigrp:
  attributes:
    global:
      af:
        ipv4: bool
        ipv6: bool
      as: { type: int, min_value: 1, max_value: 65535 }
    node:
      af:
      as:
    link:
      passive: bool
```

As an optional step, we could automatically convert child attribute lists into dictionaries. The final EIGRP attribute definition would become even simpler:

```
eigrp:
  attributes:
    global:
      af:
        ipv4: bool
        ipv6: bool
      as: { type: int, min_value: 1, max_value: 65535 }
    node: [ af, as ]
    link:
      passive: bool
```
