### ISSUE TITLE
[BUG] Invalid management interface name on cEOS node using secondary provider

### ISSUE THREAD

**Issue by ipspace** [ipspace/netlab#718]
### Describe the bug

vEOS uses Management1, cEOS uses Management0. The management interface name should be derived from provider-specific node data which does not happen if the cEOS node is using secondary provider.

### Lab topology

```
module: [ ospf ]
provider: libvirt

nodes:
  r1:
    device: cumulus
  r2:
    device: eos
    provider: clab

links:
- r1-r2
```

### Version

* 1.5.0-dev1
