### ISSUE TITLE
Link groups

### ISSUE THREAD

**Issue by ipspace** [ipspace/netlab#727]
Here's a generalization of #707:  use nested **links** to configure groups of links with the same attributes. For example:

```
links:
- name: Core fabric links
  vlan:
    trunk: [ a,b,c ]
    native: a
  bandwidth: 10000
  ospf.cost: 10
  links: [ l1-s1, l1-s2, l2-s1, l2-s2 ]
- name: Edge links
  vlan.access: b
  links: [ l1-h1, l2-h2 ]
```

The expansion is trivial: whenever an element in the **links** list has a **links** element, expand it into a list of links sharing the attributes (apart from **links**) of the parent link group.

Any thoughts on this @ssasso @petercrocker @jbemmel @ddutt?
