### ISSUE TITLE
[BUG] Module extra attributes cannot be used in group data

### ISSUE THREAD

**Issue by ipspace** [ipspace/netlab#740]
### Describe the bug

A BGP module node attribute defined with 'extra_attributes' is not recognized when used in a group.

### Expected behavior

The same module is recognized when used within an individual node. Group- and node behavior should be identical.

### Lab topology

```
module: [ bgp ]
defaults.bgp.extra_attributes.node: [ anycast ]

groups:
  anycast:
    members: [ r ]
    bgp.anycast: 10.42.42.42

nodes:
  r:
    device: eos
    bgp.as: 65000
```

### Version

* netlab version 15.0
