### ISSUE TITLE
[BUG] Specifying loopback address for a node is no longer a supported attribute

### ISSUE THREAD

**Issue by jbemmel** [ipspace/netlab#747]
### Describe the bug

It used to be possible to do this:
```
nodes:
 ...
  pe1:
  pe2:

  c1:
    loopback.ipv6: 2001:cafe::1/64
```

i.e. use ipv4-only loopbacks for most nodes, but add ipv6 loopbacks for some specific ones.
This is supported within vrfs, but 'loopback' is not a supported node attribute

### Expected behavior

Node c1 should get the assigned ipv6 loopback address

### Lab topology

```
defaults:
  device: srlinux

provider: clab

addressing:
  loopback:
    ipv4: 10.0.0.0/24
nodes:
  c1:
    loopback.ipv6: 2001:cafe::1/64
```

### Output

```
netlab up /tmp/test.yml 

IncorrectAttr in nodes: Invalid node attribute 'loopback' found in nodes.c1

Fatal error in netlab: Cannot proceed beyond this point due to errors, exiting
```

### Version

1.5.0-post2
