### ISSUE TITLE
[BUG] Ignore primary provider specified as per-node secondary provider

### ISSUE THREAD

**Issue by ipspace** [ipspace/netlab#773]
### Describe the bug

I want to run a test lab with Linux hosts running as containers. That's easy to do with `provider: clab` parameter specified on Linux nodes. However, it the main provider is set to `clab`, **netlab create** fails because `clab` cannot be a sub-provider of `clab`.

### Expected behavior

Secondary provider should be ignored when it's identical to the primary provider

### Lab topology

```
provider: clab

nodes:
  r:
    device: eos
  h:
    device: linux
    provider: clab
```

### Output

```
IncorrectValue in nodes: Provider clab specified in node h is not compatible with lab topology provider clab
Fatal error in netlab: Cannot proceed beyond this point due to errors, exiting
```

### Version

* netlab version 1.5.x
