### ISSUE TITLE
[BUG] Links with one node attached to them cannot be addressed from the loopback pool

### ISSUE THREAD

**Issue by ipspace** [ipspace/netlab#787]
### Describe the bug

A tunnel headend cannot be addressed from the loopback pool even though there's only a single node attached to the link.

### Lab topology

```
defaults.device: iosv

nodes: [ r1 ]

links:
- r1:
  type: tunnel
  pool: vrf_loopback
```

### Output

```
netlab create -o none lbp.yml
IncorrectValue in links: Cannot use ipv4 prefix 10.2.0.1/32 to address 1 nodes on links[1]
... link data: {'_linkname': 'links[1]', 'type': 'tunnel', 'pool': 'vrf_loopback',
      'interfaces': [{'node': 'r1'}], 'linkindex': 1, 'node_count': 1, 'bridge': 'X_1',
      'prefix': {'ipv4': '10.2.0.1/32'}}
Fatal error in netlab: Cannot proceed beyond this point due to errors, exiting
```

### Version

* netlab version 1.5.x
