### ISSUE TITLE
[BUG] Tool-specific attributes cannot be configured on nodes

### ISSUE THREAD

**Issue by ipspace** [ipspace/netlab#795]
### Describe the bug

Graphite tool can use **graphite.icon** node attribute to display different icons for individual lab devices, however the node attribute validation logic reports an error when that attribute is used.

### Expected behavior

netlab should support tool-specific attributes in nodes and groups.

### Lab topology

```
defaults.device: none
nodes:
  r1:
    graphite.icon: router
tools:
  graphite:
```

### Version

* netlab version 1.5.x
