### ISSUE TITLE
[BUG] NXOS initial configuration template fails with IPv6 LLA interfaces

### ISSUE THREAD

**Issue by ipspace** [ipspace/netlab#798]
### Describe the bug

IPv6 LLA interfaces cannot be configured on Nexus OS -- Ansible fails with a templating error message

### To Reproduce

Execute `netlab create` followed by `netlab initial -o` using the below lab topology.

### Lab topology

```
nodes:
  sw:
    device: nxos

links:
- sw:
  prefix.ipv6: True
```

### Version

Probably present in all netlab versions 

### Additional context

Initially reported (together with a solution) in a private email.
