### ISSUE TITLE
[BUG] Cumulus hostname cannot contain underscores

### ISSUE THREAD

**Issue by ipspace** [ipspace/netlab#819]
### Describe the bug

Initial device configuration fails on Cumulus Linux if the hostname contains an underscore

### Minimum Topology

```
provider: clab
nodes:
  A_1:
    device: cumulus
```

### Version

All versions (the config template has never been changed)
