### ISSUE TITLE
[BUG] VLAN interfaces are not created in topology that has no links element

### ISSUE THREAD

**Issue by ipspace** [ipspace/netlab#829]
### Describe the bug

If a topology has no `links` element, the links-related module hooks are not called and thus the VLAN module does not create VLAN interfaces.

### Lab topology

```
defaults.device: eos
module: [ vlan, vrf ]

vrfs:
  tenant:

vlans:
  red:
    vrf: tenant

nodes:
  a:
    vrfs:
      tenant:
    vlans:
      red:
```

### Proposed remediation

Create an empty `links` element in VLAN module if needed (after fixing #828)

### Version

* 1.5.x, probably much earlier than that (the code is pretty old)
