### ISSUE TITLE
Static Management Addresses

### ISSUE THREAD

**Issue by achurak** [ipspace/netlab#856]
Hello,

I'm a bit confused about the subj, can I assign static management addresses to the nodes or not? I see this construct all over the place in the documentation:

```
nodes:
  spine01:
    box: cisco/nexus9300v:10.3.3
    mgmt:
      ipv4: 192.168.121.18
```

However when I try to start a lab with this configuration I'm getting 

```
IncorrectAttr in nodes: Invalid node attribute 'mgmt' found in nodes.spine01
Fatal error in netlab: Cannot proceed beyond this point due to errors, exiting
```

Am I doing something wrong? Are static management addresses supported or does it have to be assigned by a DHCP server?

Thanks!
