### ISSUE TITLE
[BUG] Custom link/interface attribute lost when using vlans in particular order

### ISSUE THREAD

**Issue by jbemmel** [ipspace/netlab#866]
### Describe the bug

In my use case I am trying to define a custom attribute 'epipe' on a link/interface. Given a certain combination of vlans on links, this attribute is lost in translation

### To Reproduce

```netlab create```

### Expected behavior

The 'epipe' attribute should show up in the topology file (ideally on the physical port like the 'mtu' link attribute, for some reason it gets copied to the vlan interface instead)

### Lab topology

```
message: |
  Illustrates an issue with a custom link attribute getting lost in translation

provider: clab

defaults:
  device: sros
  attributes.link.epipe: id

module: [vlan]

vlans:
  tenant:
    mode: bridge

groups:
  hosts:
    members: [ ce20 ]
  core:
    members: [ pe2 ]
  mtu:
    members: [ mtu1 ]

nodes:
 mtu1:
 pe2:
 ce20:

links:
- ce20: # Removing this one fixes the issue
  pe2:
  vlan.access: tenant
- mtu1:
  pe2:
   epipe: epipe-1     # This attribute is lost
   mtu: 1234
  vlan.access: tenant # This causes the epipe link attribute to get lost
```

### Output

In host_vars/pe2/topology.yml
```
hostname: clab-tmp-pe2
interfaces:
- bridge: tmp_1
  clab:
    name: eth1
  ifindex: 1
  ifname: 1/1/c1
  linkindex: 1
  mtu: 1500
  type: lan
  vlan:
    access: tenant
    access_id: 1000
- bridge: tmp_2
  clab:
    name: eth2
  ifindex: 2
  ifname: 1/1/c2
  linkindex: 2
  mtu: 1234
  type: lan
  vlan:
    access: tenant
    access_id: 1000
- bridge_group: 1
  ifindex: 3
  ifname: svi.1000
  name: VLAN tenant (1000) -> [ce20,mtu1]
  neighbors:
  - ifname: eth1
    ipv4: 172.16.0.3/24
    node: ce20
  - ifname: 1/1/c1
    ipv4: 172.16.0.1/24
    node: mtu1
  type: svi
  virtual_interface: true
  vlan:
    mode: bridge
```
Note how there is no 'epipe' attribute. Also see how the 'mtu' link attribute gets assigned to the lan interface, while the custom link attribute gets put on the vlan interface (when fixed, e.g. by removing the first link)

### Version

netlab version 1.6.1

### Additional context

I wasn't doing IBGP over EBGP this time...
