### ISSUE TITLE
[BUG] Link-level vlan.mode attribute should be used solely to create routed subinterfaces

### ISSUE THREAD

**Issue by ipspace** [ipspace/netlab#878]
### Describe the bug

Overriding **vlan.mode** on an interface/link makes sense only when the VLAN forwarding mode is set to `route`. In all other cases the **vlan.mode** could get ignored once the SVI interface is created (see #868 for details)

### Lab topology

```
defaults.device: eos
module: [ vlan ]

vlans:
  red:
  blue:

nodes:
  s1:
  s2:

links:
- s1:
  s2:
  vlan.access: red
- s1:
  s2:
  vlan.access: red
  vlan.mode: bridge
```
