### ISSUE TITLE
[BUG] Global VLAN mode still leaks into node VLAN data

### ISSUE THREAD

**Issue by ipspace** [ipspace/netlab#881]
### Describe the bug

Even after fixing #874 (or not 🤷‍♂️) there's still a scenario where the VLAN forwarding mode set in global VLAN data is taking precedence over node `vlan.mode`.

### Lab topology

```
defaults.device: frr

module: [ vlan ]
vlans:
  red:
  green:
    mode: route

nodes:
  s1:
  s2:
    vlan.mode: bridge

links:
- s1:
  s2:
  vlan.trunk: [ red, green ]
```

### Expected behavior

VLAN data on S2 is correct:

```
netlab create vm.yml -o yaml:nodes.s2.vlans
green:
  bridge_group: 1
  id: 1001
  mode: bridge
  prefix:
    allocation: id_based
    ipv4: 172.16.1.0/24
red:
  bridge_group: 2
  id: 1000
  mode: bridge
  neighbors:
  - ifname: vlan1000
    node: s2
  - ifname: vlan1000
    ipv4: 172.16.0.1/24
    node: s1
  prefix:
    allocation: id_based
    ipv4: 172.16.0.0/24
```

However, the S2 subinterface for the green VLAN is routed. Even worse, it has no IP address, but also no corresponding VLAN interface.

```
- ifindex: 1
  ifname: eth1
  linkindex: 1
  name: s2 -> s1
  neighbors:
  - ifname: eth1
    node: s1
  subif_index: 2
  type: p2p
- bridge_group: 1
  ifindex: 2
  ifname: eth1.1001
  name: s2 -> s1
  neighbors:
  - ifname: eth1.1001
    ipv4: 172.16.2.1/24
    node: s1
  parent_ifindex: 1
  parent_ifname: eth1
  type: vlan_member
  virtual_interface: true
  vlan:
    access_id: 1001
    mode: route
    routed_link: true
```
