### ISSUE TITLE
[BUG] BGP networks are not originated on nodes with no BGP neighbors

### ISSUE THREAD

**Issue by ipspace** [ipspace/netlab#929]
### Describe the bug

If you have a node running BGP but having no neighbors in an address family, the address family (and the prefixes it should originate) will not be configured on most devices.

The behavior doesn't matter if you're deploying a lab and not adding BGP sessions (who cares if a node with no neighbors has incorrect BGP table), but breaks things if you later add BGP sessions that should advertise the missing prefixes.

### Expected behavior

The **node.bgp.ipv4** or **node.bgp.ipv6** flag should also be influenced by the prefixes (networks) the node should advertise, not just by node's neighbors.

### Lab topology

```
defaults.device: eos

module: [ bgp ]

nodes:
  lb1:
    bgp.as: 65000
```

### Output

```
% ../netlab create test.yml -o yaml:nodes.lb1.bgp
advertise_loopback: true
as: 65000
community:
  ebgp:
  - standard
  ibgp:
  - standard
  - extended
neighbors: []
next_hop_self: true
router_id: 10.0.0.1
```

Note that the **ipv4** flag is not set, so the BGP router configuration will not include the **address-family ipv4** command.

### Version

All netlab versions
