### ISSUE TITLE
Write plugin developer documentation (was: Consistency between topology.nodes[n].links and topology.links)

### ISSUE THREAD

**Issue by jbemmel** [ipspace/netlab#94]
Due to the way https://github.com/ipspace/netsim-tools/blob/master/netsim/augment/links.py#L68 is structured, the topology contains duplicate copies of link attributes (specifically the ip address and any custom attributes)

Consequently, a plug-in that tries to augment the data structure must make modifications in 2 places (or be aware of which data gets put into host_vars)

For example:
```
links:
- type: lan
  prefix: 192.168.1.0/24
  r1:
    ipv4: False
    epipe: r4   # Cannot declare this at top level
  h1:
    ipv4: 1

POST: links=[ ... {'type': 'lan', 'prefix': '192.168.1.0/24', 'r1': {'ipv4': False, 'epipe': 'r4'}, 'h1': {'ipv4': '192.168.1.1/24'}, 'node_count': 2, 'linkindex': 6, 'bridge': 'sr-isis-te_6'} ... ]


POST: nodes={'r1': { ... 'links': [
			  ... 
			 {'ipv4': False, 'epipe': 'r4', 'name': 'r1 -> [h1]', 'linkindex': 6, 'bridge': 'sr-isis-te_6', 'type': 'lan', 'ifindex': 3, 'ifname': '1/1/c3', 'provider_ifname': 'eth3', 'neighbors': {'h1': {'ifname': 'eth1', 'ipv4': '192.168.1.1/24'}}, 'epipe_peer': '10.0.0.2/32'}]},   
```
My plugin resolves the custom 'epipe' attribute with value 'r4' to the loopback IP of that node, and puts it as 'epipe_peer'. For data model consistency, it would be better if this would also update the 'topology.links' data - as it is, there are 2 copies that diverge
