### ISSUE TITLE
[BUG] Nokia SR-OS stub interfaces fail the initial config rendering

### ISSUE THREAD

**Issue by sdktr** [ipspace/netlab#942]
### Describe the bug

Using SR-OS, the initial config template can not be rendered when a 'stub' interface is in the topology.

### To Reproduce

 Use the template from https://blog.ipspace.net/2023/09/ecmp-ospf-unnumbered.html with SR-OS

### Expected behavior

Eighter:
1) the config should render with a stub interface (in Cisco IOS I assume this will produce a loopback?)
2) Render config without the interface at all or
3) some validation error 'a stub interface is not supported by SR-OS'

### Lab topology

Use the template from https://blog.ipspace.net/2023/09/ecmp-ospf-unnumbered.html or this minimalist version:
```yaml
---
provider: clab
defaults:
  device: sros

defaults.devices.sros.clab:
  image: vrnetlab/vr-sros:23.7.R2
  node:
    kind: vr-sros
    type: ixr-ec
    license: ../../sros/license-sros23.3.R3-202310.txt

addressing.p2p.ipv4: True
module: [ ospf ]

nodes: [ r1 ]
links: [ r1 ]
```

### Output

Running `netlab initial -vvv`

```
TASK [debug] *********************************************************************************************************************************************************************************************
task path: /home/sdktr/.local/lib/python3.10/site-packages/netsim/ansible/tasks/deploy-module.yml:40
redirecting (type: filter) ansible.builtin.ipaddr to ansible.netcommon.ipaddr
redirecting (type: filter) ansible.netcommon.ipaddr to ansible.utils.ipaddr
redirecting (type: filter) ansible.builtin.ipv4 to ansible.netcommon.ipv4
redirecting (type: filter) ansible.netcommon.ipv4 to ansible.utils.ipv4
redirecting (type: filter) ansible.builtin.ipv6 to ansible.netcommon.ipv6
redirecting (type: filter) ansible.netcommon.ipv6 to ansible.utils.ipv6
fatal: [r1]: FAILED! => 
  msg: |-
    The task includes an option with an undefined variable. The error was: 'null' is undefined. 'null' is undefined. 'null' is undefined. 'null' is undefined
  
    The error appears to be in '/home/sdktr/.local/lib/python3.10/site-packages/netsim/ansible/tasks/deploy-module.yml': line 40, column 5, but may
    be elsewhere in the file depending on the exact syntax problem.
  
    The offending line appears to be:
  
  
      - debug:
        ^ here
```

### Version

1.6.4-post2

**Comment by sdktr** [comment]
I slighly changed the deploy-module.yml with this ansible task to get a better output of this jinja rendering. 
```yaml
  - name: test template
     ansible.builtin.template:
       src: "{{ config_template }}"
       dest: "./test.txt"
     delegate_to: localhost

**Comment by ipspace** [comment]
The error seems to be here https://github.com/ipspace/netlab/blob/dev/netsim/ansible/templates/initial/sros.j2#L56C48-L56C52 and I'm guessing that the line should be

```
{{ True if l.vrf is defined else "[null]" }}
````

If that fix works for you, please submit a PR, and thanks a million for reporting this one!

**Comment by jbemmel** [comment]
Yes, just some missing quotes. PR submitted

**Comment by sdktr** [comment]
You beat me to it @jbemmel , thanks guys!

This fixes the initial config. Running the same minimalistic topology still fails here though. This time on the OSPF deployment part:

```log
TASK [Update ospf node configuration (using gNMI SET based on YAML template /home/sdktr/.local/lib/python3.10/site-packages/netsim/ansible/tasks/../templates/ospf/sros.j2)] *****************************
FAILED - RETRYING: [r1]: Update ospf node configuration (using gNMI SET based on YAML template /home/proxsys/.local/lib/python3.10/site-packages/netsim/ansible/tasks/../templates/ospf/sros.j2) (2 retries left).
FAILED - RETRYING: [r2]: Update ospf node configuration (using gNMI SET based on YAML template /home/proxsys/.local/lib/python3.10/site-packages/netsim/ansible/tasks/../templates/ospf/sros.j2) (2 retries left).
```

**Comment by sdktr** [comment]
If I change https://github.com/ipspace/netlab/blob/4f71ecf0e82a8eab722f5f12c3cd763cd8d8047b/netsim/ansible/templates/ospf/sros.j2#L17

to
```
   - area-id: "{{ l.ospf.area }}"
     interface:
{%  if l.type not in ['loopback','stub','svi'] %}
       - interface-name: {{ if_name(l.ifname) }}
{%  else %}
       - interface-name: {{ ("stub-"+if_name(l.ifname)) if l.type=='stub' else if_name(l.ifname) }}
{%  endif %}
```
the OSPF deployment goes through. I'm now repeating logic from the initial/sros.j2 though. We propably need a better way:
- add the naming logic as a seperate marco in inital/sros.j2
- import that macro in ospf?

Additionally: why is this naming logic not in the 'core' of netlab? Is it the responsibility of the platform/OS specific logic to decide how a loopback should be named?

**Comment by sdktr** [comment]
Now, answering my own 2nd and 3rd question:
There actually is a shared macro in the initial config that is used for interface naming. [This macro](https://github.com/ipspace/netlab/blob/4f71ecf0e82a8eab722f5f12c3cd763cd8d8047b/netsim/ansible/templates/initial/sros.j2#L1) is called for non-stub interfaces, but not for stubs, as far as I can tell.

Next step: figuring out why stubs don't get the naming convention right in the initial config.
```yaml
#netlab topology, stub and non-stub interface
- bridge: ml_3_3
  clab:
    name: eth3
  ifindex: 3
  ifname: 1/1/c3
  ipv4: 172.16.0.1/24
  linkindex: 3
  mtu: 1500
  name: r1 -> stub
  neighbors: []
  ospf:
    area: 0.0.0.0
    passive: true
  type: stub
loopback:
  ipv4: 10.0.0.1/32
- clab:
    name: eth2
  ifindex: 2
  ifname: 1/1/c2
  ipv4: true
  linkindex: 2
  mtu: 1500
  name: r1 -> r2
  neighbors:
  - ifname: 1/1/c2
    ipv4: true
    node: r2
  ospf:
    area: 0.0.0.0
    network_type: point-to-point
    passive: false
  type: p2p
```
Config after deployment has:
```
 "i1/1/c2"
 "stub-1/1/c3"
 "system"
```
OSPF module tries to patch these interface names:
```
 "i1/1/c2"
 "stub-i1/1/c3"
 "system"
```
