### ISSUE TITLE
[probably-a-BUG] Link custom attributes not preserved after vlan transformation

### ISSUE THREAD

**Issue by ssasso** [ipspace/netlab#977]
### Describe the bug

It seems that, after *vlan transformation*, custom link attributes are not preserved.

### To Reproduce

Topology:

```
provider: clab

defaults.device: arubacx

# Define custom data for lag
defaults.attributes.link.lag_id: int

module: [ vlan, vrf ]

vrfs:
  tenant:

vlans:
  red:
    vrf: tenant

nodes:
  sw1:
  sw2:

links:
- sw1:
  sw2:
  lag_id: 1
  vlan.access: red

- sw1:
  sw2:
  lag_id: 1
```

### Expected behavior

Given the above topology, and taking as example the file `host_vars/sw1/topology.yml` (copying only the relevant part), I would expect to find the `lag_id` attribute on both the two interfaces.
Instead, it is present only on the interface without the vlan information.

```
interfaces:
- bridge: test2_1
  clab:
    name: eth1
  ifindex: 1
  ifname: 1/1/1
  linkindex: 1
  mtu: 1500
  type: lan
  vlan:
    access: red
    access_id: 1000
- clab:
    name: eth2
  ifindex: 2
  ifname: 1/1/2
  ipv4: 10.1.0.1/30
  lag_id: 1
  linkindex: 2
  mtu: 1500
  name: sw1 -> sw2
  neighbors:
  - ifname: 1/1/2
    ipv4: 10.1.0.2/30
    node: sw2
  type: p2p
- bridge_group: 1
  ifindex: 3
  ifname: vlan1000
  ipv4: 172.16.0.1/24
  name: VLAN red (1000) -> [sw2]
  neighbors:
  - ifname: vlan1000
    ipv4: 172.16.0.2/24
    node: sw2
    vrf: tenant
  type: svi
  virtual_interface: true
  vlan:
    mode: irb
  vrf: tenant
```

### Additional context

I know it may seems a "nonsense" to have a vlan declared on a physical interface that will be part of a lag, but I expect to use a custom config template and "inherit" the vlan attributes for the lag from the first physical interface assigned to it.

**Comment by jbemmel** [comment]
Consider what would happen here:
```
links:
- sw1:
  sw2:
  lag_id: 1
  vlan.access: red
links:
- sw2:
  sw3:
  lag_id: 2
  vlan.access: red
```

The problem is that VLANs (on the 'industry standard boxes at least') are global objects. So if multiple links have the same vlan, which attribute do you pick?

It used to be the first interface, but that's kind of arbitrary, so I believe we ended up with "don't do that".
Ivan can add more color
